### ISSUE TITLE
Post messages with full width using sections

### ISSUE THREAD

**Issue by peimanja** [slack-go/slack#1001]
### Description
More of a question! I'm struggling to post messages with full width when using sections

![image](https://user-images.githubusercontent.com/18074432/142751939-3e48144b-d96b-44ee-b982-999e2990b50c.png)

I could not find an example posting message with Rich Text and could not get that to work.

**Comment by kanata2** [comment]
This is slack's design  as far as I know, so we cannot set width via API.
