### ISSUE TITLE
How to update a message?

### ISSUE THREAD

**Issue by ZhangDewei** [slack-go/slack#1024]
### Description

I can postMessage, but how can i update a message?

**Comment by brainexe** [comment]
On slack.PostMessage call you get the msgTimestamp as 2nd return value of your initial message.

This msgTimestamp can be used to update the given message :)

```go
slackClient.PostMessage(
    channelID,
    slack.MsgOptionText("text", false),
    slack.MsgOptionUpdate(msgTimestamp),
)
```


then it will call the [chat.update](https://api.slack.com/methods/chat.update) method automagically.

**Comment by kanata2** [comment]
Thanks @brainexe!
