### ISSUE TITLE
Omitempty prevents setting replace_original to false

### ISSUE THREAD

**Issue by wojtkiewicz** [slack-go/slack#1063]
### What happened

At the moment it's impossible to send `replace_original: false` in WebhookMessage because of `omitempty`.
This would be fine if `replace_original` was set to `false` by default. Unfortunately it's not.

### Expected behavior

It should be possible to set `replace_original: false` from slack-go.

### Steps to reproduce

```
import (
	"encoding/json"
	"fmt"
)

type WebhookMessage struct {
	ReplaceOriginal bool `json:"replace_original,omitempty"`
}

func main() {
        msg := &WebhookMessage{
		ReplaceOriginal: false,
	}
	out, _ := json.Marshal(msg)
	fmt.Println(string(out))
}

// produces {}

```

### Versions
- Go: any
- slack-go/slack: 0.10.3

**Comment by kanata2** [comment]
Resolved by #1122
