### ISSUE TITLE
Calling conversations.unarchive returns not_in_channel error

### ISSUE THREAD

**Issue by llamahunter** [slack-go/slack#1066]
### What happened

Called client.UnarchiveConversationContext() on an archived channel, but got a 'not_in_channel' error, which isn't even listed as a valid error on https://api.slack.com/methods/conversations.unarchive

### Expected behavior

Channel is unarchived and caller is added to channel

### Steps to reproduce

1. archive a channel
2. call client.UnarchiveConversationContext on the channel

#### reproducible code

see https://github.com/pablovarela/terraform-provider-slack/blob/master/slack/resource_conversation.go#L247

### Versions
- Go: 1.16
- slack-go/slack: v0.10.2

**Comment by kanata2** [comment]
Please could you try to use User Token instead of Bot Token?
Actually it seems that this is Slack's undocumented specification.

See also: https://stackoverflow.com/questions/63361079/slack-webapi-conversations-unarchive-fails-with-not-in-channel

**Comment by llamahunter** [comment]
> https://stackoverflow.com/questions/63361079/slack-webapi-conversations-unarchive-fails-with-not-in-channel

Err... that seems like a somewhat egregious bug in the slack api?  Why can't bots unarchive channels?
