### ISSUE TITLE
Channel does not have a `NumMembers`/`num_members` field

### ISSUE THREAD

**Issue by dvdplm** [slack-go/slack#109]
Just noticed that Slack does not expose a `num_members` (maybe they used to?) but `slack.Channel` has that field so it's always set to 0 which is surprising. Can we remove it?

**Comment by nlopes** [comment]
That's a good point. I'm most likely doing a sprint this weekend on the library so I'll look into this and remove if appropriate. Thanks for raising.

**Comment by dvdplm** [comment]
Let me know if you want a PR for it!

**Comment by nlopes** [comment]
Just removed this in https://github.com/nlopes/slack/commit/f1b061d99e7405d5f83e0b437fac0e1689f8852f

Thanks!
