### ISSUE TITLE
API returns int64 for "timestamp" in RichTextSectionDateElement.

### ISSUE THREAD

**Issue by rusq** [slack-go/slack#1104]
### What happened
API returns timestamp as int64 type for "RichTextSectionDateElement" and json parsing fails. 

### Expected behavior
The API response is correctly Unmarshalled into RichTextSectionDateElement.

### Steps to reproduce
Attached is the archive with the API output and a main.go program that, if executed, reproduces the error.

The attached archive contains also `bug119-r.json` which is the raw output from the API with the PII removed.

#### reproducible code
[rich_text_date_issue.zip](https://github.com/slack-go/slack/files/9444032/rich_text_date_issue.zip)

#### manifest.yaml
manifest WHO?

### Versions
- Go: go version go1.19 darwin/amd64
- slack-go/slack: v0.11.2

### Comments

I'm not sure how to go about this - has there been an instance where timestamp is string for this RichText block element?

Original issue link: https://github.com/rusq/slackdump/issues/119

**Comment by rusq** [comment]
Possibly `JSONTime` will do the trick? (an additional branch for when input is a number would be needed)

**Comment by rusq** [comment]
Hey team, any chance this can be looked at?

**Comment by kanata2** [comment]
It will be fixed in v0.12.
