### ISSUE TITLE
API returns "null" for file timestamp

### ISSUE THREAD

**Issue by rusq** [slack-go/slack#1107]
### What happened
API returns `null` for the file "timestamp" field (sample raw api output in the attached zip file)

```
bug109$ go run .                                                                                                                                           
2022/08/31 17:26:07 strconv.Atoi: parsing "null": invalid syntax
exit status 1
```
### Expected behavior
Null values are expected to be treated gracefully.

### Steps to reproduce
See attached zip file: 
[json-unmarshal-issue.zip](https://github.com/slack-go/slack/files/9459650/json-unmarshal-issue.zip)

#### reproducible code
See attached zip file: 
[json-unmarshal-issue.zip](https://github.com/slack-go/slack/files/9459650/json-unmarshal-issue.zip)

#### manifest.yaml
Yes, please.

### Versions
- Go: 1.19 darwin/amd64
- slack-go/slack: v0.11.2

Original issue: https://github.com/rusq/slackdump/issues/109

**Comment by rusq** [comment]
#1106 fixes it, if merged

**Comment by kanata2** [comment]
Thanks for reporting. I'll confirm later.
(Please use Gist instead of zip😢)

**Comment by kanata2** [comment]
@
