### ISSUE TITLE
Add ChannelJoined event type

### ISSUE THREAD

**Issue by treeder** [slack-go/slack#111]
When a bot joins a channel, would be good to have this event type: 
https://api.slack.com/events/channel_joined

**Comment by dlsniper** [comment]
Hi @treeder,

I can see the event here: https://github.com/nlopes/slack/blob/master/websocket_managed_conn.go#L369 can you please let me know if this is what you are looking for?
I think this can be closed but not sure if it's correct or not.
Thank you.

**Comment by treeder** [comment]
Hi @dlsniper , I can't even remember anymore. I'll reopen if I come across this again.
