### ISSUE TITLE
text width in attachments

### ISSUE THREAD

**Issue by riza-awang** [slack-go/slack#1110]
### What happened
the message is truncated, no more than 80 characters
<img width="638" alt="Screen Shot 2022-09-07 at 01 10 20" src="https://user-images.githubusercontent.com/96410563/188708160-39a52018-838d-47dc-ac4c-ca137a386bae.png">

### Expected behavior
the message is not truncated. 
<img width="1358" alt="Screen Shot 2022-09-07 at 01 10 51" src="https://user-images.githubusercontent.com/96410563/188708223-6d2e0560-4458-4d03-9854-4a85b3b68f31.png">

### Steps to reproduce
create long string
```
attachment := slack.Attachment{
	Pretext:
	"*something1something2something3something4something5something6something7something8something9*\n"+
	"```+------------+-------------------+-------------+-------------+-----------------+-------------+\n"+
	"| Column A | Column B | Column C | Column D | Column E | Column F | Column G | Column H | Column I |\n"+
	"+------------+-------------------+-------------+-------------+-----------------+-------------+```\n"+
""}
```
### Versions
- Go: go1.17.5 darwin/arm64
- slack-go/slack: v0.11.2

**Comment by kanata2** [comment]
This is slack's specification and is not related to slack-go. Please use text instead of attachments.
