### ISSUE TITLE
RTM: Connection drops every few days

### ISSUE THREAD

**Issue by preethi-d** [slack-go/slack#1124]
### What happened
slack app unresponsive every few days, even though service running. Upon viewing logs we can see this

<img width="810" alt="Screen Shot 2022-11-07 at 10 53 02 AM" src="https://user-images.githubusercontent.com/39286006/200218636-3400afbe-5842-458e-9fe2-5f3a4fb7cd24.png">

not sure how to fix this, as the handleEvents() method should by right handle disconnect events gracefully and reconnect right?

### Expected behavior
if disconnect happens, handleEvent() should help reconnect. we need not add our own check and retry on our end, as it is not advised to call 'rtm.ManageConnection()' more than once.

### Versions
- Go: 1.17
- slack-go/slack: v0.11.0

**Comment by kanata2** [comment]
dup of #1101

**Comment by preethi-d** [comment]
hi @kanata2 neither this nor the other ticket are completed actually, stil having this issue and unable to understand why. Appreciate any help thanks! 

This ticket shows some of the logs we get before the connection seems to drop.
