### ISSUE TITLE
MessageEvent not triggering

### ISSUE THREAD

**Issue by xackery** [slack-go/slack#114]
It appears on the slack API documentation it talks about subscribing to channels to get information, however, when I run this package, doing the examples/websocket/websocket.go code with minor modifications, I never see the `case *slack.MessageEvent:` line trigger. I'm trying to figure out if there's a step to make this happen.. you can't make a bot join the channel.. So..

**Comment by ujj** [comment]
It appears I am facing a similar issue. We use this library to run our bot that the user can interact with over direct messages. On some occasions (1 in 10), we are simply not getting the direct messages in `case *slack.MessageEvent:`. While this is happening, if the bot is added to a channel then we receive the channel messages without any problems but the direct messages just don't seem to come. Any pointers here would be really appreciated.

**Comment by james-lawrence** [comment]
closing due to age.
