### ISSUE TITLE
Unmarshalling attachment struct literal fails if "ts" field present.

### ISSUE THREAD

**Issue by ddombrow** [slack-go/slack#115]
I believe (new to golang so pardon if I'm just being stupid), that now that "ts" in the Attachment struct is of type json.Number, you can no longer pass a PostMessageParamaters struct that contains attachments with the ts field to the post message call.  It will fail on unmarshalling the attachments.

Illustrative go playground on what I am seeing (simplified):
https://play.golang.org/p/R5EivlvQRn

**Comment by mlabouardy** [comment]
you should use interface{} instead of json.Number and then do conversion manually or reassign json.Number value to a new one right after Unmarshalling.

Example:

```
type Message struct {
  Ts interface{}
}
...

message := Message{
  Ts: time.Now().Unix(),
}
attachment := &slack.Attachment{
  Title:     "Example",
  Ts:         message.Ts.(json.Number),
}
```

**Comment by james-lawrence** [comment]
closing due to age.
