### ISSUE TITLE
replace gorilla/websocket dependency which is no longer maintained

### ISSUE THREAD

**Issue by jfatta** [slack-go/slack#1154]
### Description

slack-go/slack [uses](https://github.com/slack-go/slack/search?q=%22github.com%2Fgorilla%22) `github.com/gorilla/websocket` which is no longer maintained now according to:
https://github.com/gorilla#gorilla-toolkit

It would be useful to replace this dependency with a maintained module for security purposes initially.

**Comment by kanata2** [comment]
@jfatta Do you know any other modules which is maintaned?

**Comment by ehakan** [comment]
There is [nbio](https://github.com/lesismal/nbio). Has websockets, integrates with stdlib and projects like echo, gin, go-chi.
