### ISSUE TITLE
CloudQuery Source Plugin?

### ISSUE THREAD

**Issue by yevgenypats** [slack-go/slack#1159]
Hi Team, hopefully this is right place to ask, if not, I'd appreciate if you can direct me.

I'm the founder of [cloudquery.io](https://www.cloudquery.io/), a high performance open source ELT framework. 

Our users are asked for a [Slack source plugin](https://www.cloudquery.io/docs/plugins/sources/slack/overview), and we already shipped a first version.

As we have limited capacity to maintain all plugins, we are usually looking for the official vendor to help maintain it (similar to terraform provider).

I was curious if this would be an interesting collaboration, where we can help with the initial version (already implemented) and you will help maintain it?

This will give your users the ability to sync/ELT Slack APIs to any of their datalakes/data-warehouses/databases easily using any of the growing list of CQ [destination plugins](https://www.cloudquery.io/docs/plugins/destinations/overview).

Best,
Yevgeny

**Comment by kanata2** [comment]
@yevgenypats 
Hi, thanks for your suggestion.
Let me ask one question first.
Is the plugin implemented in the Go language and is it using the slack-go/slack?
If so, I would appreciate if you could send me an e-mail for further discussion.

**Comment by yevgenypats** [comment]
Hi @kanata2! Yes, the plugin is in Go and using the `slack-go/slack` library, It is located here right [now](https://github.com/cloudquery/cloudquery/tree/main/plugins/source/slack)

Following up via email now.
