### ISSUE TITLE
Error starting the application

### ISSUE THREAD

**Issue by henriquechehad** [slack-go/slack#116]
Returned the error when tried to start the application, the second try worked.

```Invalid credentialspanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x55fa094141d5]

goroutine 12 [running]:
panic(0x55fa099da220, 0xc42000c050)
    /usr/lib/go/src/runtime/panic.go:500 +0x1a5
github.com/golang.org/x/net/websocket.(*Conn).SetWriteDeadline(0x0, 0xecfaec8ba, 0x55fa1492367a, 0x55fa09db18e0, 0xc4203f1900, 0x0)
    /go/src/github.com/golang.org/x/net/websocket/websocket.go:279 +0x45
github.com/github.com/nlopes/slack.(*RTM).connect(0xc4201c6900, 0x1, 0x8, 0x55fa096229ac, 0xb, 0x0)
    /go/src/github.com/github.com/nlopes/slack/websocket_managed_conn.go:94 +0x268
github.com/github.com/nlopes/slack.(*RTM).ManageConnection(0xc4201c6900)
    /go/src/github.com/github.com/nlopes/slack/websocket_managed_conn.go:32 +0x46
```

Searching I also found this issue in other project that uses the slack lib:
https://github.com/erroneousboat/slack-term/issues/36

**Comment by nlopes** [comment]
Gah! Will take a look. Thanks for the heads up!

**Comment by kodieGlosser** [comment]
@nlopes we are also seeing an error starting the application. It seems to only happen with 1 specific slack key we are using. It works sometimes, but most of the time it fails. Here is what I see:

```
panic: post: json: cannot unmarshal number into Go value of type string

goroutine 1 [running]:
panic(0x6f4300, 0xc420109cd0)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
```

It is making the call to NewSlackBot with the slack token. Ideas?

**Comment by gondor** [comment]
@kodieGlosser did you ever figure this out?  I'm getting the same

**Comment by kodieGlosser** [comment]
@gondor no I haven't. It seems to come and go. I even regenerated my slack key, which seem to help some.

**Comment by james-lawrence** [comment]
closing due to age.
