### ISSUE TITLE
Fetching file attachments

### ISSUE THREAD

**Issue by kirill-artamonov-form3** [slack-go/slack#1160]
### Description

We have emails sent to a Slack channels.
Those email have attachments that we want to read via API.

With `GetConversationHistory` and `ListFiles`, we have a link to download the email, but not the attachment.

### (Optional) Slack's documentation

Somehow it's [not documented on for a file type](https://api.slack.com/types/file), but when examining JSON responses from Slack for both calls, I see that there's `attachments` attribute on the `file` object containing the link that we need.

**Comment by kanata2** [comment]
@kirill-artamonov-form3 
Please see Python, Node or Java SDK. If this field is added in these SDKs, you can assume that it is officially supported it, even if not documented.
