### ISSUE TITLE
How do i get the message  corresponding a specific reaction event

### ISSUE THREAD

**Issue by wiyr** [slack-go/slack#117]
The method `GetReactions` doesn't return message object but slack api [support](https://api.slack.com/methods/reactions.get). So how do I  get total message when i receive a `reaction_added`  event ?   Any other method can do this ?

**Comment by blakeandrewwood** [comment]
I'm wondering this too. I can get the Reference Item, but can't figure out how to get the actual message.

**Comment by brenns10** [comment]
You're right, the part of the code that extracts the `reactions.get` API response seems to ignore everything that isn't the list of reactions, including the message details. Kind of silly, but it looks like there are workarounds.

Using [channels.history](https://api.slack.com/methods/channels.history) you can retrieve an event by its timestamp. The Slack API docs have a section on how to do exactly that. The docs even say:

> Messages that have been reacted to by team members will have a reactions array delightfully included.

Which makes the `reactions.get` endpoint seem a little bit superfluous :stuck_out_tongue:.

Anyway depending on your use case you may want to be caching `message` events anyway, and then updating them as events come in. Then you can look up the message in your local cache before falling back to the history command. Just a thought!
