### ISSUE TITLE
Possibility to extend the API?

### ISSUE THREAD

**Issue by davesnx** [slack-go/slack#119]
Hello @nlopes,

First of all, great work with this client, seems pretty nice 👍.
I'm opening this issue because I'm interested in extend the API for example of channels, creating a method `getCurrentChannels` or methods build on top of the Slack API. 

In order to increase the usability and keep all the "module" the pure operations that you can do to get info of Slack.

What do you think?

Thanks!

**Comment by nlopes** [comment]
Sounds good but using your `getCurrentChannels` as an example, how would that be different from `GetChannels`?
