### ISSUE TITLE
Error while installing flutterfire cli via terminal

### ISSUE THREAD

**Issue by Sri-Geyan** [slack-go/slack#1226]
After installing 624 packages by running (npm install -g firebase-tools),I was not able to run (dart pub global activate flutterfire_cli)
![Screenshot (5)](https://github.com/slack-go/slack/assets/73470830/b3f6871f-3168-4507-b1a8-a64e2c601926)
I have tried changing from sdk: '>=2.10.0 <3.0.0' to sdk: '>=2.17.3 <3.0.0' in pubspec.yaml,updated dart to the latest stable release and add the flutter path in system variable environment but still the above mentioned error code occurs,It would be helpful if someone assists me on rectifying this error and on installing flutterfire cli

**Comment by lorenzoaiello** [comment]
@Sri-Geyan I think you may have opened this in the wrong repository.
