### ISSUE TITLE
Add support Custom profile fields

### ISSUE THREAD

**Issue by Tozapid** [slack-go/slack#1241]
### Description

It will be great if we add support for custom profile fields

### (Optional) Slack's documentation

API: https://api.slack.com/methods/users.profile.set

**Comment by wolveix** [comment]
@Tozapid this is already possible:

```go
err := slackUserClient.SetUserCustomFields(userId, map[string]slack.UserProfileCustomField{
	fieldId: {
		Value: fieldValue,
	},
})
```
