### ISSUE TITLE
no desktop_notification at eventMapping

### ISSUE THREAD

**Issue by Pechenn** [slack-go/slack#125]
no desktop_notification at eventMapping

**Comment by karl-gustav** [comment]
My suggestion would be that the library didn't notify you if it got an event it didn't understand. I don't wan't to have my error log filled with stuff every time slack adds a new type of event, it's not like the new event is going to change the behavior of my existing application one bit.

**Comment by jBugman** [comment]
This particular issue is fixed in #173.
Anyway, I agree with that it would be nice to not be spammed with not supported events, or maybe only in debug logging level.
