### ISSUE TITLE
 file_input feature support in slack-go

### ISSUE THREAD

**Issue by kbxadu** [slack-go/slack#1268]
it seems slack-go doesn't have the file_input feature, which is talked about in the Slack API docs https://api.slack.com/reference/block-kit/block-elements#file_input. I'm trying to build a Slack bot that allows file uploads. Is this feature supported, or are there plans to implement it in the future?

**Comment by parsley42** [comment]
The Slack Go library is maintained by volunteers, and currently there's nobody putting much time into it except for fairly trivial updates. If you create a PR and it doesn't include breaking changes, I can probably have a look at it.

**Comment by devlife20** [comment]
got it

**Comment by 0xArch3r** [comment]
this file input block is currently in this repo, i used it recently.

https://github.com/slack-go/slack/blob/d2493facbd56df23ea8d633fe1bf9c4c4c80d77f/block_element.go#L650
