### ISSUE TITLE
files.upload is getting deprecated by Slack

### ISSUE THREAD

**Issue by DestroyerAlpha** [slack-go/slack#1287]
### Description
Check if we are using slack's file.upload API and migrate to newly suggested API for uploading files in slack.
### (Optional) Slack's documentation
https://api.slack.com/methods/files.upload
files.upload is deprecated and will stop functioning on March 11, 2025. Use [files.getUploadURLExternal](https://api.slack.com/methods/files.getUploadURLExternal) and [files.completeUploadExternal](https://api.slack.com/methods/files.completeUploadExternal) to upload files instead. Newly created apps will be unable to use files.upload beginning May 8, 2024. See [Uploading files](https://api.slack.com/messaging/files#uploading_files) for more details on the process and [this changelog](https://api.slack.com/changelog/2024-04-a-better-way-to-upload-files-is-here-to-stay) for more on the deprecation.

**Comment by lorenzoaiello** [comment]
@DestroyerAlpha  , There are currently two methods available in this package (`UploadFileV2` and `UploadFileV2Context`) which should provide a path forward which require no token scope changes to transition to.

I'm not sure how many people are going to be affected or if there is interest in updating the existing `UploadFile` method to call `UploadFileV2` under the hood to not break existing applications.
