### ISSUE TITLE
conversations.history unmarshall bug

### ISSUE THREAD

**Issue by nitzan-entro** [slack-go/slack#1292]
### What happened

getting this from the sdk:
"cannot unmarshal number into Go struct field Attachment.messages.attachments.color of type string"

### Expected behavior

unmarshall ok.

### Versions
- Go: 1.22
- slack-go/slack: 0.12.0

**Comment by lorenzoaiello** [comment]
@nitzan-entro I tried to reproduce your issue locally but am having a hard time. Can you please a code sample to reproduce the issue or provide more information on how to reproduce the issue (eg what kind of attachment)?

Thanks
