### ISSUE TITLE
Events API Reconciliation

### ISSUE THREAD

**Issue by lorenzoaiello** [slack-go/slack#1304]
### Description
There are quite a few event types that are missing from [inner_events.go](https://github.com/slack-go/slack/blob/master/slackevents/inner_events.go). It would be great if someone could go through and reconcile the list and add any missing events.

### (Optional) Slack's documentation
https://api.slack.com/events?filter=Events

**Comment by Aryakoste** [comment]
Hello @lorenzoaiello I would like to work on this issue.

**Comment by Aryakoste** [comment]
https://api.slack.com/events?filter=Events. I will have to go through events in this link right. And if not available add it in the inner_events file right.

**Comment by lorenzoaiello** [comment]
> https://api.slack.com/events?filter=Events. I will have to go through events in this link right. And if not available add it in the inner_events file right.

Yes, that's right. You'll also want to add appropriate tests for any events you add, but if you want to put up a draft PR early on, I can provide some feedback early on.
