### ISSUE TITLE
GetChannelHistory only retrieving last message posted on channel

### ISSUE THREAD

**Issue by jmhossler** [slack-go/slack#139]
I'm trying to get a history of messages for a channel. 

`package main

import (
	"fmt"
	"github.com/nlopes/slack"
	"io/ioutil"
	"strings"
)

func main() {
	token, err := ioutil.ReadFile("bot_token")
	check(err)
	str_token := strings.TrimSpace(string(token))
	fmt.Printf("Token: %s\n", string(str_token))
	api := slack.New(string(str_token))
	channels, err := api.GetChannels(true)
	check(err)
	bot_id := getChannelIDFromName(channels, "bot")
	fmt.Println(bot_id)
	// msg_params := slack.PostMessageParameters{}
	hst_params := slack.HistoryParameters{}
	history, err := api.GetChannelHistory(bot_id, hst_params)
	check(err)
	fmt.Println(history)
	for _, message := range history.Messages {
		fmt.Println(message.Text)
	}
}

func getChannelIDFromName(channels []slack.Channel, name string) string {
	for _, channel := range channels {
		if channel.Name == name {
			return channel.ID
		}
	}
	return ""
}

func check(e error) {
	if e != nil {
		panic(e)
	}
}
`

The output from fmt.Println(history): 
'&{ [{{message  U17RLSCLA Hello World 1487703863.000191 false [] [] <nil>  false     <nil>      [] <nil> false <nil>  0  []} <nil>}] true}`
This is despite the fact that there is actually a long history, and running the example command from the slack api doc returns many more messages.

Am I setting something up incorrectly?

**Comment by Davejkane** [comment]
Instead of this `hst_params := slack.HistoryParameters{}`
try `hst_params := slack.NewHistoryParameters()`, that will set reasonable defaults that should help you out.

**Comment by james-lawrence** [comment]
closing due to age.
