### ISSUE TITLE
Enterprise grid support

### ISSUE THREAD

**Issue by rrufus** [slack-go/slack#140]
With slack's change to supporting enterprise with links across multiple slack teams, some parts of https://api.slack.com/enterprise-grid may need to be addressed if enterprise grid support is required for this library.

Listed in the link for RTM specifically:
- Support events & messages containing user IDs beginning with W
- Support users from other teams in shared channels
- Support duplicate message deliveries in shared channels when installed on multiple teams

**Comment by james-lawrence** [comment]
I've tested these there isn't anything that needs to be done, as long as you only run 1 RTM connection.

I've only had issues with looking up user information if a user exists only in a shared channel.

**Comment by james-lawrence** [comment]
Going to close unless someone runs into an issue they think requires changes to the library.
