### ISSUE TITLE
Set port of websocket for RTM

### ISSUE THREAD

**Issue by acomagu** [slack-go/slack#143]
Hi.
I tried to connect RTM on Heroku but it fails because all web apps on there must listen on the specified port by $PORT environment variable.
- [Runtime Principles | Heroku Dev Center](https://devcenter.heroku.com/articles/runtime-principles#web-servers)
- [Using WebSockets on Heroku with Go | Heroku Dev Center](https://devcenter.heroku.com/articles/go-websockets)

Now this library listens only 80 or 443 for RTM. This can be solved?

**Comment by server-may-cry** [comment]
Hi @acomagu 
your server as client connect across websocket to slack server
you don't need to listen on any port (watch example off [websocket](/nlopes/slack/blob/master/examples/websocket/websocket.go))
[slack doc rtm](https://api.slack.com/rtm)
In heroku if you don't need to handle any http requests, you must specify process as worker (not web) in `Prockfile` [devcenter.heroku.com](https://devcenter.heroku.com/articles/procfile)

**Comment by acomagu** [comment]
Oh, it's really helpful for me!
Thank you @server-may-cry .
