### ISSUE TITLE
rtm.GetInfo().Groups won't get updated if new group is created

### ISSUE THREAD

**Issue by uwehdaub** [slack-go/slack#144]
I recognized that rtm.GetInfo().Groups won't get updated during an existing web socket connection.
During an existing connection I created a new group in my slack team and it doesn't show up in the Info structure. Is this intended behavior?

**Comment by brenns10** [comment]
While I'm not the original author, this seems to be the intended behavior. `GetInfo()` only returns the information that was given on startup through the websocket. You can handle the events `group_ joined` and `group_left` (most likely) to keep your list up-to-date. However if you try that, you'll notice that the RTM API doesn't send a full `Group` structure in those events, which is probably why the library doesn't automatically handle and update the information struct.

**Comment by uwehdaub** [comment]
Hi, @brenns10 
thanks for the info.
