### ISSUE TITLE
Get timestamp of sent message

### ISSUE THREAD

**Issue by hacdias** [slack-go/slack#158]
That's it: how to get the timestamp of a sent message? That's really easy using the NodeJS sdk and I can't find how to do it here.

**Comment by hacdias** [comment]
Just found out that using the AckMessage in the IncomingMessages we can get get the Timestamp 😄 
The thing is that in NodeJS we can add a callback which simplifies the process.

Thanks!

**Comment by dlsniper** [comment]
Can you please explain the use-case? If it's the timestamp of the message your code is sending then you can use time.Now().Unix(), no? Thank you.

**Comment by hacdias** [comment]
It's the timestamp to use to create a Thread. Not sure if using time.Now().Unix() would work
