### ISSUE TITLE
json unmarshal error when starting RTM with wrong credentials

### ISSUE THREAD

**Issue by Wiwiweb** [slack-go/slack#17]
``` go
slackApi = slack.New("a-wrong-key")
slackApi.SetDebug(true)
_, err := slackApi.StartRTM("", "http://example.com")
if err != nil {
    log.Printf("Error starting RTM: %s", err)
}
```

```
2015/05/13 12:15:26 {"ok":false,"error":"invalid_auth"}
2015/05/13 12:15:26 Error starting RTM: json: cannot unmarshal string into Go value of type slack.SlackWSError
```

The response returned by Slack is `{"ok":false,"error":"not_authed"}`
[This line](https://github.com/nlopes/slack/blob/master/misc.go#L71) then tries to parse that as a `infoResponseFull` and fails, which causes the error above.

**Comment by nlopes** [comment]
I haven't forgotten about this but it's trickier than it seems to fix this properly. Because this doesn't affect people using a correct key, I will spend more time thinking how to fix it.

Thanks for the report.

**Comment by nlopes** [comment]
With the latest changes, you'll be able to check for this scenario very easily.
Check https://github.com/nlopes/slack/blob/nlopes-breaking-changes/examples/websocket/websocket.go#L43
