### ISSUE TITLE
Run in a scratch container

### ISSUE THREAD

**Issue by mumblez** [slack-go/slack#171]
Hi,

Not really a bug, maybe a feature request or advice on how I can accomplish building a binary with this library to run in a scratch container, works fine in alpine or any other distro just not scratch, I've set the http client and used a custom transport with included ca ssl certs, but it seems to fail when an rtm connection is created, I assume the rtm connection is using the same http client?

If not, any advice is much appreciated, thanks for the great library.

**Comment by dlsniper** [comment]
Hi, can you please explain what error you have? I use the library in a container with the RTM API and haven't had any issue with it. Thank you

**Comment by mumblez** [comment]
I only have a problem in a 'scratch' container, it's based on this example - https://github.com/nlopes/slack/blob/master/examples/websocket/websocket.go

Hangs at rtm.IncomingEvents, with debug turned on I get the following auth errors (but works in non-scratch containers)

`slack bot ready for requests...
slack-bot: 2017/07/02 08:53:13 misc.go:79: parseResponseBody: {"ok":false,"error":"not_authed"}
slack-bot: 2017/07/02 08:53:13 slack.go:86: reconnection 2 failed: not_authed
slack-bot: 2017/07/02 08:53:13 slack.go:92:  -> reconnecting in 100ms
slack-bot: 2017/07/02 08:53:14 misc.go:79: parseResponseBody: {"ok":false,"error":"not_authed"}
slack-bot: 2017/07/02 08:53:14 slack.go:86: reconnection 3 failed: not_authed
slack-bot: 2017/07/02 08:53:14 slack.go:92:  -> reconnecting in 143.771418ms
slack-bot: 2017/07/02 08:53:14 misc.go:79: parseResponseBody: {"ok":false,"error":"not_authed"}
slack-bot: 2017/07/02 08:53:14 slack.go:86: reconnection 4 failed: not_authed
slack-bot: 2017/07/02 08:53:14 slack.go:92:  -> reconnecting in 227.391249ms
slack-bot: 2017/07/02 08:53:14 misc.go:79: parseResponseBody: {"ok":false,"error":"not_authed"}
slack-bot: 2017/07/02 08:53:14 slack.go:86: reconnection 5 failed: not_authed
slack-bot: 2017/07/02 08:53:14 slack.go:92:  -> reconnecting in 580.776151ms
slack-bot: 2017/07/02 08:53:15 misc.go:79: parseResponseBody: {"ok":false,"error":"not_authed"}
slack-bot: 2017/07/02 08:53:15 slack.go:86: reconnection 6 failed: not_authed
slack-bot: 2017/07/02 08:53:15 slack.go:92:  -> reconnecting in 198.455528ms
slack-bot: 2017/07/02 08:53:15 misc.go:79: parseResponseBody: {"ok":false,"error":"not_authed"}
slack-bot: 2017/07/02 08:53:15 slack.go:86: reconnection 7 failed: not_authed
slack-bot: 2017/07/02 08:53:15 slack.go:92:  -> reconnecting in 585.209689ms
slack-bot: 2017/07/02 08:53:16 misc.go:79: parseResponseBody: {"ok":false,"error":"not_authed"}
slack-bot: 2017/07/02 08:53:16 slack.go:86: reconnection 8 failed: not_authed
slack-bot: 2017/07/02 08:53:16 slack.go:92:  -> reconnecting in 710.907969ms
slack-bot: 2017/07/02 08:53:17 misc.go:79: parseResponseBody: {"ok":false,"error":"not_authed"}
slack-bot: 2017/07/02 08:53:17 slack.go:86: reconnection 9 failed: not_authed
slack-bot: 2017/07/02 08:53:17 slack.go:92:  -> reconnecting in 3.921580629s
slack-bot: 2017/07/02 08:53:21 misc.go:79: parseResponseBody: {"ok":false,"error":"not_authed"}
slack-bot: 2017/07/02 08:53:21 slack.go:86: reconnection 10 failed: not_authed
slack-bot: 2017/07/02 08:53:21 slack.go:92:  -> reconnecting in 13.237922026s`

**Comment by dlsniper** [comment]
My guess is that you need to add all the missing certificates so that it works but I've never tried from scratch, just alpine

**Comment by mumblez** [comment]
I've pasted a complete program, hopefully you guys will spot something egregious! - https://pastebin.com/rJGhmMEg

@dlsniper - using the gocertifi library to pull in cacerts

**Comment by dlsniper** [comment]
I meant this part https://github.com/gopheracademy/gopher/blob/master/Dockerfile#L10 I don't know what gocertifi does, sorry.

This is clearly not a app problem since it works from other containers. I would suggest learning the difference between various container base images and that should give you the answer you are looking for.

**Comment by mumblez** [comment]
gocertifi is a very small library-https://github.com/certifi/gocertifi, a wrapper that puts all the cacerts from mkcert.org/general into a file, we then create a custom transport object which we pass into a custom http client, I hope I'm using it right by setting the http client with slack.SetHTTPClient, I assume the error might be cos the websocket / rtm is using a separate client? (purely speculation)

**Comment by james-lawrence** [comment]
@mumblez going to close this issue, you're doing the right thing, like dlsniper I suspect its an issue with your container.

easy way to determine if your assumption about the RTM is correct:
```
api := slack.New(token)
if err := api.AuthTest(); err != nil {
  log.Fatalln(err)
}
```
