### ISSUE TITLE
JSON Roundtrip Issue For Forward Slash

### ISSUE THREAD

**Issue by joefitzgerald** [slack-go/slack#18]
Slack's JSON escapes `/` such that it is emitted as `\/`. This Unmarshals correctly but `json.Marshal` doesn't re-escape this character by default. It may be worth adding a custom encoder to handle this scenario correctly.

**Comment by nlopes** [comment]
:+1: I will include this in a future patch (if you already have a patch, feel free to PR it)
Thanks for the report!

**Comment by nlopes** [comment]
Can you tell me which response does this? I don't see it when logging all requests coming through. When I send the messages, they also show up properly.
