### ISSUE TITLE
Tokens are now considered Legacy. Provide example of how to use with Oauth.

### ISSUE THREAD

**Issue by veqryn** [slack-go/slack#184]
I just created a new Slack app, and all I have are:
Client ID
Client Secret
Verification Token

I have no idea how to use these with this library.

Can you please provide an example?

**Comment by bitterlox** [comment]
I have the same problem. Would like to see how to use OAuth

**Comment by sh3rp** [comment]
FYI, you need to set up an app that's also a bot.  Then go to https://api.slack.com/apps, select your app, then click "OAuth & Permissions" in the left sidebar.  That should have your OAuth Bot Access Token in it.

**Comment by bitterlox** [comment]
Yeah i found it eventually.

**Comment by egeland** [comment]
Good advice, @sh3rp :+1:
