### ISSUE TITLE
How do I handle Mentions? 

### ISSUE THREAD

**Issue by MTRNord** [slack-go/slack#187]
As in the title how could I handle Mentions against the bot? Means check if bot is mentioned and get the text after the mention (a bit like commands)

**Comment by inge4pres** [comment]
A simple solution is to parse the incoming message and see if contains \@botname with `regexp`

**Comment by james-lawrence** [comment]
@inge4pres  regex won't work for `@botName` end users can change the name of the bot.

that being said the mentions are sent in the form `<@ID|name>` iirc and can be matched against the ID of the bot with can be pulled off the client post connect.
