### ISSUE TITLE
websocket_proxy.go should support lower case `http_proxy`

### ISSUE THREAD

**Issue by ArcticSnowman** [slack-go/slack#188]
As there is no real standard for the proxy environment variable, systems can have either HTTP_PROXY or http_proxy.  

websocket_proxy.go should handle both cases.

**Comment by gingersnapz** [comment]
https://github.com/nlopes/slack/pull/204

**Comment by james-lawrence** [comment]
easily fixed in your application:
```
os.Setenv('HTTP_PROXY', os.Getenv('http_proxy'))
```
