### ISSUE TITLE
Websocket / Keepalive

### ISSUE THREAD

**Issue by abourget** [slack-go/slack#19]
there are plenty of `log.Fatal`, `log.Panic` in the code, especially regarding disconnection...

My bot handles reconnecting after disconnection.. but this API makes it hard to recover as it kills the whole thing at many points.

Anyone using the websocket stream ? I'd like to either make it reconnection-handling friendly, or maybe implement the reconnection right into this lib.  what do you think ?

**Comment by nlopes** [comment]
I hope someone tackles this. It is one of the things I regret having in the api. At some point I want to tag this as it is (with the current PRs merged non withstanding) and then break with a clean api (removing many of the log.X) in a newer version.

If someone has a patch for this, I would gladly merge it.

**Comment by abourget** [comment]
Can you list a couple of things you would have like to see reworked ?

I've seen a couple of non-standard things.. I'd be willing to give it a swift.. clean up and put some scalable patterns.

I was thinking of optionally handling all the ChannelDeleteEvent, ChannelCreateEvent, etc.. internally, so as to keep an updated view of the users and channels available to the API user. Now I need to build that in my app.. but it would be useful in the lib directly.

I saw also a Sleep(500ms) somewhere.. feels a little bit crude inside a library.. what's the intent there ? Maybe we could implement some pattern, backoff or something.. The sleep was in the loop to read incoming messages.. I don't see the point of blocking incoming messages, but rather of rate-limiting the outgoing messages, no ?

**Comment by nlopes** [comment]
I agree on most of those points.

Sleep(500ms) shouldn't really be needed, but I remember the underlying go websocket library being very unhappy without that sleep. At the time I didn't invest enough time researching that.

Other things I would like to fix in a rewrite include allowing for/handling some of the inconsistencies of their own API (e.g.: sometimes the timestamp comes as an int, other times as a string, some other times returning a channel when they should return a group - I believe there's a nasty comment in groups.go)

**Comment by abourget** [comment]
What about having the lib handle disconnections and reconnections, and emitting a `SlackEvent{Data: Disconnected}` and `SlackEvent{Data: Connected}` of our own.. so we could still handle things if those occur.. flush things, or whatnot.. but the users of the lib wouldn't need to implement those repetitive things.

I'd make sure we have a `.Disconnect()` method, that would disconnect everything, emit the `Disconnected` event, and then stop.. in case the caller wants to manage the disconnections himself.

I'd have the `Keepalive` be automatic, with a predefined amount of seconds.. but it would simply trigger a reconnection in case it fails.. would trigger a stop of the other goroutines, and schedule a restart.  It could implement a log-backoff algo in reconnecting...

What do you think ?

**Comment by abourget** [comment]
Regarding the "group" as a channel (or vice versa).. my implementation receives the Groups and keeps a list of "Channels" up to date, with groups merged in there as "Channels", with `IsGroup == true`.. so I can easily go through the list, filter if needed, but I'm not forced to loop through 2-3 lists when I want to check all "rooms" available.

What do you think ?  Could that be the way this lib handles things ?

**Comment by nlopes** [comment]
Sounds like a good idea. Although I would prefer Groups and Channels unmerged. It's fairly trivial to do that outside of the library and it keeps things tidy. I like the idea of having different types for those just in case Slack decides to do something very different with groups and channels. I can think of video within a group but not everyone in a channel.

**Comment by abourget** [comment]
@nlopes don't know if you've seen how https://github.com/abourget/slack has advanced.. I've done some quite major reworks though.. it breaks the API.

Quick peek here: https://godoc.org/github.com/abourget/slack#RTM

**Comment by nlopes** [comment]
Just got back from a conference. Will check this in the next couple days once I have recovered. Thanks!

**Comment by nlopes** [comment]
Wow, quite some breaking changes. I will spend some time cherry-picking a lot of these changes (they look pretty great).

As for the breaking changes, I will probably tag the one (plus a couple of fixes) I currently have and then pull the rest of the changes.

**Comment by nlopes** [comment]
Just looked at this again, will need a bit more time to merge some things. Already merged some (easy) breaking changes from another person, so now I won't feel so uneasy about merging these.

**Comment by mstewa34** [comment]
I've worked on improving the stability of @abourget's changes over at https://github.com/FogCreek/slack. In particular, the Disconnect method should now work and more error events are recognized and sent to the IncomingEvents channel. Most of my changes from @abourget's fork are in [websocket.go](https://github.com/FogCreek/slack/blob/master/websocket.go) and [websocket_managed_conn.go](https://github.com/FogCreek/slack/blob/master/websocket_managed_conn.go).

**Comment by nlopes** [comment]
@mlbvsnba Awesome! Will take a look at this soon. Thanks! (p.s.: Big fan of FogCreek here :D)

**Comment by nlopes** [comment]
@mlbvsnba @abourget All merged in to https://github.com/nlopes/slack/tree/nlopes-breaking-changes and soon to master.

Big kudos for the changes.
