### ISSUE TITLE
why don't i see bot picture/name in slack? i have same code in java that shows bot picture/name

### ISSUE THREAD

**Issue by eitanh** [slack-go/slack#190]
weird. am i doing something wrong?

fmt.Println("Eddie is here")
	api := slack.New("zzz")
	params := slack.PostMessageParameters{}
	channelID, timestamp, err := api.PostMessage("incident_manager", "yo", params)
	if err != nil {
		fmt.Printf("%s\n", err)
		return
	}
	fmt.Printf("Message successfully sent to channel %s at %s", channelID, timestamp)

**Comment by dlsniper** [comment]
You need to set the ` AsUser ` to true

**Comment by eitanh** [comment]
yes now it's working, where i have seen this option? i didn't see in main page.
