### ISSUE TITLE
change logger to an interface?

### ISSUE THREAD

**Issue by bjhaid** [slack-go/slack#193]
I currently use [glog](https://github.com/golang/glog/blob/master/glog.go) in my code, I don't mind implementing an interface to wrap calls to glog in my code, but giving [`logger`](https://github.com/nlopes/slack/blob/master/slack.go#L11) points to the concrete type `log.Logger` then my choices are limited. I wouldn't mind opening a PR to fix this if this sounds like a good idea to you

**Comment by jBugman** [comment]
Did something similar in #179 a while ago, but it is not merged yet.

**Comment by james-lawrence** [comment]
fixed by #236
