### ISSUE TITLE
"error":"missing_scope","needed":"rtm:stream"

### ISSUE THREAD

**Issue by mikkergimenez** [slack-go/slack#195]
I'm not sure if something changed on the slack side, but I don't seem to be able to get the library working.  I had code that worked some months ago that seems to have stopped working, now I mucked with some of the permissions on the applications and it seems i have may removed a scope that I can't re-add.  Any insights?  The documentation around this isn't helpful.

**Comment by toby3d** [comment]
Same problem. I don't understand why this scope in URL break OAuth2 authorization.

**Comment by mikkergimenez** [comment]
This was my bad, I was using an app key instead of a bot key.  The documentation on this error message on the slack site is somewhat misleading.
