### ISSUE TITLE
Consistency - channel argument is in some cases channel name, in others channel id

### ISSUE THREAD

**Issue by pete911** [slack-go/slack#202]
```
rtm := slack.New(token).NewRTM()
...
rtm.JoinChannel(channel string) // expects channel name
rtm.LeaveChannel(channel string) // expects channel id
rtm.GetChannelInfo(channel string) // expects channel id
```
would be good to make this consistent (change join channel to accept channel id instead of name) and also rename arguments so it is clear if it is channel name or id: `LeaveChannel(channelId string)`

**Comment by freddieptf** [comment]
This also just bit me right now while going through the websocket example 
https://github.com/nlopes/slack/blob/5cde21b8b96a43fc3435a1f514123d14fd7eabdc/examples/websocket/websocket.go#L30 
Had to go through [slack api docs](https://api.slack.com/rtm) to realize i had to use the channel id

**Comment by pete911** [comment]
I have create pull request (https://github.com/nlopes/slack/pull/203) so if you are happy with the changes (only renamed method args and added comments - this should not break existing implementations). @freddieptf I have updated websocket example you mentioned (I have used channelId example from slack docs - https://api.slack.com/events/message)

**Comment by freddieptf** [comment]
@pete911 nice!

**Comment by pete911** [comment]
@nlopes hi, when do you think this could get merged? It should not break any code (it's just args rename and added a few comments)
