### ISSUE TITLE
Message formatting

### ISSUE THREAD

**Issue by courtenayf** [slack-go/slack#210]
Hi there,

How does one pass back formatted messages like attachments? eg:

https://api.slack.com/docs/message-attachments

**Comment by karl-gustav** [comment]
Judging by this it doesn't support markdown/advanced formatting yet: https://github.com/nlopes/slack/blob/master/TODO.txt

(I would love to be proven wrong on this)

**Comment by inkel** [comment]
Say you have a client already instantiated, wouldn't this do what you are looking for?

```go
params := slack. PostMessageParameters{
  Attachments: []Attachment{
    {
      Color: "good",
      PreText: "Some `code` and _italic_ and *bold* is allowed",
      MarkdownIn: []string{"pretext"},
    },
  },
}

client.PostMessage("#channel", "", params)
```

I haven't tried, but it'd think it's the way to go.

**Comment by james-lawrence** [comment]
yesm that would be the general way of handling it. closing.

**Comment by karl-gustav** [comment]
This worked:
```
params := slack.PostMessageParameters{
	Attachments: []slack.Attachment{
		{
			Color:      "good",
			Pretext:    "Some `code` and _italic_ and *bold* is allowed <http://www.foo.com|a link>",
			MarkdownIn: []string{"pretext"},
		},
	},
}

rtm.Client.PostMessage(slackReceiverRoomID, "", params)
```
