### ISSUE TITLE
Slack RTM endpoint behavior change

### ISSUE THREAD

**Issue by apokalyptik** [slack-go/slack#216]
Between 10PM UTC and 11PM UTC yesterday slack started responding to my RTM endpoint connections *which included a port number* with {} (and possibly closing the connection).  This caused the api  client to go into infinite forceping loops, and reconnecting constantly.  Also this caused the client not to actually work -- obviously.  As a workaround I had to modify rtm.go to stop using websocketizeURLPort in StartRTM and in ConnectRTM.

**Comment by jyap808** [comment]
I've experienced this issue too but it started much earlier. Can you post your code changes? Thanks

**Comment by jyap808** [comment]
Oh wow, my bot works now. Thanks!

**Comment by apokalyptik** [comment]
opened PR -- https://github.com/nlopes/slack/pull/217

**Comment by YouEclipse** [comment]
Thanks!!!! my bot works now too!

**Comment by jlgale** [comment]
We ran into this issue as well where the trailing query parameter (`?dp=1`) was being stripped by `websocketizeURLPort()`. The PR fixed things for us.

**Comment by syphoxy** [comment]
I'd hate to contribute a "me too" comment but today this issue surfaced on my bot.

using debug, I could see that the bot (eventually) connected to the Slack API but then observed what was mentioned in the original post and then eventually rate limited.

see here: https://api.slack.com/docs/rate-limits

PR #217 solves it for me. is this solution viable or is it just a hack?

**Comment by apokalyptik** [comment]
@syphoxy I don't know. I was kind of hoping that @nlopes would have commented on it by now? ¯\_(ツ)_/¯

**Comment by ben-greco** [comment]
I just want to continue to chime in and say that I also encountered this issue and it's a critical bug that breaks the bot, the fix by @apokalyptik in #217 fixed it and we actually made those changes directly in our source and rebuilt it to fix it. Wanted to give a big shout out and also +1 for merging the PR into master. Thanks!

**Comment by pasali** [comment]
This issue also caused our bot to crash. I spent hell of time to find out what is broken. So it would be very nice if this PR gets merged.
