### ISSUE TITLE
changing the bot name

### ISSUE THREAD

**Issue by prvst** [slack-go/slack#224]
My messages show up as from 'Slack API Tester'. Is there a way to change the bot name ?

**Comment by lrstanley** [comment]
If you are simply using a bot (and not a user or similar), you would change that within the bot configuration section of the App Directory of Slack.

E.g. https://your-team.slack.com/services/YOUR-BOT-ID

On that page, there will be a "Customize Name" and "Full Name" section where you can change this. I am not aware of any way for the bot to be able to change this by itself.

**Comment by prvst** [comment]
Thanks!

**Comment by Joshfindit** [comment]
Just a quick update:
If you just want simple messages, since at least https://github.com/slack-go/slack/pull/519 you can use

```go
api.PostMessage(
    channel,
    slack.MsgOptionText("Message", false),
    slack.MsgOptionPostMessageParameters(slack.PostMessageParameters{Username: "Desired Username"}))
```

**Comment by prvst** [comment]
Thanks @Joshfindit
