### ISSUE TITLE
Move Websocket Implementation Over to Gorilla Websocket

### ISSUE THREAD

**Issue by catherinetcai** [slack-go/slack#228]
This package currently use's Google's [websocket](https://godoc.org/golang.org/x/net/websocket) implementation. I think the [Gorilla one](https://godoc.org/github.com/gorilla/websocket) is more actively maintained (and recommended in the Google websocket godoc as a better alternative) . Just making a note of it here as an enhancement we can make down the line.

**Comment by ArcticSnowman** [comment]
This change does seem to help in solving a connection issue with a recent API change..

**Comment by Helcaraxan** [comment]
@james-lawrence this one can be closed now. 🙂
