### ISSUE TITLE
Remove global configuration settings.

### ISSUE THREAD

**Issue by james-lawrence** [slack-go/slack#231]
general issue for cleaning up the API, lets put all the global configuration/assumptions here.
known globally exposed configs:

- http.Client
- HTTPResponder
- net.Dialer for websockets
- logger - may let us also remove the SetDebug option.
- HTTP_PROXY code in RTM connect setup (investigate)

**Comment by zellyn** [comment]
The `HTTP_PROXY` code in RTM connect setup is also global config; there's no way to specify a proxy in config.
