### ISSUE TITLE
Package not building

### ISSUE THREAD

**Issue by mauleyzaola** [slack-go/slack#232]
As of today this package is not building. I realized it when pushing code to a PR that uses your package. Travis output below.
```
kaizen$ wwtd
Ignoring: go, language, notifications
START
./check.sh
github.com/nlopes/slack (download)
github.com/nlopes/slack
# github.com/nlopes/slack
../../../../nlopes/slack/slack.go:104:9: logger.Output undefined (type stdLogger has no field or method Output)
../../../../nlopes/slack/slack.go:110:9: logger.Output undefined (type stdLogger has no field or method Output)
# github.com/nlopes/slack
../../../../../../nlopes/slack/slack.go:104:9: logger.Output undefined (type stdLogger has no field or method Output)
../../../../../../nlopes/slack/slack.go:110:9: logger.Output undefined (type stdLogger has no field or method Output)
FAIL	github.com/mauleyzaola/kaizen/src/backend/tests/business [build failed]
[FAIL] One or more unit tests failed.
FAILURE
```

It looks the problem is with this commit: https://github.com/nlopes/slack/commit/28fbc53ee8cf0e0033c3852a222d47bc06b11b04

Someone forgot to add the `Output()` method 😄 

I can help if you like. Thanks!

**Comment by dvdplm** [comment]
@mauleyzaola hey I just noticed that same thing (https://github.com/nlopes/slack/pull/179#event-1405373500). 
Yes, if you have time to make a PR I'll make sure it's merged asap! Thanks! :)

**Comment by mauleyzaola** [comment]
Ok, I am on it now. 👍

**Comment by mauleyzaola** [comment]
@dvdplm It looks like all tests are passing now. Please review. Thanks!

**Comment by dvdplm** [comment]
Looks good, however I don't see the PR here https://github.com/nlopes/slack/pulls
