### ISSUE TITLE
helper methods for user->id, usergroup->id, channel->id, group->id

### ISSUE THREAD

**Issue by lrstanley** [slack-go/slack#234]
Thoughts on the idea of potentially adding helper methods for these types of lookups? They probably wouldn't need to support caching or similar, as that would be on the end user (and is fairly trivial if needed). At this stage, I've written ~5 different application which utilize this library, and each time I have to implement a lookup wrapper which fetches, and loops through all users/usergroups/channels/groups/etc. This is because many of the applications have configuration files, where it would be irritating to require users to specify the ID rather than the display name of some channel/user/etc.

Something like...
```go
func (api *Client) LookupUserByName(name string) (user *User, err error) {}
```

Or if we were to implement caching into the client, we could take just a "return id" approach:
```go
func (api *Client) LookupUserByName(name string) (id string err error) {}
```

etc.. for users, usergroups, channels, groups, and so forth.

If this doesn't seem unreasonable, I could probably throw a PR together to add these methods. Also, thoughts on if caching should at all be enabled? It's hard to reason about caching, due to how long we should keep it, and if users rename channels and similar when the mapping is cached.

Also, I'm not too familiar with the Slack enterprise "team" username mapping/merging, maybe a team lookup too, if that's needed?

**Comment by lrstanley** [comment]
https://github.com/nlopes/slack/issues/95 is also related.

**Comment by james-lawrence** [comment]
Unless the API explicitly allows for that sort of filtering I'd like to avoid those kinds of methods in the client.

I'd be fine with actual pure functional utility methods for filtering though.

`func FilterUsers([]User, func(User) bool) ([]User)`
`func UniqueUser([]User, func(User) bool) User`
`func MatchUserByName(name string) func(User) bool`

I'd also prefer them to be in a sub package. mainly because adding the methods as you described would increase the surface area of the API client beyond what is actually supported by slack, and people may actually want custom logic.

definitely open to ideas for this.

**Comment by james-lawrence** [comment]
as for the caching problem, not totally opposed to having a cache implementations available for use, but again they don't belong in the main package. nor would they be wired in automatically. those are application specific concerns.

**Comment by dvdplm** [comment]
FWIW I strongly agree with @james-lawrence on both issues.

**Comment by lrstanley** [comment]
That does seem a bit more reasonable. Thoughts on what the sub-package should be named? If the sub-package is solely based on filtering, `filter` would be sufficient enough as long as it's a sub-package?  We should probably not put `Filter` in the method names at that point then. E.g:

```go
func Users([]User, func(User) bool) []User {}
// Unique sounds misleading, since we'd likely want to go from index 0 onward,
// and "Unique" doesn't tell us how it's being picked.
func FirstUser([]User, func(User) bool) (user User, ok bool) {}

// Thoughts on some useful pre-defined matchers. Would be different for each
// type, but for users, like your suggestion:
func MatchUserName(name string) func(User) bool {}
func MatchUserEmail(email string) func(User) bool {}
func MatchUserIsAdmin() func(User) bool {}
// .. etc
```

And usage example, something along the lines of:

```go
package main

import (
	"log"

	"github.com/nlopes/slack"
	"github.com/nlopes/slack/filter"
)

func main() {
	api := slack.New("YOUR_TOKEN_HERE")
	users, err := api.GetUsers()
	if err != nil {
		log.Fatal(err)
	}

	match, ok := filter.FirstUser(users, filter.MatchUserName("lrstanley"))
	if !ok {
		log.Fatal("user not found!")
	}

	log.Printf("found user %#v", match)
}
```

Thoughts on if there is anything else that may be useful to add to the sub-package as well? Other than just filters for users/usergroups/channels/groups/etc?

In regards to caching, that was my thought as well. Implementing it would bring too many assumptions about how they'd like to handle expiration and similar.

If you folks don't want to have to manage these types of functions or don't think they would be useful enough for others, I can probably drop them in a separate package. May also be good to add a 'packages/utilities using this package in the readme' to give people some more examples of usage as well.

**Comment by james-lawrence** [comment]
Pretty indifferent on the name but at a minimum lets prefix them with slack:
```
slackfilter.FirstUser
slackcache.NewUser
```

**Comment by lrstanley** [comment]
Just a heads up, haven't given this attention lately, due to new job, new city/state, etc. Closing for now, but will likely re-open when I _eventually_ get to poking this.
