### ISSUE TITLE
Switch to using RTM Connect by default.

### ISSUE THREAD

**Issue by james-lawrence** [slack-go/slack#235]
change default of useRTMStart from true to false.

also remove `NewRTMWithOptions(options *RTMOptions)` and `RTMOptions`

**Comment by Helcaraxan** [comment]
@james-lawrence Happy to take this one as it should be fairly small. Will there be a branch for 2.0.0 to target with the relevant PRs?

**Comment by james-lawrence** [comment]
@Helcaraxan no real work to be done really. #244 has the majority of the code done. only thing remaining is to remove the method on 2.0.0

**Comment by Helcaraxan** [comment]
Ah apologies. Had not seen your PR yet. 👍

**Comment by james-lawrence** [comment]
cleaned up with the remove globals branch that was merged.
