### ISSUE TITLE
Make bot respect Retry-After

### ISSUE THREAD

**Issue by pete0emerson** [slack-go/slack#240]
This problem may be on me, but I'm not sure.

My RTM bot (based on your [example](https://github.com/nlopes/slack/blob/master/examples/websocket/websocket.go)) was offline this morning. After settign up `api.SetDebug(true)`, I saw that Slack has throttled me:

```slack-bot: 2018/01/09 09:09:26 slack.go:86: reconnection 5 failed: post: Slack server error: 429 Too Many Requests.
slack-bot: 2018/01/09 09:09:26 slack.go:92:  -> reconnecting in 406.399931ms
Event Received: Event Received: slack-bot: 2018/01/09 09:09:27 misc.go:164: HTTP/2.0 429 Too Many Requests
Content-Length: 34
Access-Control-Allow-Origin: *
Cache-Control: private, no-cache, no-store, must-revalidate
Content-Type: application/json; charset=utf-8
...
Retry-After: 43
...
{"ok":false,"error":"ratelimited"}
```

What appears to be happening, though, is that the bot continues to make requests, not respecting the Retry-After, and therefore gets continuously rate limited. In other words, I see the similar message above repeated over and over with no seeming attempt to throttle itself.

What is the right way to get the bot to respect the rate limiting, and is that best done in my code, or in your library?

**Comment by Jmainguy** [comment]
check out https://github.com/nlopes/slack/issues/239, updating the code got my bot to start working again, even though respecting retry-after would be a cool feature to add.

**Comment by james-lawrence** [comment]
#186 added basic infrastructure for this. updating where-ever it is missing it sohuld be pretty straight forward for anyone so inclined.

also let me know if updating to master doesn't resolve this.

**Comment by james-lawrence** [comment]
try up

**Comment by james-lawrence** [comment]
closing due to age and we have support in various areas now.
