### ISSUE TITLE
Cut a new tagged version?

### ISSUE THREAD

**Issue by james-lawrence** [slack-go/slack#245]
been a while since a tagged release was cut.

things we need to think about:
- changelog.
- how often do we want to do this.
- the process

**Comment by schimmy** [comment]
Yes, please cut a new release!
I've had to lock onto a specific version in my Gopkg file. I needed to use a more recent version to take in @jmhobbs 's rate-limiting fixes. (thank you @jmhobbs)

**Comment by dvdplm** [comment]
I strongly agree that it's time for a release. I suggest we cut the release asap and continue the frequency/process dialogue in parallel.

**Comment by jayminkapish** [comment]
A new tag/release is possible? I need to use slash.go and it isn't included in `v0.1.0`

**Comment by james-lawrence** [comment]
released v.0.2.0 for now.

**Comment by stjohnjohnson** [comment]
@james-lawrence any chance you could cut another release?  Maybe `v0.4.0`?

**Comment by james-lawrence** [comment]
not quite yet, have some upcoming changes i want to get in first and mark them as experimental so people can expect breakage. (around dialogs)

**Comment by james-lawrence** [comment]
@stjohnjohnson done.
