### ISSUE TITLE
bot presence

### ISSUE THREAD

**Issue by jicui** [slack-go/slack#250]
does any one meet the issue before or may be just I only ,here is the senario ,I connect to via RTM api ,as the doc said in https://api.slack.com/docs/presence-and-status .once you connect via RTM and pass in correct token ,your bot will auto up (status =active not away)

but it does not work in my machine ,the connect is success and bot can response ,but status is always "away"

any hints is appreciated

**Comment by jicui** [comment]
*code example is like this* 


        api := slack.New("tokenhere")  
         logger := log.New(os.Stdout, "slack-bot: ", log.Lshortfile|log.LstdFlags)
         slack.SetLogger(logger)
        api.SetDebug(true)      
        api.SetUserPresence("auto")	
        rtm := api.NewRTM()
	go rtm.ManageConnection()

	for msg := range rtm.IncomingEvents {
		fmt.Print("Event Received: ")
		switch ev := msg.Data.(type) {
		case *slack.HelloEvent:
		// Ignore hello

		case *slack.ConnectedEvent:
...
`

**Comment by andyone** [comment]
Remove `api.SetUserPresence("auto")` from your code and check it agian.

**Comment by jicui** [comment]
remove ,but still not work ,then I stay back for 2 days and check again ,then the presence right now is works fine ,
I guess it is related to slack rtm server side
