### ISSUE TITLE
Support Conversations API

### ISSUE THREAD

**Issue by jdanlewis** [slack-go/slack#253]
Add support for the [Conversations API](
https://api.slack.com/docs/conversations-api).

Related: `channels.info`, `channels.join`, `channels.list`, and `rtm.start` now return a [truncated members list](https://api.slack.com/changelog/2017-10-members-array-truncating).

#249 takes care of:

https://api.slack.com/methods/conversations.archive
https://api.slack.com/methods/conversations.members
https://api.slack.com/methods/conversations.rename
https://api.slack.com/methods/conversations.setPurpose
https://api.slack.com/methods/conversations.setTopic
https://api.slack.com/methods/conversations.unarchive

#252 takes care of:

https://api.slack.com/methods/conversations.close
https://api.slack.com/methods/conversations.create
https://api.slack.com/methods/conversations.info
https://api.slack.com/methods/conversations.invite
https://api.slack.com/methods/conversations.kick
https://api.slack.com/methods/conversations.leave
https://api.slack.com/methods/conversations.replies

Remaining:

https://api.slack.com/methods/conversations.history
https://api.slack.com/methods/conversations.join
https://api.slack.com/methods/conversations.list
https://api.slack.com/methods/conversations.open

**Comment by suzuki-shunsuke** [comment]
I have added supports of remaining APIs to the Pull Request https://github.com/nlopes/slack/pull/252 .

* https://api.slack.com/methods/conversations.history
* https://api.slack.com/methods/conversations.join
* https://api.slack.com/methods/conversations.list
* https://api.slack.com/methods/conversations.open

**Comment by james-lawrence** [comment]
all merged. this should be done.
