### ISSUE TITLE
RTM API with private channels

### ISSUE THREAD

**Issue by sevagh** [slack-go/slack#255]
Hello,

I'm using the RTM api in a loop to write a poll-bases slackbot. It listens for mentions of itself, and responds.

When I invite my bot to private channels and try to speak to it, I get the following error:

```
nlopes/slack2018/01/25 14:20:23 websocket_managed_conn.go:295: Incoming Event: {"type":"desktop_notification","title":"MyOrg","subtitle":"oc_bot_test_private","msg":"1516918822.000302","content":"Sevag Hanssian: @oncall who","channel":"XXXX","launchUri":"slack:\/\/channel?id=XXXX&message=1516918822000302&team=WWWW","avatarImage":"https:\/\/avatars.slack-edge.com\/2017-12-13\/286259283427_a73eeb87a887c6c43953_192.jpg","ssbFilename":"knock_brush.mp3","imageUri":null,"is_shared":false,"event_ts":"1516918822.000521"}
nlopes/slack2018/01/25 14:20:23 websocket_managed_conn.go:316: Received desktop notification, ignoring
nlopes/slack2018/01/25 14:20:23 misc.go:88: parseResponseBody: {"ok":false,"error":"channel_not_found"}
```

Is the RTM intended to work with private channels?

**Comment by james-lawrence** [comment]
RTM works in private channels. something else is likely wrong with your application.

**Comment by sevagh** [comment]
My application does nothing fancy except create a slack client and establish an RTM connection.

**Comment by dvdplm** [comment]
@sevagh Can you provide us with a minimal test case so we can reproduce the problem? Thanks!

**Comment by sevagh** [comment]
Apologies for vagueness/low-info. Was hoping for some miraculous "Aha! you forgot `rtm.EnablePrivateChannels()`".

Tomorrow morning I'll do a deeper dive (perhaps my API key doesn't have good permissions) and produce a full test case to paste here.

**Comment by dvdplm** [comment]
@sevagh Great! FWIW that is the error Slack usually spits back at you when you're trying to interact with a private channel without being a member. So make extra sure the user whose API token your using actually has access to the channel.

**Comment by sevagh** [comment]
Finally got around to making a minimal example, and somehow things are working fine. From what I understand from the Slack bot permission model, if it's invited somewhere, there should be no access denied errors.

I wonder what I screw up in the code of my main application...


```
package main

import (
	"fmt"
	"github.com/nlopes/slack"
	"os"
        "strings"

)

func main() {
	client := slack.New(os.Getenv("SLACK_API_KEY"))
	rtm := client.NewRTM()
	go rtm.ManageConnection()
	for {
		select {
		case msg := <-rtm.IncomingEvents:
			switch ev := msg.Data.(type) {
			case *slack.MessageEvent:
                                userID := rtm.GetInfo().User.ID
                                prefix := fmt.Sprintf("<@%s>", userID)
                                channel := ev.Channel

                                if ev.User != userID && strings.HasPrefix(ev.Text, prefix) {
                                        params := slack.PostMessageParameters{AsUser: true}
                                        params.Text = "Hello from my bot!\n"
                                        if _, err := rtm.PostEphemeral(channel, ev.User, slack.MsgOptionText(params.Text, params.EscapeText), slack.MsgOptionAttachments(params.Attachments...), slack.MsgOptionPostMessageParameters(params)); err != nil {
                                                panic(err)
                                        }
                                        fmt.Println("I just succeeded at responding on a channel!")
                                }
			case *slack.RTMError:
                                panic("RTM Error")
			case *slack.InvalidAuthEvent:
                                panic("Invalid auth")
			default:
			}
		}
	}
}
```

**Comment by sevagh** [comment]
I believe I found the issue.

```
channelInfo, err := sc.client.GetChannelInfo(channel)
	if err != nil {
                fmt.Println("What the fuck")
		return err
	}
```

I'm trying to get the channel name (the received RTM event only emits the channel ID), and my bot doesn't have the permission to make this API call.

**Comment by ArcticSnowman** [comment]
FYI...   According to Slack API..  private channels should use the groups.info call.
