### ISSUE TITLE
Is there a way to send a *slack.Message?

### ISSUE THREAD

**Issue by zwass** [slack-go/slack#256]
In the case of receiving a callback for an interactive message, we end up with a parsed `*slack.Message` as the original message (see https://github.com/nlopes/slack/blob/master/attachments.go#L55). Now what if we want to slightly modify this message, and then update it?

AFAICT the only way to post/update messages is through [this family of methods](https://github.com/nlopes/slack/blob/master/chat.go#L85-L171). None of these seem to support taking the `*slack.Message` struct, and so to make a slight modification to the message it would require breaking everything apart into the appropriate `MsgOptions` (which seems both brittle and unnecessary).

Am I missing something here?

**Comment by james-lawrence** [comment]
You're not missing anything, just hasnt' been a need to do what your asking.

slack's api historical uses url form posts for sending messages which means there isn't a direct translation between slack.Message and what we post. if you want to write a helper Option that does the conversation for the SendMessage api that would be useful. I'd have it take a straight struct though not a pointer.
