### ISSUE TITLE
Why no 'id' item in the type IM struct?

### ISSUE THREAD

**Issue by MsPseudolus** [slack-go/slack#258]
I need to send a DM to each workspace member that is from the installing user (`as_user` is `true`). To do that I need each member's dm channel `id` that gets returned by the im.list method, not the `user` id string. 

>If as_user is true:
>Pass the IM channel's ID (D023BB3L2) as the value of channel to post to that IM channel as the authenticated user.

Is there a reason that the `id` string isn't included in the type IM struct? Thanks!

**Comment by james-lawrence** [comment]
@MsPseudolus first apologies for the delayed response.

there is not a particular reason, if its part of the API and missing from the data structure then likely no one has needed it yet. Pretty easy to add if you're so inclined, feel free to make the change and open a PR.

**Comment by lrstanley** [comment]
Unless I'm misunderstanding, that field does exist, and has existed.

I see the IM type embeds the `conversation` type:

https://github.com/nlopes/slack/blob/1217b9d3e4304348a9be15c2afd80ad4691f31e5/im.go#L26

That conversation type has the exported `ID` field:

https://github.com/nlopes/slack/blob/1217b9d3e4304348a9be15c2afd80ad4691f31e5/conversation.go#L12-L15

Example:
```go
api := slack.New("YOUR_TOKEN")
list, err := api.GetIMChannels()
if err != nil {
	log.Println(err)
}
for _, im := range list {
	fmt.Println(im.ID)
}
```

**Comment by MsPseudolus** [comment]
Well done, @lrstanley   I managed to miss that!
