### ISSUE TITLE
Panic with gorilla websocket

### ISSUE THREAD

**Issue by parsley42** [slack-go/slack#260]
I have a 'bot plugin that sends ~4k replies, which is the limit of what slack allows. With the latest nlopes/slack, the bot panics with the dump shown below. With my local fork reverting the gorilla websocket commit, I get my loooong messages as expected. If I get time this weekend I may try to dig deeper, but figured folks might want a heads-up. My code just uses the RTM.SendMessage(s.conn.NewTypingMessage(chanID)) for sending messages.

Here's the full panic / stack trace.
panic: repeated read on failed websocket connection

goroutine 36 [running]:
github.com/uva-its/gopherbot/vendor/github.com/gorilla/websocket.(*Conn).NextReader(0xc042044f00, 0xc042430358, 0x0, 0x0, 0xc04234fec0, 0xc04234fec0)
        C:/Users/dlp7y/go/src/github.com/uva-its/gopherbot/vendor/github.com/gorilla/websocket/conn.go:958 +0x3e0
github.com/uva-its/gopherbot/vendor/github.com/gorilla/websocket.(*Conn).ReadJSON(0xc042044f00, 0x8b65c0, 0xc0422b15a0, 0xba51c0, 0xbd6d30)
        C:/Users/dlp7y/go/src/github.com/uva-its/gopherbot/vendor/github.com/gorilla/websocket/json.go:45 +0x36
github.com/uva-its/gopherbot/vendor/github.com/nlopes/slack.(*RTM).receiveIncomingEvent(0xc042414640)
        C:/Users/dlp7y/go/src/github.com/uva-its/gopherbot/vendor/github.com/nlopes/slack/websocket_managed_conn.go:288 +0xb1
github.com/uva-its/gopherbot/vendor/github.com/nlopes/slack.(*RTM).handleIncomingEvents(0xc042414640, 0xc04236d260)
        C:/Users/dlp7y/go/src/github.com/uva-its/gopherbot/vendor/github.com/nlopes/slack/websocket_managed_conn.go:223 +0x34
created by github.com/uva-its/gopherbot/vendor/github.com/nlopes/slack.(*RTM).ManageConnection
        C:/Users/dlp7y/go/src/github.com/uva-its/gopherbot/vendor/github.com/nlopes/slack/websocket_managed_conn.go:54 +0x26c

**Comment by dvdplm** [comment]
This seems very worrying, thank you for reporting it.

When you say "sends 4k replies", do you mean the message is 4k chars long or do you mean you call `RTM.SendMessage(s.conn.NewTypingMessage(chanID))` 4k times? Over what time frame approximately? Do you know if Slack rate limits you when the panic hits?

A minimal test case to reproduce would be super helpful. :)

**Comment by parsley42** [comment]
Yah, I should be able to produce a test case this evening, I'll try to do that tonight after work.

By '4k', I mean that I researched the maximum message size that could be sent via *RTM SendMessage, and my 'bot chops up very large messages into chunks of size MaxMessageTextLength. So, my guess is a simple test case would be SendMessage with 4000 chars.

**Comment by jdanlewis** [comment]
This appears to be due to rate limiting causing the connection to close, resulting in a slack.IncomingEventError: websocket: close 1006 (abnormal closure): unexpected EOF.

I'm running into this, too, when chunking large messages. A simple test case of sending a message with length slack.MaxMessageTextLength does not seem to trigger it alone.  The following works fine:

```
func sendABigMessage(rtm *slack.RTM, channelID string) {
    var buf bytes.Buffer
    for i := 0; i < slack.MaxMessageTextLength; i++ {
        buf.WriteString(".")
    }
    msg := rtm.NewOutgoingMessage(buf.String(), channelID)
    rtm.SendMessage(msg)
}
```

Hitting the rate limit does cause the panic above if the slack.IncomingEventError is ignored.

```
func hitRateLimit(rtm *slack.RTM, channelID string) {
    msg := rtm.NewOutgoingMessage("hello world", channelID)
    for {
        rtm.SendMessage(msg)
    }   
} 
```

See also:
https://github.com/gorilla/websocket/blob/master/conn.go#L960
and
https://github.com/nlopes/slack/blob/master/websocket_managed_conn.go#L288

**Comment by parsley42** [comment]
Thanks for digging. Yes, that makes sense - this particular plugin creates a message that's ~16k. The bot chops it up in to 4 messages, each 4000 bytes, and sends them out with a delay of 200ms - apparently still too fast. I guess the previous code dealt with this gracefully - the messages show up pretty quickly.

**Comment by judwhite** [comment]
We also ran into this today using db1988b. In our case I suspect it was a normal network drop, we weren't doing anything which would approach a rate limit. Thanks for looking into it.

**Comment by jdanlewis** [comment]
#264 prevents the panic, but I've noticed another regression caused by #238: attempting to send a relatively long message that includes channel IDs will result in the connection being closed. To reproduce:

```
func testLongMessageWithChannels(rtm *slack.RTM, channelID string) {
	s := `
<#C7WKFLK8E> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C24N4CFTP> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C4B4ED0MD> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C47HJJHAM> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C8NU8CJ1L> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C3H9PQQ5S> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C8G8DBKAA> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C1ZLG48QG> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C1UT51QCC> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C4GUJ5RU6> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C79NZJ35H> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C20G6T2RY> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C1UTFFE3F> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C1URUFKMH> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C8WQAS3E1> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C6KT0G8JD> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C7LV9C473> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C24JHKKDL> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C25V2UR7Y> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C4N70RD8U> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C1UT90DCY> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C7094SWAW> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C28ND794Y> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C4CB4D09L> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C27R3DGGH> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C5DEJST8Q> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C2US486MA> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C24HQ6QTT> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C7P3RK6MS> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C2RBTVATT> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C7CQPF0PQ> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C7B8UJR5E> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C51A3VAKV> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
<#C52A3VAKV> xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
`
	msg := rtm.NewOutgoingMessage(s, channelID)
	rtm.SendMessage(msg)
}
```

Interestingly,

1. The length of the message is less than MaxMessageTextLength.
2. Long messages (of length MaxMessageTextLength) without the channel IDs still work.
3. A RateLimitEvent is not being reported prior to the connection closure.
4. This works prior to #238.

**Comment by james-lawrence** [comment]
@jdanlewis mind opening another issue for the 2nd problem? (if you havent already)
