### ISSUE TITLE
Add support for chat.update

### ISSUE THREAD

**Issue by jmtsi** [slack-go/slack#262]
There's already support for updating messages, but updateMessage() only allows updating the text of the message. There doesn't seem to be any way to update the attachments of that message, for example.

This would be the proper way to handle message updates instead: https://api.slack.com/methods/chat.update

**Comment by jmtsi** [comment]
I added a PR implementing these changes: #267

**Comment by james-lawrence** [comment]
going to close this out, not really an issue.
