### ISSUE TITLE
Enhancement: Allow externally-provided *http.Client

### ISSUE THREAD

**Issue by joelgwebber** [slack-go/slack#27]
I need to use this library from an AppEngine frontend, which necessitates the use of Google's urlfetch API, which provides a custom `*http.Client`. I have it patched on my end (`slack.Slack` gets an extra `config *http.Client` field that's initialized in `slack.New()`), but I wanted to be sure you were receptive to such a change before submitting a patch.

**Comment by joelgwebber** [comment]
And of course if you'd prefer a different approach, I'm happy to adapt to whatever style you prefer.

**Comment by derekperkins** [comment]
If he uses the http.DefaultClient, you could modify that on init and then it should work with urlfetch.

**Comment by joelgwebber** [comment]
True enough, but that doesn't work in environments like AppEngine, where you can't rely on setting http.DefaultClient.

**Comment by nlopes** [comment]
Let me take a look at this. I had lost track of this ticket, apologies for that.

**Comment by nlopes** [comment]
@joelgwebber I've added some breaking changes to the library today so I'll merge this in if you feel generous enough to send a patch.

**Comment by joelgwebber** [comment]
Sure thing. Let me pull in your changes to my fork and get a patch together. Hopefully over the next day or two.

**Comment by dvdplm** [comment]
Did this merge happen? We'd love to be able to use something like facebooks httpcontrol (https://godoc.org/github.com/facebookgo/httpcontrol) to get retries and stats. :)

**Comment by john-difool** [comment]
I would love to hear if any progress has been made on this one?

**Comment by nlopes** [comment]
It didn't. I never got back a patch for it afaict. Will look at adding a patch myself this week.

**Comment by joelgwebber** [comment]
So sorry this completely slipped my mind for ages. I'm updating our fork now and will send a PR by the end of the week. It's a pretty simple, but pervasive change to push the `http.Client` parameter everywhere, so the change will look larger than it actually is, conceptually.

**Comment by joelgwebber** [comment]
https://github.com/nlopes/slack/pull/68

**Comment by dlsniper** [comment]
There's now an ` HTTPClient ` package level variable, which can be changed so that it can use a custom http.Client fixed in #73. I'll close this for now.
