### ISSUE TITLE
Feature request: support dialog.open method

### ISSUE THREAD

**Issue by mifisignal** [slack-go/slack#277]
https://api.slack.com/methods/dialog.open

**Comment by james-lawrence** [comment]
@otterley we'll accept a PR if you're willing to do the work.

**Comment by mifisignal** [comment]
Hard to say.  It doesn't look obvious how to add an API method to the package without copying a lot of functions.  Ideally I'd just invoke a method on a common API client struct.  Any hints?

**Comment by james-lawrence** [comment]
without digging into too many details regarding the dialog specific stuff (which I haven't looked at)

its usually as simple as invoking postForm (or the other similar functions):

```
func userRequest(ctx context.Context, client HTTPRequester, path string, values url.Values, debug bool) (*userResponseFull, error) {
	response := &userResponseFull{}
	err := postForm(ctx, client, SLACK_API+path, values, response, debug)
	if err != nil {
		return nil, err
	}
	if !response.Ok {
		return nil, errors.New(response.Error)
	}
	return response, nil
}
```

and then adding a method to the client:
```
// GetUserPresenceContext will retrieve the current presence status of given user with a custom context.
func (api *Client) GetUserPresenceContext(ctx context.Context, user string) (*UserPresence, error) {
	values := url.Values{
		"token": {api.token},
		"user":  {user},
	}

	response, err := userRequest(ctx, api.httpclient, "users.getPresence", values, api.debug)
	if err != nil {
		return nil, err
	}
	return &response.UserPresence, nil
}
```

**Comment by burdandrei** [comment]
looks like @robiball is working on this!

**Comment by richmondwang** [comment]
Any updates on this feature? 😄
I can probably help too if it is needed 🙇

**Comment by robiball** [comment]
I've implemented it and it works nicely. Just need to clean up my code a bit and add some tests, I'll try and get a PR raised this afternoon.

**Comment by burdandrei** [comment]
I already deployed it to our bot, and it works really good!

**Comment by chesleybrown** [comment]
Would love to see the result! 😍

**Comment by james-lawrence** [comment]
this has been implemented. overall API is still unstable but its workable.
