### ISSUE TITLE
Future: Support workspace

### ISSUE THREAD

**Issue by sonyccd** [slack-go/slack#279]
Support everything needed for the change to workspace tokens.
https://api.slack.com/docs/working-with-workspace-tokens

In general, these new Slack apps cannot do the following:

   * Impersonate users — your app can't post as as team member, nor award reacji on behalf of a user. Your app is your app and only your app. (Some impersonation options will be made available at a later date.)
   * Contain a bot user — workspace tokens make bot tokens and users obsolete; your app is a bot if you want it to be but you don't need a bot user feature to provide that functionality.
   * Connect to the RTM API — it's just not possible or practical with this permission model. Please use the Events API for near-real-time delivery instead.
   * Incoming webhooks aren't part of the new Slack app model. Apps should use chat.postMessage with the new channel & conversation selection model in the Permissions API instead.
   * Sign in with Slack is not yet available for new Slack apps.

Some functionality previously made possible through impersonating the authenticating user, like creating and inviting users to channels, is no longer possible with this model.

**Comment by jimsmart** [comment]
Quoting from that same page:
> Using workspace tokens isn't recommended unless you've already built an app using them. New workspace apps may no longer be created.

— Sounds like they've deprecated workspace apps already? 🤔

**Comment by james-lawrence** [comment]
yeah, closing.
