### ISSUE TITLE
Allow NewOutgoingMessage to reply in thread

### ISSUE THREAD

**Issue by Gardnem6** [slack-go/slack#280]
In message.go, there's a property for thread_ts in the OutgoingMessage struct that isn't used on the NewOutgoingMessage function.  It would be nice to allow this property to be set as part of the simple message, since the thread_ts is necessary to reply in thread to a user.  I can write and pr the change myself if preferred, but the change looks pretty simple.

**Comment by james-lawrence** [comment]
feel free.

**Comment by tylarb** [comment]
Submitted PR https://github.com/nlopes/slack/pull/351 on which should resolve this

**Comment by ghostsquad** [comment]
This should probably be closed now that #351 is merged?
