### ISSUE TITLE
it's firing too many MessageEvents once we post message as bot

### ISSUE THREAD

**Issue by cyberhck** [slack-go/slack#287]
I copied RTM example from repo:
```go
slackToken := "my real token"
api := slack.New(slackToken)
rtm := api.NewRTM()
go rtm.ManageConnection()
for msg := range rtm.IncomingEvents {
	fmt.Print("Event Received: ")
	switch ev := msg.Data.(type) {
	case *slack.MessageEvent:
		rtm.PostMessage(ev.Msg.User, "test message", slack.PostMessageParameters{AsUser:true})
		fmt.Printf("Message: %v\n", ev)
	case *slack.InvalidAuthEvent:
		fmt.Printf("Invalid credentials")
		return
	default:
	}
}
```

it connects, and replies correctly, I can see "test message" on slack, but once that happens, it still gets the message event, as a result, `Message: <data>` is printed over and over again.

The first user is me, when I typed "Hi" from slack, then all the event after that is created by bot itself. It's like bot sends this message to itself, and recursion happens. Is that a valid behavior? doesn't look like it.

**Comment by james-lawrence** [comment]
the bug is in your code.

```
rtm.PostMessage(ev.Msg.User, "test message", slack.PostMessageParameters{AsUser:true})
fmt.Printf("Message: %v\n", ev)
```

in particular you're posting every time you receive a message, including in response to yourself. (i.e. from the message you just sent)
