### ISSUE TITLE
json.Unmarshal errors

### ISSUE THREAD

**Issue by ai-pavel** [slack-go/slack#29]
Hi, great library, I'm using it for developing a bot, and yesterday he suddenly stopped with this error message:

`json: cannot unmarshal number into Go value of type slack.JSONTimeString`

I'm sorry that I cant' provide more information for now, but I'll try to catch this error later (the main problem is that it happened only once yet). I've taken a brief look at the code, and looks like there is a lot of `JSONTimeString`'s everywhere, so probably, Slack guys started changing protocol a bit.

**Comment by ai-pavel** [comment]
The only related thing I've found in spec:

`ChannelRenameInfo` should have integer value for `event_ts` - https://api.slack.com/events/channel_rename

But I've tried to rename channel and event was handled properly.

**Comment by nlopes** [comment]
Ah yes, they changed this to be an int. Need to patch this up.

**Comment by ai-pavel** [comment]
Ok, I've finally catched this bug - the bot crashed when new channel was [created](https://api.slack.com/events/channel_created), same error, with same field changed. Do you accept pull requests?

**Comment by nlopes** [comment]
@kpashka Yes, of course.

**Comment by ai-pavel** [comment]
@nlopes here you go
