### ISSUE TITLE
StartRTMContext and ConnectRTMContext masks ConnectionErrorEvent.ErrorObj type

### ISSUE THREAD

**Issue by olovpe** [slack-go/slack#299]
By returning `return nil, "", fmt.Errorf("post: %s", err)` instead of just passing along the underlying error, it's impossible to check for the type of the error, for example checking for and handling `RateLimitedError`.

**Comment by james-lawrence** [comment]
agreed, i'd happily accept a PR removing that behaviour.

**Comment by james-lawrence** [comment]
though it will break the API technically, I think its a good thing to break in this context.

**Comment by james-lawrence** [comment]
this has been resolved i believe?
