### ISSUE TITLE
Support interactions

### ISSUE THREAD

**Issue by sashker** [slack-go/slack#310]
Hello.

Is there a way to send late responses using the *response_url* param which Slack sends for interactive messages.

Thank you!

**Comment by richmondwang** [comment]
You can store the `response_url` somewhere, and use it later on... wouldnt that work for you?

**Comment by sashker** [comment]
Thanks, @richmondwang. It would work for me but I just can't realize a pipeline for such a case. I mean, what to use then in order to send a message to the *response_url* - just regular http/Client?

**Comment by richmondwang** [comment]
I see.. maybe you can use the other way.
I am talking about the `message_ts` used in `chat.update`, instead of the `response_url`.. ?

You can use this `func (*Client)`[UpdateMessage](https://godoc.org/github.com/nlopes/slack#Client.UpdateMessage).

**Comment by richmondwang** [comment]
I think I understand you now.. 
I forgot you are talking about interactive messages.. Im sorry..
In this case, I now agree with you 🙇 

I currently achieve this pipeline by http/Client as it is very simple.

```
func SendResponseURL(url, message string) (io.ReadCloser, error) {
	payload := strings.NewReader(message)
	req, _ := http.NewRequest("POST", url, payload)

	req.Header.Add("content-type", "application/json")
	res, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, nil
	}
	return res.Body, nil
}
// msg -> slack.AttachmentActionCallback
original := msg.OriginalMessage
// do the thing...
originalText, _ := json.Marshal(original)
SendResponseURL(msg.ResponseURL, string(originalText))
```

**Comment by sashker** [comment]
@richmondwang Agree with you, it's relatively simple. Though, it'll be better as a part of the main code. ))
Thank you!

**Comment by james-lawrence** [comment]
We've had a need for this as well. I actually have a branch that implements it. but its messy has some details specific to our usage that need to be cleaned up.

feel free to take a peek and extract the necessary pieces in a single PR.
https://github.com/james-lawrence/slack/tree/response-url-hacks

**Comment by james-lawrence** [comment]
this can be achieved using `UnsafeMsgOptionEndpoint` in chat.go.

not the final solution but its a workaround for the time being.
