### ISSUE TITLE
File.timestamp sometimes string

### ISSUE THREAD

**Issue by arduanov** [slack-go/slack#316]
Request
POST https://slack.com/api/channels.history

Response
```
            "file": {
                "id": "F053LCV08",
                "created": 1432940527,
                "timestamp": "1432980468",
```

Error

json: cannot unmarshal string into Go struct field File.timestamp of type slack.JSONTime

**Comment by t-vorobyova** [comment]
This is a fix
#348

**Comment by kanata2** [comment]
`channels.history` is deprecated now. So close this issue.
