### ISSUE TITLE
Client.GetUsers returns a short list

### ISSUE THREAD

**Issue by insomniacslk** [slack-go/slack#317]
Apparently it is capped at 200 users - the default limit - because the function `UserPagination.Done` returns too early:

```
    if t.c == nil || (t.previousResp != nil && t.previousResp.Cursor == "") { 
        return t, errPaginationComplete 
    } 
```

If I force the limit to a higher number, or 0, I get more results. Before I make a PR I want to check here if this is a valid bug.

**Comment by insomniacslk** [comment]
To reproduce: check out the latest commit of this library, and run the following program:

```
$ cat main.go 
package main

import (
	"log"
	"os"

	"github.com/nlopes/slack"
)

func main() {
	if len(os.Args) < 2 {
		log.Fatal("Need the legacy token as argument")
	}
	token := os.Args[1]
	client := slack.New(token)
	users, err := client.GetUsers()
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("Found %d users", len(users))
}

$ go run main.go xoxp-<your legacy token here>
2018/05/16 02:33:07 Found 200 users
```

The users are actually more than 5000. A free-to-join team with such a large number of people is NetworkToCode, accessible at http://networktocode.herokuapp.com/ .

**Comment by freeformz** [comment]
This may be fixed by: https://github.com/nlopes/slack/pull/320

Pagination is broken w/o it.

**Comment by freeformz** [comment]
PS: I had to use the UserPagintor directly in https://github.com/flexd/slackinviter/pull/25 to handle the rate limit errors. I am torn about handling those directly in Next or not. On one hand it may be something useful to know about in certain situations, on the other hand when I don’t care about them I just want a nice abstraction via GetUsers. So maybe handling the rate limiting in GetUsers makes more sense.

**Comment by insomniacslk** [comment]
thanks for the pointer! I will wait for your PR to be merged to re-verify this issue :)

**Comment by james-lawrence** [comment]
@freeformz rate limits are an application level concern, I would not accept a code path in Next() to handle them. I would accept a utility function that wraps UserPagination in a slackutils package though.

merged in the fix for this. closing.
