### ISSUE TITLE
More granular project packaging 

### ISSUE THREAD

**Issue by taraspos** [slack-go/slack#324]
Hey,
good job keeping the package without many external dependencies.
But anyway there is `gorilla/websocket` dependency which I would like to be able to avoid, still using all the message types etc.

In most cases I do not need the `websocket`, for example:
- Using only Events API
- Sending Webhooks

Thanks

**Comment by james-lawrence** [comment]
is websocket exposed in the public api anywhere? otherwise simply vendoring it with dep should resolve the issue.

**Comment by taraspos** [comment]
Yep, it is here:
https://github.com/nlopes/slack/blob/master/websocket.go#L27

**Comment by james-lawrence** [comment]
that isn't public.
