### ISSUE TITLE
Missing Support for MessageEvent Subtypes

### ISSUE THREAD

**Issue by whithajess** [slack-go/slack#327]
The slackevents api seems to be missing support for the following subtypes from MessageEvent:
- https://api.slack.com/events/message/bot_message
- https://api.slack.com/events/message/thread_broadcast
- https://api.slack.com/events/message/reply_broadcast
- https://api.slack.com/events/message/message_replied
- https://api.slack.com/events/message/message_deleted
- https://api.slack.com/events/message/message_changed
- https://api.slack.com/events/message/me_message

**Comment by whithajess** [comment]
Initial PR for `bot_message` here: https://github.com/nlopes/slack/pull/326 will follow up with PRs for others if this is the required direction.

**Comment by whithajess** [comment]
@james-lawrence Any thoughts on this?

**Comment by james-lawrence** [comment]
mmm, PR looks like just needs to be rebased off master.

**Comment by whithajess** [comment]
@james-lawrence This is actually still relevant I only added the `bot_message` subtype in the initial PR to see if that was the approach you wanted to take. If you re-open I can make the additional PRs for the other types.

**Comment by kanata2** [comment]
Note: not yet supported now

- https://api.slack.com/events/message/thread_broadcast
- https://api.slack.com/events/message/message_replied

**Comment by batflarrow** [comment]
Was the support added for `bot_message` subtype? Coz still I don't get the subtype as bot_message for messages from a integrated bot.

**Comment by kanata2** [comment]
Could you create new issue?
