### ISSUE TITLE
Parameter name is incorrect

### ISSUE THREAD

**Issue by mythrnr** [slack-go/slack#334]
Field name of `PostMessageParameters.Username` is "username", not "user_name".

https://github.com/nlopes/slack/blob/master/chat.go#L34

**Comment by james-lawrence** [comment]
will gladly accept a PR making the change. nice catch.

**Comment by mythrnr** [comment]
thank you for your reply :)
check my change, please.

**Comment by james-lawrence** [comment]
@mythrnr sorry just seeing this. the change looks good, mind actually submitting a pull request?

**Comment by mythrnr** [comment]
@james-lawrence I think that this change was merged, but isn't it?
https://github.com/nlopes/slack/pull/337

**Comment by james-lawrence** [comment]
ah, sorry =) i was wondering why this was still open and thought I imagined that we had merged it.
