### ISSUE TITLE
vendor/ subdirectory breaks go get

### ISSUE THREAD

**Issue by jrouviere** [slack-go/slack#340]
Hello,

Since #330 got merged my app doesn't build anymore.

The problem is that my app also has a dependency on gorilla/websocket and when I run `go get -u .` it's complaining about the directory layout:
```
unexpected directory layout:
	import path: github.com/gorilla/websocket
	root: /Users/julien/dev/go/src
	dir: /Users/julien/dev/go/src/github.com/nlopes/slack/vendor/github.com/gorilla/websocket
	expand root: /Users/julien/dev/go/src
	expand dir: /Users/julien/dev/go/src/github.com/nlopes/slack/vendor/github.com/gorilla/websocket
	separator: /
```

I don't use godep so I might be wrong on this, but I don't think you are supposed to commit the `vendor/` directory in your repo?

**Comment by james-lawrence** [comment]
mind providing more context? i.e the command and all the output along with your go env.

**Comment by jrouviere** [comment]
Sorry for the delay @james-lawrence, I can't seem to be able to reproduce the issue now. I believe that it is actually a transient issue from the go toolchain, as described here: https://github.com/golang/go/issues/21057
