### ISSUE TITLE
`groups.close` no longer works

### ISSUE THREAD

**Issue by philipithomas** [slack-go/slack#341]
I'm showing that the `groups.close` API is no longer working, and there seems to be an open issue on the Slack API spec for this:

https://github.com/slackapi/slack-api-specs/issues/12

*Proposed solution:* Remove this function from the library.

**Comment by james-lawrence** [comment]
seems reasonable if it has actually stopped working. feel free to submit a PR.

**Comment by weirdion** [comment]
@james-lawrence submitted a PR with groups.close removed. Could you review it  please when you get a chance?
