### ISSUE TITLE
logProvider can't compatible logrus

### ISSUE THREAD

**Issue by flw-cn** [slack-go/slack#344]
Unlike the comment says, logProvider can't compatible https://github.com/sirupsen/logrus.

```
// logProvider is a logger interface compatible with both stdlib and some
// 3rd party loggers such as logrus.
type logProvider interface {
	Output(int, string) error
}
```

**Comment by james-lawrence** [comment]
well doh, will fix the comment.

**Comment by james-lawrence** [comment]
closing, logrus can be wrapped to supply the Output(n, string) method if one desires to do so.
