### ISSUE TITLE
setUltraRestricted token requirements

### ISSUE THREAD

**Issue by apex-omontgomery** [slack-go/slack#345]
First off I want to say you have a great project here. I mainly work with the python client and I saw that you're accessing the setUltraRestricted method which is non-public. I've been able to get the setInactive method to work with my client by using the correct token permissions but I cannot figure out how to get the setUltraRestricted to work.

When I send an event with that method I get can incredibly non-specific error: 
```{'ok': False, 'error': 'not_allowed_token_type', headers....}```

My first action was to contact slack, but was informed that since it's not public they can't clarify further. Hopefully you have some recommendations.

Thank you!

**Comment by dragon788** [comment]
It appears that setUltraRestricted is for their "beta" Shared Channels/guest access feature which is probably why they are mum on it. Did you check out the code? https://github.com/nlopes/slack/blob/18ee123ca35d40ba5b011e215a8798c017a3ba80/admin.go#L173

**Comment by apex-omontgomery** [comment]
Yeah I read it over which is where I got the idea to try and access the method. Kudos to you guys. I get a different error than when I try an invalid method so I know it's reachable. We've been having admins manually make users single channel accounts, and trying to expose this feature in a slash command to vetted moderators so we don't have to expose the whole set of admin tools. 

I'm able to get the `setInactive` working with these tools but due to the token issues cannot do this. Pretty frustrating with the lack of slack api support.

**Comment by james-lawrence** [comment]
@wimo7083 my guess is its related to Enterprise Grid, i.e. you need to be using a grid team in order for it to work. =)

**Comment by theccalderon** [comment]
@wimo7083 were you able to get this working? Thanks.

**Comment by apex-omontgomery** [comment]
No I wasn't, I contacted the slack support about this and was told this is not supported and they cannot help.

![image](https://user-images.githubusercontent.com/10781353/45444968-3708da00-b686-11e8-9f8f-bac106e73d01.png)

**Comment by theccalderon** [comment]
@wimo7083 I found a way to activate a user using Slack's SCIM API (https://api.slack.com/scim) however, I can't use it because it's only available for Plus and Enterprise Grid plans, see below:

> PATCH /Users/{id}
> Updates an existing user resource, overwriting values for specified attributes. Attributes that are not provided will remain unchanged.
> Disabled users can be re-enabled by sending active attribute equal to true.

**Comment by james-lawrence** [comment]
closing out as there doesn't seem much we can do to resolve this for you.

**Comment by apex-omontgomery** [comment]
Thanks for the effort, they gotta make their money somehow.
