### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by nlopes** [slack-go/slack#35]
I am currently in the process of merging some really great changes from @abourget slack branch and a couple more from @mlbvsnba.

I would love to start moving towards merging naming for some things in the library but I thought asking what people prefer wouldn't harm anyone.

The ones I see so far are:
RTM vs WS
Client vs Slack

@joefitzgerald @abourget @mlbvsnba: would you guys mind chiming in on this if you feel strongly either way?

Thanks!

**Comment by joefitzgerald** [comment]
In general `slack.Slack<Anything>` is redundant and should instead be `slack.<Anything>`. Additionally, I would recommend running:
- [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports)
- [vet](http://godoc.org/golang.org/x/tools/cmd/vet)
- [lint](https://github.com/golang/lint)

On every save, and complying with the recommendations made by those tools. This enhances consistency when people make PRs against the repo.

**Comment by abourget** [comment]
I guess you can infer my preference from my PR :-) RTM I feel is more
precise than WS. And the go convention is to name properly within a
package.. so if it's a Client in the slack package.. then we know it's a
slack client :-) It could be some other slack thing.. so again is more
precise.

Alexandre

Le sam. 1 août 2015 13:19, Joe Fitzgerald notifications@github.com a
écrit :

**Comment by mstewa34** [comment]
I agree with what @joefitzgerald and @abourget said. Besides complying those tools I think that we should also be careful to remain consistent throughout the library.

Having said that, I have really only touched the RTM code so I don't have any other suggestions for the library as a whole.

**Comment by nlopes** [comment]
@mlbvsnba @abourget @joefitzgerald cherry picked most of all of your changes. It still needs a couple of improvements but you should be able to pull my new changes. Currently in https://github.com/nlopes/slack/tree/nlopes-breaking-changes but moving to master once I feel I have everything I want to consider this good enough for merging.

**Comment by dmitshur** [comment]
What about the [consts](https://godoc.org/github.com/nlopes/slack#pkg-constants), they're currently not using the recommended idiomatic Go style:

https://github.com/golang/go/wiki/CodeReviewComments#mixed-caps
