### ISSUE TITLE
`im.list` endpoint needs pagination

### ISSUE THREAD

**Issue by philipithomas** [slack-go/slack#350]
The `im.list` endpoint limits responses and needs pagination to retrieve all IM channel IDs. Unfortunately, to directly message a user - it seems like you need to paginate through this endpoint until you find the user. So, it's fairly critical.

https://api.slack.com/methods/im.list

**Comment by philipithomas** [comment]
Actually, this library supports the `im.open` method for finding a direct message channel ID. So, my original reason for using `im.list` has a workaround. However, `im.list` still is truncating responses!

**Comment by james-lawrence** [comment]
good to know!

**Comment by argowang** [comment]
@james-lawrence Do we still want this implemented? According to https://api.slack.com/methods/im.list, we should use conversations.list instead and conversations.list support pagination already. I believe this issue could be closed.

**Comment by james-lawrence** [comment]
I'm okay with that for an answer to this issue.
