### ISSUE TITLE
Using signed secrets to verify Slack requests

### ISSUE THREAD

**Issue by Garethgr** [slack-go/slack#353]
Hi all,
I am very new to Golang and posting on Github.
To start thanks for the code ;)
While trying to create a bot using this library I noticed that Verification Tokens are soon to be deprecated.
Slack now suggests using their Signing Secret Token which is "the cooler, fresher sibling of verification tokens."
As per: [Verifying Requests from Slack](https://api.slack.com/docs/verifying-requests-from-slack)

Again, I am very new to Golang, this was my hack to get it working in the _parser.go_ instead of the "_slackevents.OptionVerifyToken_"
I have this working via an APIGateway{proxy} and a Lambda
_(All info below has been obfuscated)_

request.Body
```
{"token":"aF5ynEYQH0dFN9imlgcADxDB","team_id":"XXXXXXXXX","api_app_id":"YYYYYYYYY","event":{"type":"app_mention","user":"AAAAAAAAA","text":"<@EEEEEEEEE> hello world","client_msg_id":"477cc591-ch73-a14z-4db8-g0cd76321bec","ts":"1531431954.000073","channel":"TTTTTTTTT","event_ts":"1531431954.000073"},"type":"event_callback","event_id":"TvBP7LRED7","event_time":1531431954,"authed_users":["EEEEEEEEE"]}
```

Slack Signing Secret
```
SSS_TOKEN = string("e6b19c573432dcc6b075501d51b51bb8") // Found in the Admin Panel
```

request.Headers
```
request.Headers["X-Slack-Signature"] = "v0=adada4ed31709aef585c2580ca3267678c6a8eaeb7e0c1aca3ee57b656886b2c"
request.Headers["X-Slack-Request-Timestamp"] = "1531431954"
```
merge the timestamp and request body
```
VERIFY_SLACKREQUEST := fmt.Sprintf("v0:%v:%v", request.Headers["X-Slack-Request-Timestamp"], request.Body)
```

parse the event using OptionVerifySSS to verify the slack message
```
eventsAPIEvent, e := slackevents.ParseEvent(json.RawMessage(request.Body), slackevents.OptionVerifySSS(&slackevents.TokenComparator{request.Headers["X-Slack-Signature"]}, SSS_TOKEN, VERIFY_SLACKREQUEST))
```

OptionVerifySSS in the _parsers.go_ file
```
func OptionVerifySSS(v verifier, sss_token string, slackrequest string) Option {
	return func(cfg *Config) {
		signingsecret := []byte(sss_token)
		sig := hmac.New(sha256.New, signingsecret)
		sig.Write([]byte(slackrequest))
		TokenResult := string(hex.EncodeToString(sig.Sum(nil)))
		cfg.VerificationToken = fmt.Sprintf("v0=%v", TokenResult)
		cfg.TokenVerified = v.Verify(cfg.VerificationToken)
	}
}
```

Below is an example of the OptionVerifySSS code working on the go playground
https://play.golang.org/p/NjtrkWyrtv7

Not sure if this helps anyone.

**Comment by james-lawrence** [comment]
that it does. I'd like to see a pure function in the core package for this as it'll be used everywhere, I'd love a contribution of this code to the library.

requirements:
1. function must be agnostic to http requests. (i.e. don't use any data structures from http package). we can implement a helper function for http requests on top.

**Comment by mikeatlas** [comment]
I hope you have regenerated your actual Signing Secret since posting it in cleartext here @Garethgr

**Comment by Garethgr** [comment]
@mikeatlas "_All info below has been obfuscated_"
It was all made up info ;)

**Comment by alyosha** [comment]
@james-lawrence just curious,  where would you locate this function in the core package?

**Comment by Garethgr** [comment]
@james-lawrence Hey, I placed the OptionVerifySSS function in the parsers.go file

**Comment by james-lawrence** [comment]
`github.com/nlopes/slack/security.go` is probably where I'd put it. I believe its going to be used by everything in the API at somepoint correct?

**Comment by Garethgr** [comment]
@james-lawrence to be honest I was just trying to get it to work ;)
I would assume if it would be used globally then yea.

**Comment by alyosha** [comment]
That makes sense--thanks for the input. Yeah there are a number of areas in the core package using verification tokens at the moment that can be updated too. 

I'm hacking a bit for a personal project and may throw up a PR later if nobody else has

**Comment by alyosha** [comment]
@james-lawrence just following up on this, I have a working example in my personal project but wanted to ask your opinion about arguments, etc. Envisioning having a function like this located in `github.com/nlopes/slack/security.go`

```
func VerifySignedSecret(body io.ReadCloser, header map[string][]string, signingSecret string) bool {
	buf, err := ioutil.ReadAll(body)
	if err != nil {
		log.Printf("[ERROR] Failed to read request body: %s", err)
		return false
	}

	message := fmt.Sprintf("v0:%v:%v", header["X-Slack-Request-Timestamp"][0], string(buf))
	expectedMAC := header["X-Slack-Signature"][0]

	mac := hmac.New(sha256.New, []byte(signingSecret))
	mac.Write([]byte(message))
	actualSignature := "v0=" + string(hex.EncodeToString(mac.Sum(nil)))

	if actualSignature == expectedMAC {
		return true
	}

	return false
}
```

Example use case would look something like below (signingSecret would be set as an environment variable and, in the below case, assigned to a field in the callback handler):
```
	// Only accept message from slack with valid signed secret
	if !VerifySignedSecret(r.Body, r.Header, h.signingSecret) {
		log.Printf("Invalid signing secret")
		w.WriteHeader(http.StatusUnauthorized)
		return
	}
```
Still relatively new to Go and this repo so definitely would love any feedback you have. Thanks in advance

**Comment by alyosha** [comment]
actually rethinking the above design because it makes no sense to call `ioutil.ReadAll` inside the function, but any other feedback still welcome

**Comment by alyosha** [comment]
now thinking something more like below
```

type SecretsVerifier struct {
	rawBody       []byte
	slackSig      string
	timeStamp     string
	signingSecret string
}

func (v SecretsVerifier) VerifySignedSecret() bool {
	message := fmt.Sprintf("v0:%v:%v", v.timeStamp, string(v.rawBody))
	expectedMAC := v.slackSig

	mac := hmac.New(sha256.New, []byte(v.signingSecret))
	mac.Write([]byte(message))
	actualSignature := "v0=" + string(hex.EncodeToString(mac.Sum(nil)))

	if actualSignature == expectedMAC {
		return true
	}

	return false
}

```
with an example use-case looking like this:

```
func (h callbackHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {

	if r.Method != http.MethodPost {
		log.Printf("[ERROR] Invalid method: %s", r.Method)
		w.WriteHeader(http.StatusMethodNotAllowed)
		return
	}

	buf, err := ioutil.ReadAll(r.Body)
	if err != nil {
		log.Printf("[ERROR] Failed to read request body: %s", err)
		return
	}

	v := SecretsVerifier{
		rawBody:       buf,
		slackSig:      r.Header["X-Slack-Signature"][0],
		timeStamp:     r.Header["X-Slack-Request-Timestamp"][0],
		signingSecret: h.signingSecret,
	}

	if !v.VerifySignedSecret() {
		log.Printf("Invalid signing secret")
		w.WriteHeader(http.StatusUnauthorized)
		return
	}
```

**Comment by james-lawrence** [comment]
hmm lets make the SecretsVerifier an io.Writer
```golang

func NewSecretVerifierFromHeader(headers http.Header) SecretVerifier {
  return ....
}

type SecretsVerifier struct {
	slackSig      string
	timeStamp     string
	signingSecret string
}

func (t SecretVerifier) Write([]byte) (n int, error) {..}

func (t SecretVerifier) Ensure() error {
   // check token 
   return errors.New("invalid token")
}

// usage:
sv := NewSecretVerifierFromHeader(req.Header)
if err = json.NewDecoder(io.Tee(req.Body, sv)).Decode(&msg); err != nil {
  // ...
}
if err = sv.Ensure(); err != nil {
  // ...
}

```

**Comment by alyosha** [comment]
Didn't you say in your previous comment that "function must be agnostic to http requests. (i.e. don't use any data structures from http package)" ?

**Comment by james-lawrence** [comment]
yup, I also said 

> we can implement a helper function for http requests on top.

```
func NewSecretVerifierFromHeader(headers http.Header) SecretVerifier {
  return ....
}
```
is the helper method. nothing in the struct, Write or Ensure methods should need any of the http stuff.

sorry if it wasn't super clear.

**Comment by alyosha** [comment]
ah, makes sense! thanks for clarifying

**Comment by alyosha** [comment]
@james-lawrence can you clarify why you want to make SecretsVerifier an io.Writer here and also what io.Tee refers too?

**Comment by alyosha** [comment]
also, in your example where are you writing the contents of `req.Body` to?

**Comment by james-lawrence** [comment]
I want to make it an io.Writer because that is what we are doing to compute the secret. your code reads the contents of the request then writes them into a hashing function. making it a writer makes it easily composable with other code that deals with request contents as my example code demonstrates.

please see standard golang io package for documention on io.Tee, but if you're familiar with standard linux commands it functions the same as the command Tee.

**Comment by james-lawrence** [comment]
the contents of req.Body are handled by the json decoder.

**Comment by alyosha** [comment]
got it! hey thanks for responding to each of my questions man, I'm sure you're busy and I know this is pretty basic stuff,  but like I said new to Go and coming from Ruby so still learning about primitives, etc. really appreciate it

**Comment by james-lawrence** [comment]
no problem. happy to help, especially those coming from ruby. (though that might be because of my irrational hatred for that language)

**Comment by alyosha** [comment]
last question -- what data structure are you using for the above `msg`? i am able to successfully write to the sv object but getting JSON syntax error when trying to decode

**Comment by james-lawrence** [comment]
depends on the callback you're dealing with. can't really answer that without seeing what your code is doing.

**Comment by alyosha** [comment]
no worries! anyways, got it working with the writer. would you mind taking one more look before I make a PR? (no rush at all)

```
type SecretsVerifier struct {
	slackSig    string
	timeStamp   string
	requestBody string
}

func NewSecretVerifierFromHeader(header http.Header) (SecretsVerifier, error) {
	if header["X-Slack-Signature"][0] == "" || header["X-Slack-Request-Timestamp"][0] == "" {
		return SecretsVerifier{}, errors.New("headers are empty")
	}

	return SecretsVerifier{
		slackSig:  header["X-Slack-Signature"][0],
		timeStamp: header["X-Slack-Request-Timestamp"][0],
	}, nil
}

func (v *SecretsVerifier) Write(body []byte) (n int, err error) {
	v.requestBody = string(body)
	return len(body), nil
}

func (v SecretsVerifier) Ensure(signingSecret string) error {
	message := fmt.Sprintf("v0:%v:%v", v.timeStamp, v.requestBody)
	expectedMAC := v.slackSig

	mac := hmac.New(sha256.New, []byte(signingSecret))
	mac.Write([]byte(message))
	actualSignature := "v0=" + string(hex.EncodeToString(mac.Sum(nil)))

	if actualSignature == expectedMAC {
		return nil
	}

	return errors.New("invalid signing secret")
}
```

**Comment by james-lawrence** [comment]
make a PR and I'll review further its easier that way. but you'll be moving some stuff into the write method that is current in the ensure.

**Comment by alyosha** [comment]
just pushed
https://github.com/nlopes/slack/pull/399

**Comment by alyosha** [comment]
@james-lawrence please let me know if there are any other changes you'd like to see!

**Comment by bbriggs** [comment]
@james-lawrence @alyosha93 Is this still progressing? I'd love to use it and I'd be happy to contribute or help move it forward if help is needed.

**Comment by james-lawrence** [comment]
its done. see #399

**Comment by jimsmart** [comment]
Hi,

— Wasn't sure if I should open a new issue or not...

```go
func NewSecretVerifierFromHeader(header http.Header) (SecretsVerifier, error) {
	if header["X-Slack-Signature"][0] == "" || header["X-Slack-Request-Timestamp"][0] == "" {
		return SecretsVerifier{}, errors.New("headers are empty")
	}
```

This above code will actually panic if the headers are empty — because element[0] of a slice is the first element, but if there are no headers then the map lookup will return a nil slice, which has no first element.

I believe the code should be:

```go
func NewSecretVerifierFromHeader(header http.Header) (SecretsVerifier, error) {
	if len(header["X-Slack-Signature"]) == 0 || len(header["X-Slack-Request-Timestamp"] == 0 {
		return SecretsVerifier{}, errors.New("headers are empty")
	}
```

Perhaps the error message should be `"missing header"`...?

Stylistically, one should maybe define the magic strings as consts earlier in the code, and, perhaps the action verb should be `Validate()` or `Verify()` instead of `Ensure()` (although that would be an API change now?). Just my 2p worth.

**Comment by james-lawrence** [comment]
@jimsmart I believe these concerns were fixed in #440

**Comment by james-lawrence** [comment]
if it turns out to still be an issue in master, please open a new issue.

**Comment by jimsmart** [comment]
My bad, I see that now. 
Apologies for the noise.
— Thanks for a great library!
