### ISSUE TITLE
Breakage on Google AppEngine

### ISSUE THREAD

**Issue by akfaew** [slack-go/slack#358]
Google AppEngine returns the following error when deploying code using `nlopes/slack`:

```
ERROR: (gcloud.app.deploy) Error Response: [9] Deployment contains files that cannot be compiled: Compile failed:
/work_dir/github.com/nlopes/slack/rtm.go:10:2: can't find import: "github.com/gorilla/websocket"
2018/07/18 07:11:29 go-app-builder: build timing: 7\xd7compile (3.845s total), 0\xd7link (0s total)
2018/07/18 07:11:29 go-app-builder: failed running compile: exit status 2
```

I noticed that there were some changes with dependencies recently here: https://github.com/nlopes/slack/commit/2123bd8e3090415072d6bfdab8a9096dea25ac20. I'm not sure how to investigate this further. Is `nlopes/slack` working on AppEngine for anyone?

**Comment by james-lawrence** [comment]
it looks to be related to how app engine handles the go environment. try the chat room for help, or documentation for AppEngine. issues are for bugs in the library, not for help with deployment issues.

**Comment by shubhambhuyan** [comment]
ERROR: (gcloud.app.deploy) Error Response: [9] Deployment contains files that cannot be compiled: Compile failed:
/work_dir/github.com/nlopes/slack/rtm.go:9:2: can't find import: "github.com/gorilla/websocket"

**Comment by shubhambhuyan** [comment]
i too have the same issue, need your help

**Comment by james-lawrence** [comment]
@shubhambhuyan, i'll happily debug issues within the library, but not for deployment environments.

this is likely an app engine constraint/limitation. see their [docs](https://cloud.google.com/appengine/docs/go/)

if people want to debug and discuss in this issue that's fine.
