### ISSUE TITLE
there wasn't interfaces about reminders

### ISSUE THREAD

**Issue by spriggantm** [slack-go/slack#359]
Hello,
I'm use this package for slack, but it's not have functions about reminders.
so, I try to add some code snippets like this. (file name: chat.go as temp)

type Reminder struct {
	ID         string   `json:"id"`
	Creater    string   `json:"creater"`
	User       string   `json:"user"`
	Text       string   `json:"text"`
	Recurring  bool     `json:"recurring"`
	Time       JSONTime `json:"time"`
	CompleteTS int      `json:"complete_ts"`
}

type reminderReponseFull struct {
	Reminders []Reminder `json:"reminders"`
	Reminder  Reminder   `json:"reminder"`

	SlackResponse
}

func (api *Client) AddReminder(user string, what string, when string) (*Reminder, error) {
	values := url.Values{
		"token": {api.token},
		"user":  {user},
		"text":  {what},
		"time":  {when},
	}

	response := &reminderReponseFull{}
	ctx := context.Background()
	err := post(ctx, api.httpclient, "reminders.add", values, response, api.debug)
	if err != nil {
		return nil, err
	}

	if !response.Ok {
		return nil, errors.New(response.Error)
	}

	return &response.Reminder, nil
}

func (api *Client) ReminderList() ([]Reminder, error) {
	values := url.Values{
		"token": {api.token},
	}

	response := &reminderReponseFull{}
	ctx := context.Background()
	err := post(ctx, api.httpclient, "reminders.list", values, response, api.debug)
	if err != nil {
		return nil, err
	}

	fmt.Println("reminder list res=", response)

	if !response.Ok {
		return nil, errors.New(response.Error)
	}

	return response.Reminders, nil
}

it work normally as I intent to. 
but it's not perfectly.

Could you add functions about reminders api in slack?
I think it's not difficult to apply this package.
I hope that will be soon.

thanks.

**Comment by james-lawrence** [comment]
feel free to open a [PR](https://yangsu.github.io/pull-request-tutorial/)

**Comment by kanata2** [comment]
The reminder API has already been implemented.
