### ISSUE TITLE
Change String Identifier to Int Identifier

### ISSUE THREAD

**Issue by hitesh-goel** [slack-go/slack#360]
Here https://github.com/nlopes/slack/blob/8ac1139f0b5b26ddb4a5c05b727e7ce155cc37f4/slack.go#L15 Instead of using %s as string identifier we can use %d identifier as here https://github.com/nlopes/slack/blob/8ac1139f0b5b26ddb4a5c05b727e7ce155cc37f4/misc.go#L200

time is in int.

**Comment by hitesh-goel** [comment]
i don't have access to push the branch to this repo.

**Comment by james-lawrence** [comment]
correct you have to open a PR.

**Comment by hitesh-goel** [comment]
@james-lawrence .. but I don't have access to push a branch ..

**Comment by james-lawrence** [comment]
@hitesh-goel plenty of [tutorials](https://help.github.com/articles/creating-a-pull-request-from-a-fork/) for github to get started. feel free to google around for guides.
