### ISSUE TITLE
How do I get the BotID of the current bot I am running over RTM?

### ISSUE THREAD

**Issue by MTRNord** [slack-go/slack#361]
Hi I need to ignore any messages that I sent myself when listening to the RTM stream. Most of it I am able to ignore using:

```golang
if ev.User == rtm.GetInfo().User.ID {
    continue
}
```

But what about messages where ev.User is empty? Thoose only have a ev.BotID set but I cant find a way to get the BotID of the Bot I am listening as so I cant compare them or did I miss something?

**Comment by MTRNord** [comment]
So looking at the Slack API Docs the perfect world solution would be to get the BotID either using the BotID returned on the response of PostMessage (which is sadly not accessible with this lib at all :( ) Or to use the specific message ID to check against. (Which is also not accesible)

**Comment by sosedoff** [comment]
@MTRNord here's how i did this:

- before starting the realtime connection, run `resp, err := api.AuthTest()` to verity that slack token is correct. the response will include the basic user reference
- then get the user info with `user, err := api.GetUserInfo(resp.UserID)`. from here you can get your bot's id and user id: `user.ID`

then when you handle messages (with `slack.MessageEvent`) you can skip messages from your own bot:  `if event.BotID != "" || event.BotID == myBotId -> skip`

**Comment by MTRNord** [comment]
oh wow thats a solution I would never have found :D thanks @sosedoff

**Comment by MTRNord** [comment]
~~@sosedoff am I correct that `user.ID` is `myBotId` ?~~

nvm I didnt see `user.Profile.BotID`

**Comment by sosedoff** [comment]
@MTRNord also, you can see some of my examples in this repo: https://github.com/sosedoff/slacklet/blob/master/client.go
