### ISSUE TITLE
conversations.info "user" field is not parsed

### ISSUE THREAD

**Issue by Aketzu** [slack-go/slack#365]
conversations.info returns "user" parameter for IM conversations but currently this is not parsed.

One simple fix would be to add 
```go
User      string `json:"user"`
```
to Channel struct
https://github.com/nlopes/slack/blob/347a74b1ea3055e8adcf17d2e14cbf3939238f6f/channels.go#L21-L27

When I send a message from another Slack-client I get MessageEvent specifying the IM channel and myself as sender. In order to know who the message was sent to I need to query conversations.info (or keep all IM channels in memory).

Another way would be to use conversations.members but it is a bit harder to iterate over list and check which of the two is not myself.

**Comment by james-lawrence** [comment]
simple fix is reasonable. if the data is sent we should parse it.

**Comment by daniellockard** [comment]
Doesn't the JSON having `user` only exist in 1-to-1 conversations?

**Comment by james-lawrence** [comment]
@daniellockard then it'll be empty for other types? =p
