### ISSUE TITLE
Unable to create interactive messages with replace_original=false

### ISSUE THREAD

**Issue by wgyn** [slack-go/slack#367]
On the `Msg` object, the `ReplaceOriginal` field has a `bool` type but the json format string specifies `omitempty`. As such, it's not possible to marshal an instance with `ReplaceOriginal: false`. This is useful for interactive messages as described in https://api.slack.com/docs/interactive-message-field-guide.

One fix is to make the relevant fields from above pointers. I think this at least makes sense for the non-required boolean fields in the above link. On the other hand it would be a breaking change to your API...

Any thoughts? I'm happy to submit a PR but not sure how you typically handle breaking changes.

Proposed:
```
type Msg {
  ...
  ReplaceOriginal *bool `json:"replace_original,omitempty"`
  DeleteOriginal *bool `json:"delete_original,omitempty"`
}

**Comment by james-lawrence** [comment]
because false is the default behaviour? I'm not sure I understand what the issue is?

**Comment by wgyn** [comment]
Here's an illustration with more detail: https://play.golang.org/p/UWTcEVoZHjT.

**Snippet**
```
package main

import (
	"fmt"
	"encoding/json"
)

func main() {
  req1 := struct {
    Foo bool `json:"foo,omitempty"`
  }{
    false,
  }
  b1, _ := json.Marshal(req1)
  fmt.Println("Current behavior: ", string(b1))

  f := false
  req2 := struct {
    Foo *bool `json:"foo,omitempty"`
  }{
    &f,
  }
  b2, _ := json.Marshal(req2)
  fmt.Println("Desired behavior: ", string(b2))  
}
```

**Result**
```
Current behavior:  {}
Desired behavior:  {"foo":false}
```

Per above, it's not possible to make a request with `replace_original=false`.

**Comment by ezhao** [comment]
It looks like the Slack API is assuming `replace_original=true` if `replace_original` is not provided (at least in some situations `true` is default). There's no way to override this default with this library as written because there's no way to send `false` (it will be omitted as empty).

**Comment by james-lawrence** [comment]
I understood the behaviour of the json serialization, my assumption was that it was defaulting to false, in the slack api.

removing the omit_empty is the correct solution. feel free to drop a PR with the change will merge it. this is not a breaking change to remove the omit_empty as its a flat out bug.
