### ISSUE TITLE
File(s) in RTM messages are not parsed anymore

### ISSUE THREAD

**Issue by Aketzu** [slack-go/slack#368]
Due to Slack API changes handling of files has changed. More info in https://api.slack.com/changelog/2018-05-file-threads-soon-tread

For example in RTM message there is no more `file`-object but `files`-array. 

One simple fix would be to change
https://github.com/nlopes/slack/blob/347a74b1ea3055e8adcf17d2e14cbf3939238f6f/messages.go#L72
to
```go
       Files []File `json:"files,omitempty"`
```

**Comment by james-lawrence** [comment]
feel free to submit a PR.

**Comment by bearcherian** [comment]
@Aketzu I think #366 resolves this

**Comment by ofirventura** [comment]
There's still a problem with getting the files. please see the new PR regarding this issue (tested it works) : "Slack API changed the files object to list"
