### ISSUE TITLE
Ability to send raw JSON directly to websocket

### ISSUE THREAD

**Issue by sosedoff** [slack-go/slack#373]
I was looking through the code and found that there's a way to send the raw json directly to the websocket connection, however this function is not exposed as public package function. There's only one function that takes `slack.OutgoingMessage` here https://github.com/nlopes/slack/blob/2e06c71c93f07db8f6c02a0cf5454cb0125b57c6/websocket.go#L98-L105

I'd be interested to add the `rtm.SendRawMessage(data interface()) error` method so i can write data without having to construct the outgoing message first. 

Any thoughts on this?

**Comment by james-lawrence** [comment]
what are you actually trying to accomplish?

**Comment by sosedoff** [comment]
my original goal was to have ability to send a custom message (in rtm) that i get from a third-party source, so message itself is not constructed with go.

**Comment by james-lawrence** [comment]
just decode -> encode the message? sounds like you're trying to use the library as a proxy?

**Comment by sosedoff** [comment]
yeah, i think my ask is out of scope for this package, so im closing the issue.
