### ISSUE TITLE
edit Ephemer message

### ISSUE THREAD

**Issue by SulimNikita** [slack-go/slack#387]
If I change the ephemeral message, using "slack.MsgOptionUpdate(payload.MessageTs)", I get the message note found
`_,_,_,err = slkBot.SendMessageContext(
		context.Background(),
		payload.Channel.ID,
		slack.MsgOptionAttachments(params.Attachments...),
		slack.MsgOptionPostMessageParameters(params),
		slack.MsgOptionUpdate(payload.MessageTs),`

**Comment by james-lawrence** [comment]
unfortunately this is because of how slack handles the API.

I actually have a personal [branch](https://github.com/james-lawrence/slack/tree/response-url-hacks) where its possible to update ephemeral messages. but havent had time to cleanup/rethink the code.

**Comment by gtrindade** [comment]
That branch has a lot of refactoring... if anyone needs a simple way to update/delete ephemeral messages, I added these two functions to chat.go and it worked.
```go
// DeleteEphemeral deletes the ephemeral message, use the responseURL from the action payload in your ephemeral message. Only works for the interactive ones.
func (api *Client) DeleteEphemeral(responseURL string) (*SlackResponse, error) {
	message := Msg{
		ResponseType:    "ephemeral",
		Text:            "",
		ReplaceOriginal: true,
		DeleteOriginal:  true,
	}
	return api.SendResponse(responseURL, message)
}

// SendResponse Will send a json response marshalled from Msg as string using the responseURL as endpoint.
func (api *Client) SendResponse(responseURL string, message Msg) (*SlackResponse, error) {
	payload, err := json.Marshal(message)
	if err != nil {
		return nil, err
	}
	json := []byte(payload)
	response := &SlackResponse{}
	err = postJSON(context.Background(), api.httpclient, responseURL, api.token, json, response, api)
	return response, err
}
```
I would try and PR this into the main repo, but I couldn't figure out how to run tests.. feel free to use/copy this code into the main repo.

**Comment by james-lawrence** [comment]
to run the tests:

`go test ./...`

and yes that branch has a lot of refactoring in it was written a long time ago and i just rebase periodically. =)

there are easier ways now i believe. but havent tried them.

**Comment by gtrindade** [comment]
I did that, but thought all the
```
read error: websocket: close 1006 (abnormal closure): unexpected EOF
```
was a sign that additional setup is needed? but didn't find any docs in the repo. Is that expected? Some tests will still run, but some will fail with issues that seem unrelated to my code:
```
--- FAIL: TestServerSendMessageToChannel (2.00s)
    server_test.go:32:
        	Error Trace:	server_test.go:32
        	Error:      	Should be true
        	Test:       	TestServerSendMessageToChannel
```

**Comment by james-lawrence** [comment]
if you use the latest master the server_test.go error is fixed. the unexpected EOF is normal unfortunately, I havent had a chance to investigate them but they are not actually issues just noise.

**Comment by Primetalk** [comment]
@gtrindade, I've put your changes in the PR https://github.com/nlopes/slack/pull/569.

**Comment by Primetalk** [comment]
@james-lawrence could you help me understand, how to delete ephemeral message having only `ResponseURL`?
