### ISSUE TITLE
Add CI Build

### ISSUE THREAD

**Issue by joefitzgerald** [slack-go/slack#39]
Suggestion: Travis or Wecker.
Rationale: We need to run tests to verify we're not introducing regressions in PRs.

**Comment by nlopes** [comment]
:+1: I am currently cherry picking @abourget changes and after that, will make sure all tests pass and the library still works. Will also add some docs and add CI (most likely travis but I'll still need to check)

**Comment by joefitzgerald** [comment]
Can I suggest adding Travis as a first step, so that all future work (including your cherry picking) is proven to not cause test regression? All I need in the short term is for you to go to travis-ci.org and enable CI for this repo - after that, I can add a .travis.yml file in a new PR and ensure it works.

**Comment by nlopes** [comment]
Sounds like a plan. Also, I am currently updating things using https://github.com/nlopes/slack/tree/nlopes-breaking-changes)

**Comment by nlopes** [comment]
Done.
