### ISSUE TITLE
Info.Channels{} returning an empty slice

### ISSUE THREAD

**Issue by agis** [slack-go/slack#397]
Hello. I'm using the code from https://github.com/nlopes/slack/blob/master/examples/websocket/websocket.go#L27.

I'm trying to fetch the channel list by doing `ev.Info.Channels`, but apparently it's an empty slice.
The print statement outputs something like this:

```
Infos: &{wss://cerberus-xxxx.lb.slack-msgs.com/websocket/m3eJaEnHNvwWTq9LUA-V7NZbQcg0BQockbFRNDQFYTBPlvRlANLVpWdXHbRLPz9JnaGFGrjho76nIVyAuJWiEa_EWPIdXaVMRJQI1mGnuQ= 0xc0002da040 0xc00012a4e0 [] [] [] [] []}
```

I've given every scope to the bot. Doing a `client.Channels()` works though.

Any ideas?

**Comment by james-lawrence** [comment]
@agis iirc slack deprecated that functionality. really shouldn't be there anymore.
