### ISSUE TITLE
Build fails: conversation.go undefined: post

### ISSUE THREAD

**Issue by fscnick** [slack-go/slack#400]
Today, I tried to build with docker and it replied as follow:

github.com/nlopes/slack/conversation.go:137:8: undefined: post

It was ok yesterday. 
And I notice there is a commit few hours ago.

**Comment by mikepqr** [comment]
Looks like 
```
err = post(ctx, api.httpclient, "users.conversations", values, &response, api.debug)
```
should be
```
err = postSlackMethod(ctx, api.httpclient, "users.conversations", values, &response, api.debug)
```

**Comment by suzuki-shunsuke** [comment]
I'm sending PR to fix it.

#401
