### ISSUE TITLE
Client should support batched presence updates

### ISSUE THREAD

**Issue by theckman** [slack-go/slack#403]
Slack made a change in the API last year that would cause `presence_change` events to no longer be sent over the RTM connection if you're using the original format. Instead, clients needed to opt-in to the new batched `presence_change` events (as it's a breaking API change) if they wanted to subscribe to presence change notifications of users:

- https://api.slack.com/docs/presence-and-status#batching

To accomplish this we'll need to update the `PresenceChangeEvent`'s `User` field to be an `[]string`. We can then pass the new option when making the `rtm.connect` API call.

**Comment by suekto-andreas** [comment]
hi @theckman, @james-lawrence  - created a PR for this enhancement, kindly browse in: https://github.com/nlopes/slack/pull/444
