### ISSUE TITLE
Support authentication changes

### ISSUE THREAD

**Issue by alanak** [slack-go/slack#406]
Currently in [Developer Preview](https://api.slack.com/workspace-apps-preview), Workspace Apps require support for refresh tokens for oauth.

**Comment by james-lawrence** [comment]
feel free to contribute the functionality =)

**Comment by qezz** [comment]
Workspace Apps were considered legacy, https://api.slack.com/legacy-workspace-apps

**Comment by james-lawrence** [comment]
yeah still changes are coming down the pipe. going to update this issue to reflect that.

**Comment by rustycl0ck** [comment]
Isn't this a duplicate of #973 which is now resolved. Although having some sample of this in the examples would be great.
