### ISSUE TITLE
don't crash when json can't be unmarshalled

### ISSUE THREAD

**Issue by voldyman** [slack-go/slack#41]
Currently when a file is uploaded and the json can't be unmarshelled the lib class log.fatal instead it should panic so the code calling it can recover and does not need to manuall restart since log.Fatal calls os.Exit(1)

**Comment by nlopes** [comment]
The new master tree should no longer have this problem. Would you mind testing that and let me know? I know you'll have to adapt the code a bit as the current master tree has some breaking changes - apologies for that.

**Comment by voldyman** [comment]
I'll check, thanks :+1:

**Comment by nlopes** [comment]
Feel free to reopen if you still see this issue.

**Comment by voldyman** [comment]
http://dave.cheney.net/2015/11/05/lets-talk-about-logging
:point_up:  post is very relevant to this issue
