### ISSUE TITLE
NewGroupedSelectDialogInput() output appears in random order

### ISSUE THREAD

**Issue by akfaew** [slack-go/slack#419]
`func NewGroupedSelectDialogInput(name, label string, groups map[string]map[string]string) *DialogInputSelect`

Since the input argument of this function is a map, and the function itself does nothing to enforce an order, the output is random.

**Comment by james-lawrence** [comment]
ouch. we should fix that, easiest way is to change the method signature to something less awful than map[string]map[string]string
