### ISSUE TITLE
v0.4.0 has major breaking change...

### ISSUE THREAD

**Issue by ArcticSnowman** [slack-go/slack#427]
While updating to v0.4.0 found that it breaks https://github.com/BeepBoopHQ/go-slackbot..

```
# gsg/loki/vendor/github.com/BeepBoopHQ/go-slackbot
src/gsg/loki/vendor/github.com/BeepBoopHQ/go-slackbot/bot.go:124:40: cannot use "" (type string) as type slack.MsgOption in argument to b.Client.PostMessage
src/gsg/loki/vendor/github.com/BeepBoopHQ/go-slackbot/bot.go:124:40: cannot use params (type slack.PostMessageParameters) as type slack.MsgOption in argument to b.Client.PostMessage
```

Digging into this found that the PR #396  changed the call signature for PostMessage and others in chat.go but no mention is made in the commit or release for this.

This is a failure major change in the way you send messages...

**Comment by ArcticSnowman** [comment]
Woops...  now I find the reference...
 ```
Breaking: Msg structure files field changed to an array.
```
Might need a bit of expanding on that...

**Comment by patcon** [comment]
Also, breaking changes could probably be a major version bump in the future, out of consideration for users updating

**Comment by james-lawrence** [comment]
[semantic version 2.0](https://semver.org/#spec-item-4):
```
4. Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.
```

so while I do try to limit break changes, right now no promises are made. 0.4.0 actually was me biting the bullet and breaking a bunch of stuff simultaneously to move some things forward.

**Comment by patcon** [comment]
I totally respect the thought process, but just want to push back on the idea that hitting v1 needs to be some major cultural FOSS event. If there are 2000 stars (and presumably _many_ more users), we should prob not imagine this as "initial dev", right? So if we're breaking an API, should we not just bump the major version?

Again, not criticizing -- I  see where you were coming from @james-lawrence (and I also huuuuugely appreciate your stewardship!)
