### ISSUE TITLE
GetOAuthResponseContext() has an unexported type in the signature

### ISSUE THREAD

**Issue by akfaew** [slack-go/slack#436]
Commit 8b3b6ec4716f1ec88e32904ef41e303107b2dec7 entitled "remove globals" includes this change:
```
-func GetOAuthTokenContext(ctx context.Context, clientID, clientSecret, code, redirectURI string, debug bool) (accessToken string, scope string, err error) {
-       response, err := GetOAuthResponseContext(ctx, clientID, clientSecret, code, redirectURI, debug)
+func GetOAuthTokenContext(ctx context.Context, client httpClient, clientID, clientSecret, code, redirectURI string, d debug) (accessToken string, scope string, err error) {
+       response, err := GetOAuthResponseContext(ctx, client, clientID, clientSecret, code, redirectURI, d)
```
The type `debug` is unexported. How can I use this function? Ping @james-lawrence

**Comment by james-lawrence** [comment]
well technically debug is an interface so it doesn't need to be exported. you just need to pass something that satisfies it. that being said.... it shouldn't be part of this particular function. if you want to send a PR removing the debug parameter from it that'd actually be helpful.
