### ISSUE TITLE
Security issues in SecretsVerifier

### ISSUE THREAD

**Issue by adamrothman** [slack-go/slack#439]
Hi! I've noticed a couple of security issues in the implementation of `SecretsVerifier`. Specifically, there are two important ways in which it diverges from the recommendations set forth in the documentation here: https://api.slack.com/docs/verifying-requests-from-slack.

First, and most important: `SecretsVerifier` uses `==` to compare the request signature and the expected signature. This leaks timing information, as `==` short-circuits to `false` as soon as it encounters a non-matching character. It should instead use [`hmac.Equal`](https://golang.org/pkg/crypto/hmac/#Equal), which is specifically implemented to perform such a comparison without leaking timing information. The docs call this out specifically:

>Note: for best practice, use an hmac compare function instead of directly comparing the signatures for equality.

Additionally, `SecretsVerifier` does not check that the timestamp is recent. From the docs:

>While you're extracting the timestamp, check to make sure that the request occurred recently.

There's no officially recommended timeframe, but the example in the docs uses 5 minutes which seems reasonable.

I'd be happy to submit a PR with these improvements, if so desired.

P.S.: Not a security issue, but I think semantically it makes more sense to rename this struct to `SignatureVerifier`. We could drop in a type alias (e.g. `type SecretsVerifier = SignatureVerifier`) if preserving backwards compatibility is a concern.

**Comment by james-lawrence** [comment]
@adamrothman mind reviewing the mentioned PR?

**Comment by adamrothman** [comment]
Left a few comments. Thanks for following up so quickly @james-lawrence!
