### ISSUE TITLE
Dialog NewUsersSelect func providing valid struct

### ISSUE THREAD

**Issue by kneal** [slack-go/slack#448]
I have been working with some of the dialog functions and I am noticing some potential bugs. Just wanted to see if others have been having issues. I am using the NewUsersSelect function and I seem to be getting a `validation_errors` response from Slack.

Example usage:

```go
var elements = []slack.DialogElement{
	slack.NewUsersSelect("user", "User"),
}
``` 

It seems `validation_errors` is a generic error from Slack that means the elements being posted have an error.
https://api.slack.com/methods/dialog.open#errors

Is anyone else successfully using those select elements with the library? And would it be possible to get the verbose error Slack gives you in the `response_metadata` of the `validation_errors` error.

**Comment by james-lawrence** [comment]
I havent tested the user select stuff from slack personally there are likely bugs as most of the events/interactions stuff is newish and hasnt really settled.
