### ISSUE TITLE
New Release 

### ISSUE THREAD

**Issue by dmeyer22** [slack-go/slack#450]
The new state within dialogs would really make my life easier. As it is already implemented in master, is there a plan to have a new release?

**Comment by asim** [comment]
Just to add to this comment. @nlopes could you make a new release please. There's breaking changes in master since September and any dependency system basically uses tags so everything relying on it breaks. A new release would be appreciated. Thanks!

**Comment by james-lawrence** [comment]
@asim he doesn't maintain the repository anymore. =) I'll do a new release soon.

**Comment by asim** [comment]
Thanks, much appreciated!

**Comment by james-lawrence** [comment]
havent forgotten this saturday i'll cut a release.

**Comment by james-lawrence** [comment]
0.5.0 tagged
