### ISSUE TITLE
Confusing http.Client in GetOAuthResponse

### ISSUE THREAD

**Issue by dominhtri1995** [slack-go/slack#460]
Hi,

I'm pretty new here and I have no idea what to pass in as http.client (first argument) for GetOAuthResponse. Can someone give me an example ? Thank you.

I don't know why it has to be this complicated while we can just default any client and get the job done behind the scene. It's just a simple http request after all

**Comment by james-lawrence** [comment]
http.DefaultClient if you don't know what to use. its a parameter because you may want to adjust the timeouts, proxy information, etc of the client.

technically I believe those methods need to be reworked anyways but not for this particular reason.
