### ISSUE TITLE
Add support for mpim methods

### ISSUE THREAD

**Issue by nlopes** [slack-go/slack#47]
Multi-party DM methods! All prefixed with mpim and include:.close, .history, .list, .mark, and .open

**Comment by nlopes** [comment]
Worked tracked at https://github.com/nlopes/slack/pull/62

**Comment by james-lawrence** [comment]
looking for this feature, any progress on it or shall I finish implementing it?

**Comment by ddavyd0v** [comment]
Looking for this feature as well. What is the status?
