### ISSUE TITLE
Optional raw json in Api

### ISSUE THREAD

**Issue by Bmsandoval** [slack-go/slack#475]
I would like to be able to define my json responses in templatized view files and pass the rendered json (as []byte) directly to the api calls. Api calls such as OpenDialog can get hairy as Go isn't designed for nice looking json in a hurry, and extensive as your documentation is, it's difficult to see how to convert slack's raw json from their documentation into the sea of structs.

**Comment by james-lawrence** [comment]
if you can figure out a workable way to use json.RawMessage as the message contents as an escape hatch.... I may consider it depending on the changes required. (i.e. the smaller the API surface changes the better.) it'll also be marked as unsafe, won't put api compatibility promises on such a thing.

but this isn't something I'm going to actively pursue.
