### ISSUE TITLE
MsgOptionIconEmoji is not defined

### ISSUE THREAD

**Issue by knrt10** [slack-go/slack#477]
I am trying to post a message using `api.PostMessage` and for `MsgOption` I am trying to use `slack.MsgOptionIconEmoji()` but it is not defined. Image below describes my problem. Is it removed in latest version 0.5.0?

![screenshot 2019-02-19 at 7 57 53 pm](https://user-images.githubusercontent.com/24803604/53022304-f0af7680-3480-11e9-9fc8-97757af388dc.png)

**Comment by james-lawrence** [comment]
https://github.com/nlopes/slack/commit/3eeba02d932d1877a83748f46f08483a6768aa7e#diff-1f9eebfe78e8930de1a3795966f172b3 ?

**Comment by gruutak** [comment]
I'm having the same issues. Any way to fix it?
