### ISSUE TITLE
Send message to channel by name instead of id?

### ISSUE THREAD

**Issue by mehlium** [slack-go/slack#49]
Hi, and thanks for this cool library. I have a small issue sending messages to channels by using name ('#general'). Using the channel id works just fine, but it's kind of tedious to maintain. 

The RTM example on https://github.com/nlopes/slack/blob/master/examples/websocket/websocket.go uses #general (alltough it says to replace that name with the channel id). Is this library supposed to work with channel names, or do I have to lookup the channel id by name, when creating the client? Sorry to open a new issue for this.. :-)

**Comment by nlopes** [comment]
Yeah, unfortunately that's what the underlying requests expect. You can always use the info you get back on a ConnectedEvent (https://github.com/nlopes/slack/blob/master/examples/websocket/websocket.go#L26) to map a channel name to a channel id. I try very much to not maintain any state inside the library.

**Comment by mehlium** [comment]
Ah, I didn't know that! Thanks :-) Yeah, understandable :-)
