### ISSUE TITLE
GetChannelInfo fails if channel history has Block messages

### ISSUE THREAD

**Issue by khayyamsaleem** [slack-go/slack#493]
Because `GetChannelInfo` includes recent messages, and blocks were just recently supported here, `GetChannelInfo` is failing, with the error:
`json: cannot unmarshal object into Go struct field Message.blocks of type slack.Block`

**Comment by khayyamsaleem** [comment]
@alyosha #476 #490

**Comment by khayyamsaleem** [comment]
my workaround for getting a list of members for a channel without `GetChannelInfo`:
```go
slackAPI := slack.New(os.Getenv("SLACK_TOKEN"))
allUsers, _, err := slackAPI.GetUsersInConversation(&slack.GetUsersInConversationParameters{
	ChannelID: os.Getenv("SLACK_CHANNEL_ID"),
	Cursor:    "",
	Limit:     100,
})
//allUsers is an array of userIDs (strings)
```

**Comment by alyosha** [comment]
This same error will occur for interaction callbacks, and any other method that tries to unmarshal the block JSON into the Block interface. Should be addressed in the same PR I mentioned in https://github.com/nlopes/slack/issues/476 thanks for the mention :+1:

**Comment by james-lawrence** [comment]
can we confirm this has been fixed?

**Comment by jwatroba** [comment]
@khayyamsaleem are you able to confirm if this is fixed? Thanks.

**Comment by khayyamsaleem** [comment]
@jwatroba i've since been using the workaround i mentioned, but I can try reverting and get back to you.

**Comment by alyosha** [comment]
@khayyamsaleem any update on this? think it should probably be resolved

**Comment by khayyamsaleem** [comment]
@alyosha just confirmed, master's GetChannelInfo function works

**Comment by james-lawrence** [comment]
great, closing.
