### ISSUE TITLE
Crash with unmarshallable json...

### ISSUE THREAD

**Issue by tcolgate** [slack-go/slack#5]
First off, thanks for the pkg. I was originally using hal, but have moved over to using your api and a tiny custom framework, and it's a real pleasure so far.

My bot is periodically dying, I suspect possibly due to something int he latency response code, I'll take a look soon, but thought I'd report it here just incase:

json: cannot unmarshal number into Go value of type slack.JSONTimeString

I've not got a definitive way of triggering the problem yet. Will send a PR if I work it out.

**Comment by nlopes** [comment]
Thank you for the report @tcolgate . SetDebug(true) might help. This will print out all events being received. The api is a bit inconsistent and sometimes slack returns a unix timestamp, other times it returns a string so I may have missed one of those cases.

Also, are you using the latest code in here? That bug definitely existed before I corrected some code last week.
