### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by tedder** [slack-go/slack#506]
James- there are some merges that aren't released. Can you do so? My purposes are [this](https://github.com/nlopes/slack/commit/68a9954511dd7825dc9b3744a68b51398ce120b1) but I'm sure it'd be appreciated by others too.

**Comment by james-lawrence** [comment]
Going to wait until the block changes land. there are current bugs in master due to some of the block changes. do not want to tag until those are resolved.

**Comment by sjkaliski** [comment]
Hi! Thank you so much for this library, it's been awesome to use. Is there an update on timing for this release? Are there any open tickets related to this release? I'd be more than happy to help out 😃!

**Comment by james-lawrence** [comment]
https://github.com/nlopes/slack/issues/493 at a minimum needs to be resolved.

**Comment by sway** [comment]
Now that #493 is closed, when do you think there will be a new release? We'd love to make use of BlockKit with the library...

**Comment by sway** [comment]
@james-lawrence Any plan for a release?

**Comment by dewey** [comment]
#245 is also resolved once this is done

**Comment by james-lawrence** [comment]
I'm a horrible human, but its done. v0.6.0 is released.

on a related note is there anyone who'd like to pick up the release work? I don't mind PR reviews/issue management as i just schedule it consistently. releases are just too spread out for me to care in particular.

**Comment by dewey** [comment]
@james-lawrence Thanks a lot, you are not a horrible human! 🥇

**Comment by sjkaliski** [comment]
@james-lawrence thank you!!

**Comment by ahuff44** [comment]
thank you!

**Comment by sway** [comment]
Thanks a lot!
