### ISSUE TITLE
slack.Block is not a thing anymore?

### ISSUE THREAD

**Issue by grvlle** [slack-go/slack#507]
After running mod init in my Slack bot projects folder, the method doesn't exist in the library. slack.Attachment and others are though. 

Since this is a newer implementation I figured I'd try to update the package, but the go pkg manager claims to have the latest build.

Below is present in my go.mod
> github.com/nlopes/slack v0.5.0

When trying to update all packages, I get below error message too. 

Below is the output of `go get -u all`
```
grvlle$ go get -u all                                                      :(
go: finding github.com/lusis/go-slackbot latest
go: finding github.com/erikstmartin/go-testdb latest
go: finding golang.org/x/crypto latest
go: finding github.com/denisenkom/go-mssqldb latest
go: finding github.com/jinzhu/inflection latest
go: finding github.com/lusis/slack-test latest
go: finding gopkg.in/check.v1 latest
github.com/lusis/slack-test
../../../go/pkg/mod/github.com/lusis/slack-test@v0.0.0-20190408224659-6cf59653add2/types.go:80:2: undefined: slack.WebResponse
github.com/lusis/go-slackbot
../../../go/pkg/mod/github.com/lusis/go-slackbot@v0.0.0-20180109053408-401027ccfef5/bot.go:173:8: params.Attachments undefined (type slack.PostMessageParameters has no field or method Attachments)
../../../go/pkg/mod/github.com/lusis/go-slackbot@v0.0.0-20180109053408-401027ccfef5/bot.go:175:50: cannot use "" (type string) as type slack.MsgOption in argument to b.Client.PostMessage
../../../go/pkg/mod/github.com/lusis/go-slackbot@v0.0.0-20180109053408-401027ccfef5/bot.go:175:50: cannot use params (type slack.PostMessageParameters) as type slack.MsgOption in argument to b.Client.PostMessage
```

**Comment by alyosha** [comment]
@grvlle you're using release tag `0.5.0` but at that point in time the `Block` logic was not yet present in the project

**Comment by grvlle** [comment]
Figures. Thanks @alyosha for the quick reply! How do I go about and update to the latest version? `go get -u github.com/nlopes/slack/` seems to assume 0.5.0 is the latest version. I guess I can clone it manually as a last resort.

**Comment by sekka1** [comment]
I was just trying to use this also and had the same question.  I ran into this article:  https://medium.freecodecamp.org/an-intro-to-dep-how-to-manage-your-golang-project-dependencies-7b07d84e7ba5

Wrote this down in my notes for future me:

```
dep init
```

Say I want to use "github.com/nlopes/slack" from master instead of one of the releases.  In the `Gopkg.toml`
file change:

```
[[constraint]]
  name = "github.com/nlopes/slack"
  #version = "0.5.0"
  branch = "master"
```

Then run
```
dep ensure
```

This might take a minute.

If you do a:
```
git diff
```

You should see that the `Gopkg.lock` file has changed to the master.

**Comment by grvlle** [comment]
Amazing! Thanks @sekka1. This can be closed.

**Comment by kendung** [comment]
Actually, I followed the instruction to point to the master branch. But When I use Jenkins to build, it does not respect the configuration. In other words, It is still looking for the 0.5.0 release version.

Can We make a new release?
