### ISSUE TITLE
Slash command doesn't implement signing_key verification

### ISSUE THREAD

**Issue by ghostsquad** [slack-go/slack#511]
https://github.com/nlopes/slack/blob/master/security.go

https://github.com/nlopes/slack/blob/master/slash.go

I'm trying to write an implementation of this, but I can't figure out how to run ParseForm and read the body (in order to do the verification), but it seems I can't do both?

**Comment by james-lawrence** [comment]
what do you need to do the verification that requires reading the body of the request? but you can likely copy the request and read the body from one, form from the other.

since I havent looked at the signing key verification stuff i'm lacking context =)

**Comment by ghostsquad** [comment]
I might have figured it out.. maybe. The problem is that the signing key verification needs access to the body, but so does the ParseForm function on the request. I think I figured out that once I'm done reading the body for verification, I can restore it before calling ParseForm

**Comment by ghostsquad** [comment]
I can submit a PR to have slash commands perform the signing request validation, but likely there will be a different API to support that, as it requires the signing request secret to be passed in.

**Comment by james-lawrence** [comment]
so ghost I'm just going to need to see code before I can comment on anything for this really. feel free to submit a PR.

**Comment by alyosha** [comment]
@ghostsquad are you thinking of something like this?
https://github.com/alyosha/slack-utils/blob/master/verify.go#L40

**Comment by ghostsquad** [comment]
Yes

**Comment by james-lawrence** [comment]
closing out, resolved.

**Comment by ghostsquad** [comment]
@james-lawrence where's the verification? I'm not sure how this is fixed.

**Comment by james-lawrence** [comment]
ah, I misunderstood the link thought it was to a method in this repo. I'd be happy to add a similar function to slackutilx.

**Comment by rking788** [comment]
This seems related to a pull request I submit yesterday but this seems like it might be the preferred way to handle this situation by having it run the verification and parse the command in one step? 

https://github.com/nlopes/slack/pull/541
