### ISSUE TITLE
make statusCodeError exported?

### ISSUE THREAD

**Issue by tedder** [slack-go/slack#517]
Since statusCodeError isn't StatusCodeError [I can't sniff the type in the golang way](https://blog.golang.org/error-handling-and-go). Is there any reason it can't or shouldn't be exported?

**Comment by james-lawrence** [comment]
```
type statuscode interface {
   HTTPStatusCode() int
}

if statuserr, ok := err.(statuscode); ok {
   log.Println("status code", statuserr.HTTPStatusCode())
}
```

will happily accept a PR for a utility function to extract this information quickly in hte slack utils package.
