### ISSUE TITLE
GetChannels does not support pagination

### ISSUE THREAD

**Issue by jescarri** [slack-go/slack#522]
If Slack team has more than 1k channels, there's no way to get the complete list of channels.

**Comment by james-lawrence** [comment]
A PR for this will be accepted, but must follow pagination style of the get users method. (i.e. return and accept pagination information) it must not try to load everything inside a single method call before returning.

**Comment by jescarri** [comment]
Thanks @james-lawrence i've been super busy this last weeks, I will update my PR in the upcoming weeks, but if someone else tackles it before me is fine.

**Comment by atreya2011** [comment]
@james-lawrence 

If it is ok with you and @jescarri I can make a pull request for a `GetAllChannels` method along the same lines as https://github.com/nlopes/slack/issues/545
