### ISSUE TITLE
Updating attachment bar color

### ISSUE THREAD

**Issue by sunnylbk** [slack-go/slack#524]
Is there a way to update an existing attachment bar color in slack by knowing the timestamp associated with that attachment?

Thanks

**Comment by james-lawrence** [comment]
this can be achieved by retrieving the message, modifying it, and updating it.

I believe the library supports everything needed to do this. only thing I'm not 100% on is retrieving the message by timestamp.

if you find its not possible to do this, feel free to detail what exactly is missing, and we can discuss how to fix the gaps.

**Comment by brainexe** [comment]
small example where I'm updating an attachment using this library (incl the color): https://github.com/innogames/slack-bot/blob/master/client/jenkins/start_build.go#L66,L76

- first send the initial message (store the `msgTimestamp`)
- afterwards use use `SendMessage()` with `slack.MsgOptionUpdate(msgTimestamp),` again to update the iniitial attachment (just pass a changed attachment as parameter)
