### ISSUE TITLE
Multiple Slacks support

### ISSUE THREAD

**Issue by Fryyyyy** [slack-go/slack#526]
Hi

Is there a canonical example of how to use this API to support multiple Slack workspaces, as more than one team installs the Bot?
Do I need to create multiple Slack Client or RTM objects ?

**Comment by alyosha** [comment]
I would assume you need one client per workspace, each instantiated using a token that is authorized for that org. what exactly is the use case?

**Comment by Fryyyyy** [comment]
That's how I ended up implementing it in the meantime.
The use case is a Slack app that multiple people can independently install.
As it stands right now I have to capture the bot access tokens the OAuth flow gives me upon install, add them to my config file and restart the binary.

**Comment by alyosha** [comment]
are we talking about listing an app on the slack app directory so that other teams can download it?

**Comment by Fryyyyy** [comment]
Yes, I've made my app public and available to other Slacks, although not gone as far as publishing it on the Slack app directory

**Comment by james-lawrence** [comment]
Yes, a client must be instantiated per workspace (token). and the users of this library are responsible for determining how those tokens are stored, managed, and used.
