### ISSUE TITLE
slack.ConnectedEvent event ev.Info no longer contains user/channel info ?

### ISSUE THREAD

**Issue by Dieterbe** [slack-go/slack#532]
Hello!
first of all thanks for the good work.
been using the library for a hobby project with success!

One thing I noticed is that with this code (upon startup of the connection):
```
		case msg := <-d.rtm.IncomingEvents:
			switch ev := msg.Data.(type) {
			case *slack.ConnectedEvent:
				log.Info("Connected to slack")
				 spew.Dump(ev.Info)
```
ev.Info used to be fully populated - or well at least it knew about channels -, but not anymore. I suspect this may have been due to an update of this library.

now it is more sparse:
```
(*slack.Info)(0xc0000ffad0)({
 URL: (string) (len=156) "wss://....",
 User: (*slack.UserDetails)(0xc000014fc0)({
  ID: (string) (len=9) "Ufoo",
  Name: (string) (len=5) "mrbot",
  Created: (slack.JSONTime) "Wed Dec 31",
  ManualPresence: (string) "",
  Prefs: (slack.UserPrefs) {
  }
 }),
 Team: (*slack.Team)(0xc0001bcfc0)({
  ID: (string) (len=9) "TDEADBEEF",
  Name: (string) (len=13) "<myteamname>",
  Domain: (string) (len=13) "<mydomain>"
 }),
 Users: ([]slack.User) <nil>,
 Channels: ([]slack.Channel) <nil>,
 Groups: ([]slack.Group) <nil>,
 Bots: ([]slack.Bot) <nil>,
 IMs: ([]slack.IM) <nil>
})
```

the consequence of this is that upon incoming messages, I have to issue methods like api.GetUserInfo(id) and api.GetChannelInfo(id) to see what the names of the user/channel are.
In the past i could simply look it up in the info from the connectedevent.

Am I missing something or is this a regression?
thanks!

**Comment by james-lawrence** [comment]
slack changed their API results they information isn't really provided anymore. we should strip it out fo the event. feel free to open a PR to do so.

**Comment by ghost** [comment]
@james-lawrence looking at this there are convenience methods to get Channels, Users, Groups, etc by ID that look them up via the Info struc.

I assume they should just be replaced with return nil (what they return now for everyone, since the data is missing) rather than removing them for API compatibility?

**Comment by james-lawrence** [comment]
fixed by 573
