### ISSUE TITLE
ListStars does not support pagination

### ISSUE THREAD

**Issue by atreya2011** [slack-go/slack#545]
Hello. Thanks for this great library.

As with Issue #522, ListStars does not support pagination. I have add pagination support by forking this repo and the code follows the pagination style of the get users method. Is it ok to create a PR?
Below is the added code for your review:

https://github.com/atreya2011/slack/commit/00ba37d9a08b171971263b77edbcd176b81bf337

**Comment by atreya2011** [comment]
@james-lawrence Hello, did you have time to look at my proposed code addition? If all is good, I will make a pull request.

**Comment by james-lawrence** [comment]
just looked sorry. been busy.

i'll probably have minor comments from the quick looks I just gave it.

`ListStarsPaginatedContext` method isn't actually paginated for one. but otherwise looks reasonable.

**Comment by james-lawrence** [comment]
if anyone wants to pick up atreya's code and PR it that'd be wonderful.

**Comment by atreya2011** [comment]
@james-lawrence 

My apologies for the long absence. Got tied up with work. I will make a pull request tomorrow after reviewing `ListStarsPaginatedContext` method if that is ok with you.

**Comment by james-lawrence** [comment]
merged.
