### ISSUE TITLE
Signing Secret is not working for me

### ISSUE THREAD

**Issue by nicewook** [slack-go/slack#554]
Is there only me who has this issue? 
First of all, Sorry for not have much time to test enough.

related link1: https://github.com/nlopes/slack/issues/353
related link2: https://github.com/nlopes/slack/pull/399

problem. As I followed the code (below link), verifying is not working 
- https://sourcegraph.com/github.com/nlopes/slack/-/blob/examples/slash/slash.go

I tried to check where the problem occurred, but I couldn't find any.
I leave my code which worked for me. 

```
// checkMAC reports whether messageMAC is a valid HMAC tag for message.
func checkMAC(message, receivedMAC string, slackSigningSecret []byte) bool {
	mac := hmac.New(sha256.New, slackSigningSecret)
	if _, err := mac.Write([]byte(message)); err != nil {
		log.Printf("mac.Write(%v) failed\n", message)
		return false
	}
	calculatedMAC := "v0=" + hex.EncodeToString(mac.Sum(nil))
	return hmac.Equal([]byte(calculatedMAC), []byte(receivedMAC))
}

// VerifySlackSignature verifies the request is coming from Slack
// Read https://api.slack.com/docs/verifying-requests-from-slack
func verifySlackSignature(r *http.Request, slackSigningSecret []byte) bool {
	if r.Body == nil {
		return false
	}

	// do not consume req.body
	bodyBytes, _ := ioutil.ReadAll(r.Body)
	r.Body = ioutil.NopCloser(bytes.NewBuffer(bodyBytes))

	// prepare message for signing
	timestamp := r.Header.Get(hTimestamp)
	slackSignature := r.Header.Get(hSignature)
	message := "v0:" + timestamp + ":" + string(bodyBytes)

	return checkMAC(message, slackSignature, slackSigningSecret)
}
```

**Comment by nicewook** [comment]
`// checkMAC reports whether messageMAC is a valid HMAC tag for message.
func checkMAC(message, receivedMAC string, slackSigningSecret []byte) bool {
	mac := hmac.New(sha256.New, slackSigningSecret)
	if _, err := mac.Write([]byte(message)); err != nil {
		log.Printf("mac.Write(%v) failed\n", message)
		return false
	}
	calculatedMAC := "v0=" + hex.EncodeToString(mac.Sum(nil))
	return hmac.Equal([]byte(calculatedMAC), []byte(receivedMAC))
}

// VerifySlackSignature verifies the request is coming from Slack
// Read https://api.slack.com/docs/verifying-requests-from-slack
func verifySlackSignature(r *http.Request, slackSigningSecret []byte) bool {
	if r.Body == nil {
		return false
	}

	// do not consume req.body
	bodyBytes, _ := ioutil.ReadAll(r.Body)
	r.Body = ioutil.NopCloser(bytes.NewBuffer(bodyBytes))

	// prepare message for signing
	timestamp := r.Header.Get(hTimestamp)
	slackSignature := r.Header.Get(hSignature)
	message := "v0:" + timestamp + ":" + string(bodyBytes)

	return checkMAC(message, slackSignature, slackSigningSecret)
}`

**Comment by martinplouy** [comment]
Hi @nicewook 

Here is the code I used to verify the signature 

```
 // VerifyRequest verifies a request coming from Slack
func VerifyRequest(req *http.Request) error {
	secretVerifier, err := slack.NewSecretsVerifier(req.Header, signingSecret)
	if err != nil {
		return errors.Wrap(err, "NewSecretsVerifier failed")
	}

	body, err := ioutil.ReadAll(req.Body)
	if err != nil {
		return errors.Wrap(err, "ReadAll failed")
	}

	// we need to reset the body to avoid unexpected side effects
	req.Body = ioutil.NopCloser(bytes.NewBuffer(body))

	_, err = secretVerifier.Write(body)
	if err != nil {
		return errors.Wrap(err, "Ensure failed")
	}

	err = secretVerifier.Ensure()
	if err != nil {
		return errors.Wrap(err, "Ensure failed")
	}

	return nil
}
```

I hope it helps

**Comment by treeder** [comment]
Thanks @nicewook that worked perfectly for me.

**Comment by nicewook** [comment]
> Thanks @nicewook that worked perfectly for me.

That's good! sorry for not having time for my case debugging
