### ISSUE TITLE
(api *Client) GetUsersContext() doesn't return error

### ISSUE THREAD

**Issue by henkejosh** [slack-go/slack#557]
Actual Behavior: 
The `(api *Client) GetUsersContext()` method stops paginating if it encounters any errors during pagination, and returns a nil error.

Expected Behavior:
The method would return the actual error encountered so that we know that the returned data is incomplete.

Happy to provide more info if necessary, but it seems to be a simple issue w/ the for loop in `GetUsersContext`:
```go
for p = api.GetUsersPaginated(options...); !p.Done(err); p, err = p.Next(ctx) {
	results = append(results, p.Users...)
}
```
`p.Next(ctx)` receives an error from `t.c.userRequest()` on line 328 and returns an error (that isn't the `errPaginationComplete`) without setting the `t.previousResp`. Since we're not done (`!p.Done(err)`), we continue paginating and hit `p.Next(ctx)` again. This time, line 314 evaluates to true (since we have a non-nil `t.previousResp` but an empty `t.previousResp.Cursor` b/c it was never set on line 334 when we returned early from the previous iteration. We then fire off an `errPaginationComplete` error, effectively ending pagination but not letting the user know that their data is incomplete.

A quick fix might be as simple as changing the for loop in `GetUsersContext` to:
```go
for p = api.GetUsersPaginated(options...); !p.Done(err); p, err = p.Next(ctx) {
	if err != nil {
		break
	}
	results = append(results, p.Users...)
}
```

**Comment by james-lawrence** [comment]
closing this in favor of armsnyder's issue.
