### ISSUE TITLE
Dynamically creating contexts and blocks results in bad JSON

### ISSUE THREAD

**Issue by rifelpet** [slack-go/slack#559]
On the current master branch I'm seeing messages get rejected due to incorrect JSON. We need to add a dynamic number of section blocks as well as text blocks in a context block:

```go
contextElements := make([]slack.MixedElement, 0)
contextElements = append(contextElements, slack.NewTextBlockObject(slack.MarkdownType, "*hello*", false, false))
contextElements = append(contextElements, slack.NewTextBlockObject(slack.MarkdownType, "*world*", false, false))
context := slack.NewContextBlock("context", contextElements...)

blocks = make([]slack.Block, 0)
blocks = append(blocks, slack.NewSectionBlock(slack.NewTextBlockObject(slack.MarkdownType, "foobar", false, false), nil, nil))
blocks = append(blocks, *context)

_, _, err := client.PostMessage(channel, slack.MsgOptionBlocks(blocks...), slack.MsgOptionText(message, false))
```

This is generating the following `blocks` json:
```json
[
  {
    "type": "section",
    "text": {
      "type": "mrkdwn",
      "text": "foobar"
    }
  },
  {
    "type": "context",
    "block_id": "context",
    "elements": {
      "Elements": [
        {
          "type": "mrkdwn",
          "text": "*hello*"
        },
        {
          "type": "mrkdwn",
          "text": "*world*"
        }
      ]
    }
  }
]
```

and logging this error:

`parseResponseBody {"ok":false,"error":"invalid_blocks","response_metadata":{"messages":["[ERROR] must provide an object [json-pointer:\/blocks\/1\/elements\/0]"]}}`

This is [not accepted](https://api.slack.com/tools/block-kit-builder?blocks=%5B%7B%22type%22%3A%22section%22%2C%22text%22%3A%7B%22type%22%3A%22mrkdwn%22%2C%22text%22%3A%22foobar%22%7D%7D%2C%7B%22type%22%3A%22context%22%2C%22block_id%22%3A%22context%22%2C%22elements%22%3A%7B%22Elements%22%3A%5B%7B%22type%22%3A%22mrkdwn%22%2C%22text%22%3A%22*hello*%22%7D%2C%7B%22type%22%3A%22mrkdwn%22%2C%22text%22%3A%22*world*%22%7D%5D%7D%7D%5D) because of the extra `Elements` field. Removing that and making `elements` the list [does succeed](https://api.slack.com/tools/block-kit-builder?blocks=%5B%7B%22type%22%3A%22section%22%2C%22text%22%3A%7B%22type%22%3A%22mrkdwn%22%2C%22text%22%3A%22foobar%22%7D%7D%2C%7B%22type%22%3A%22context%22%2C%22block_id%22%3A%22context%22%2C%22elements%22%3A%5B%7B%22type%22%3A%22mrkdwn%22%2C%22text%22%3A%22*hello*%22%7D%2C%7B%22type%22%3A%22mrkdwn%22%2C%22text%22%3A%22*world*%22%7D%5D%7D%5D).

**Comment by james-lawrence** [comment]
definitely a bug =) I personally won't have time to look into fixing these for the foreseeable future. please feel free to open a PR fixing the issue.

**Comment by armsnyder** [comment]
I spent some time on this, and I think it isn't a bug after all. There's a problem in the code used to reproduce the issue.

```go
blocks = append(blocks, *context)
```
should be
```go
blocks = append(blocks, context)
```

If you make that change, then the JSON is correct.

Further explanation: `Block` is an interface, and `NewContextBlock()` returns a pointer to a struct which implements the `Block` interface. So you should not be dereferencing the returned object.

Sharing my work in case anyone else wants to pick this back up...

Here's a test which which replicates the code in the original post. It fails:
```go
func TestPostMessageMsgOptionBlocks(t *testing.T) {
	http.DefaultServeMux = new(http.ServeMux)
	http.HandleFunc("/chat.postMessage", func(rw http.ResponseWriter, r *http.Request) {
		body, err := ioutil.ReadAll(r.Body)
		if err != nil {
			t.Errorf("unexpected error: %v", err)
			return
		}
		form, err := url.ParseQuery(string(body))
		if err != nil {
			t.Errorf("unexpected error: %v", err)
			return
		}
		actualBlocks := form.Get("blocks")
		expectedBlocks := `[{"type":"context","block_id":"context","elements":[{"type":"mrkdwn","text":"*hello*"}]}]`
		if expectedBlocks != actualBlocks {
			t.Errorf("expected: %s, got: %s", expectedBlocks, string(actualBlocks))
			return
		}
	})

	once.Do(startServer)
	api := New("testing-token", OptionAPIURL("http://"+serverAddr+"/"))

	var blocks []Block
	blocks = append(blocks, *NewContextBlock("context", NewTextBlockObject(MarkdownType, "*hello*", false, false)))

	_, _, _ = api.PostMessage("CXXX", MsgOptionBlocks(blocks...), MsgOptionText("text", false))
}
```
Failure:
```
expected: [{"type":"context","block_id":"context","elements":[{"type":"mrkdwn","text":"*hello*"}]}], got: [{"type":"context","block_id":"context","elements":{"Elements":[{"type":"mrkdwn","text":"*hello*"}]}}]
```
However, when I change `blocks = append(blocks, *NewContextBlock(...` to `blocks = append(blocks, NewContextBlock(...`, then the test passes. 😉

**Comment by james-lawrence** [comment]
could you convert that test code into an actual PR? ;)

**Comment by armsnyder** [comment]
@james-lawrence a PR with just the test? want to clarify I don't think there's a bug in the library, in case you're asking for a fix.

**Comment by mirth** [comment]
But why it even did compile in the first place?

**Comment by kanata2** [comment]
Close. This is not a bug, but it is an easy case to make a mistake.
It may be useful to have an implementation that can detect this.
