### ISSUE TITLE
Support setting "user" in SetUserCustomStatus

### ISSUE THREAD

**Issue by finfinack** [slack-go/slack#562]
Currently, SetUserCustomStatus does not support setting the "user" argument:
https://api.slack.com/methods/users.profile.set

This means the client can't be used to set other users' status.

Assuming backwards compatibility is important, instead of updating the existing function, a new one could be added:

```
func (api *Client) SetUserCustomStatusContextWithUser(ctx context.Context, user, statusText, statusEmoji string, statusExpiration int64) error {
...
	values := url.Values{
		"user":    {user},
		"token":   {api.token},
		"profile": {string(profile)},
	}
...
}
```

The existing functions could then be redirected:

```
func (api *Client) SetUserCustomStatus(statusText, statusEmoji string, statusExpiration int64) error {
	return api.SetUserCustomStatusContextWithUser(context.Background(), "", statusText, statusEmoji, statusExpiration)
}
```

Happy to send a PR if you think that's feasible. Otherwise I might fork it locally or keep patching it.

**Comment by finfinack** [comment]
FWIW, see my change in our fork: https://github.com/hb9tf/slack/commit/1acc80f97e162c5e7bf1b9ba740b00672772ea6a

**Comment by james-lawrence** [comment]
feel free to submit a PR, I'm happy to accept a PR for this. prefer the separate function with the current one being a convenience function. but don't particularly care which route you take. =)

**Comment by finfinack** [comment]
I sent a PR (https://github.com/nlopes/slack/pull/566) - hope that's roughly what you expect. Please let me know if you have an idea / guidance for how to test this meaningfully...

**Comment by james-lawrence** [comment]
merged thanks. =)
