### ISSUE TITLE
Auto-Paginated API Methods Can Include Duplicates If Errors Occur

### ISSUE THREAD

**Issue by armsnyder** [slack-go/slack#563]
Affects version 0.5.0

Similar to #557 

The method GetUsersContext internally performs pagination. However, if one of the paginated API calls to Slack results in an error (like exceeding a rate limit), then the error is ignored and the results from the previous page are appended _again_ to the results list.

The resulting behavior is that the full results list can contain many many duplicates, especially in the case of exceeding rate limits, since the rate limit backoff is not respected by the pagination code in GetUsersContext.

Suggestion: GetUsersContext should be modified so that the results list is only appended to when there is no error, and should additionally perform backoff when the error is a rate limit error.

Alternate suggestion: The UserPagination object should set its Users property to nil when there is an error.

**Comment by armsnyder** [comment]
My mitigation was to replace in my code
```go
users, err := api.GetUsers()
if err != nil {
	return err
}
```
with
```go
var p slack.UserPagination
var err error
var users []slack.User
ctx := context.Background()
for p = this.sc.GetUsersPaginated(); err == nil; {
	p, err = p.Next(ctx)
	if err == nil {
		users = append(users, p.Users...)
	} else if rateLimitedError, ok := err.(*slack.RateLimitedError); ok {
		time.Sleep(rateLimitedError.RetryAfter)
		err = nil
	}
}
if !p.Done(err) {
	return err
}
```
which gives me error handling, retry backoff, and fixes the duplication problem.

**Comment by james-lawrence** [comment]
oh no. feel free to open a PR with the changes you suggested.
