### ISSUE TITLE
Block Examples broken

### ISSUE THREAD

**Issue by WtfJoke** [slack-go/slack#564]
Hi there,

When executing the [blocks.go](https://github.com/nlopes/slack/blob/master/examples/blocks/blocks.go) from the examples I get an exception (using current master 2891986e2a3e7c60d4e660658e3bcd4d69934f4c).

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x705b57]

goroutine 1 [running]:
github.com/nlopes/slack.NewSectionBlock(0xc000074cc0, 0x0, 0x0, 0x0, 0x0, 0xc000097778, 0x1, 0x1, 0x0)
	c:/dev/git/goslack/block_section.go:38 +0x1a7
main.exampleOne()
	c:/dev/git/goslack/examples/blocks/blocks.go:50 +0x11b
main.main()
	c:/dev/git/goslack/examples/blocks/blocks.go:17 +0xb5
Process exiting with code: 0
```

Im rather new to go so I dont know whats the cause. 
Any chance to get that fixed?

`go version go1.12.7 windows/amd64`

Is it related to #476 ?

**Comment by james-lawrence** [comment]
@WtfJoke i mean its block code so its related. =)

looking at the code.... if you remove the final nil from the method call it should work.... feel free to try and if it does submit a PR fixing it.

**Comment by WtfJoke** [comment]
Hi James

Thanks for the hint/solution. It works, didnt thought it would be that easy. I will submit a PR soon and will close this issue
