### ISSUE TITLE
Get a channel ID given a channel name

### ISSUE THREAD

**Issue by Niraj-Fonseka** [slack-go/slack#572]
Currently there's no built in functionality to get a channel ID given a channel name. I'm happy to add the functionality into the package.

**Comment by nod** [comment]
At present I do something similar to this, and it feels a bit fragile honestly.

```golang
    channels, _ := api.GetChannels(false)
    for _, channel := range channels {
        if strings.ToLower(channel.Name) == strings.ToLower(my_channel) {
            return channel.ID
        }
    }
```

edit - minor formatting change to code sample

**Comment by GeorgeMac** [comment]
Just want to second this. Also the `channels.list` supports pagination through the use of a cursor token. However, the `GetChannels` call does not support this. Currently, if you have lots of channels you're stuck behind the page limit and cannot do this reverse lookup.

**Comment by ollieparsley** [comment]
The latest release 0.6.3 does include paginating channel lists.
