### ISSUE TITLE
Any example of interactive message buttons?

### ISSUE THREAD

**Issue by skasidej** [slack-go/slack#578]
Sorry, I'm pretty new to Golang and this library is quite hard for me to comprehend. Is there anyway that anyone can guide me for creating interactive message buttons for sending feedback? Thanks in advance.

**Comment by mzjp2** [comment]
I'm new to this as well, but here's what I figured out so far:

This sends a message with an interactive button.

```attachment := slack.Attachment{
		Pretext:    pretext,
		Fallback:   "We don't currently support your client",
		CallbackID: "challenge_accept_or_reject",
		Color:      "#3AA3E3",
		Actions: []slack.AttachmentAction{
			slack.AttachmentAction{
				Name:  "accept_challenge",
				Text:  "Accept",
				Type:  "button",
				Value: "accept_challenge",
			},
			slack.AttachmentAction{
				Name:  "reject_challenge",
				Text:  "Reject",
				Type:  "button",
				Value: "reject_challenge",
				Style: "danger",
			},
		},
	}

	message := slack.MsgOptionAttachments(attachment)
	s.API.PostMessage(channelID, slack.MsgOptionText("", false), message)
```

This is a route on my server that I tell Slack to send all action callbacks to `http.HandleFunc("/actions", HandleActions)` which I then handle using: 
```
func HandleActions(w http.ResponseWriter, r *http.Request) error {
	var payload slack.AttachmentActionCallback
	err := json.Unmarshal([]byte(r.FormValue("payload")), &payload)
	if err != nil {
		return fmt.Errorf("Could not parse action response JSON: %v", err)
	}
        <do stuff>
        return nil
```

In reality, I don't quite do this and implement a Handler interface instead, but this is good enough and works.

**Comment by james-lawrence** [comment]
feel free to PR example code if you desire it.
