### ISSUE TITLE
Message event fails to parse new WYSIWYG messages

### ISSUE THREAD

**Issue by guregu** [slack-go/slack#616]
I was having all messages from only certain users get mysteriously dropped and did some digging. I'm using RTM.
Recently Slack changed how messages work: https://api.slack.com/changelog/2019-09-what-they-see-is-what-you-get-and-more-and-less
I'm not sure if this is some kind of A/B test right now but the WYSIWYG interface is only happening in the web client for me at the moment.
This library doesn't support the `rich_text` block so message events fail to parse.
Here's an example of a failing parse:
> Data: (*slack.UnmarshallingErrorEvent)(0xc00031adc0)(RTM Error: Could not unmarshall event "message": {"client_msg_id":"f6e92b76-00e7-xxxx-xxxx-56dd5761fa89","suppress_notification":false,"type":"message","text":"its over","user":"U0DCQ8UQ5","team":"T0D14XXXX","blocks":[{"type":"rich_text","block_id":"GoMVS","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"its over"}]}]}],"user_team":"T0D14XXXX","source_team":"T0D14XXXX","channel":"C8JDY8A3Y","event_ts":"1572008617.046900","ts":"1572008617.046900"})

Supporting the new blocks would be great. But because this Slack API change is mostly backwards compatible, I think we should ignore new block types instead of erroring out completely (as in here: https://github.com/nlopes/slack/blob/e5749f13b5af3c139165ab4180a95bb06a60128b/block_conv.go#L63-L64). It's likely that Slack will continue to add block types, and getting most of a message is better than failing to parse it whenever Slack changes their API.

**Comment by gitclonedcush** [comment]
Slack has now released this change on the desktop client.
