### ISSUE TITLE
private interface httpclient used in publicly exposed function

### ISSUE THREAD

**Issue by lk16** [slack-go/slack#631]
Hello,

I suggest to make the `httpclient` interface publicly exposed.
This is justified in my opinion, because this type is used in publicly exposed functions such as `OptionHTTPClient`.

If this type becomes exposed, such as `HttpClient`, that allows for people to assert their custom struct implements that interface with something like this:

```var _ foohttpclient = (*slack.HttpClient)(nil)```

I could create a PR for this if necessary

**Comment by james-lawrence** [comment]
yeah no. won't happen and completely unnecessary. the pattern `var blah = (interface)(nil)` has always been silly and doesn't really assert anything useful that actual code wouldn't enforce naturally.
