### ISSUE TITLE
When can I expect a new release?

### ISSUE THREAD

**Issue by ghost** [slack-go/slack#640]
Hi, 

Thanks for the awesome library, it's quite nice. 

We are using 0.6.0, but we are waiting for https://github.com/nlopes/slack/pull/618 to be released. When can we expect a new release?

Is there anything missing?

**Comment by parsley42** [comment]
v0.6.2 has been tagged in the new `slack-go/slack` repo. See READMEs in `nlopes/slack`, `slack-go/slack`.
