### ISSUE TITLE
UnmarshallingErrorEvent happens when user use slack 4.2.0 to communicate with slack application

### ISSUE THREAD

**Issue by kendung** [slack-go/slack#643]
github.com/nlopes/slack: v0.6.0
desktop slack app version: 4.2.0
Use RTM api to exchange message with slack

Recently, I upgraded my desktop slack app to 4.2.0. When I talked to my slack app,  a lot of UnmarshallingErrorEvent delivered to the incoming events channel.  It seems slack app introduced a new rich_text which is not recognized by nlopes.

https://github.com/nlopes/slack/blob/d06c2a2b3249b44a9c5dee8485f5a87497beb9ea/websocket_managed_conn.go#L480

Sample message payload:
{
  "client_msg_id": "43347b48-7876-4ae1-a193-3684815551ad",
  "suppress_notification": false,
  "type": "message",
  "text": "<@xxxx> help",
  "user": "xxx",
  "team": "xxx",
  "blocks": [
    {
      "type": "rich_text",
      "block_id": "9qE",
      "elements": [
        {
          "type": "rich_text_section",
          "elements": [
            {
              "type": "user",
              "user_id": "xxx"
            },
            {
              "type": "text",
              "text": " help"
            }
          ]
        }
      ]
    }
  ],
  "user_team": "xxx",
  "source_team": "xxx",
  "channel": "xxx",
  "event_ts": "1576131993.024500",
  "ts": "1576131993.024500"
}

**Comment by kendung** [comment]
My current workaround is to catch UnmarshallingErrorEvent event, and get message payload from error message. Then handle it according to my own logic.

**Comment by ldkingvivi** [comment]
any update on this ? we start to see the same issue

**Comment by ldkingvivi** [comment]
seems same issue as https://github.com/nlopes/slack/issues/630

**Comment by kendung** [comment]
Duplicate with #630 . close it. Thank you guys.

**Comment by kendung** [comment]
It seems the fix is already in master branch. I just tried the master branch, it works for me.
