### ISSUE TITLE
How to create Notification Text using MsgOptionBlocks

### ISSUE THREAD

**Issue by twskj** [slack-go/slack#644]
I ran into an issue that my notification shows "This content can't be displayed" which exactly like this post on stackoverflow described:
https://stackoverflow.com/questions/56317962/message-notifications-produce-this-content-cant-be-displayed/56327506

Can anyone advise how can I set `text` field at outer level when using `MsgOptionBlocks`?
The code I'm working on is below

```go
headerText := slack.NewTextBlockObject("mrkdwn", "This is the content", false, false)
myBtnText := slack.NewTextBlockObject("plain_text", "OK!", false, false)
myBtn := slack.NewButtonBlockElement("ok", "ok", myBtnText)
headerSection := slack.NewSectionBlock(headerText, nil, slack.NewAccessory(myBtn))
msg := slack.MsgOptionBlocks(headerSection)

client.PostMessage(CID, msg)
```
How should I modify this code so that I have `text` at the outer level. Thanks!

**Comment by samolds** [comment]
You can use `MsgOptionCompose` to combine your existing `msg` variable and a `MsgOptionText`. You can see that `applyMsgOptions` in chat.go will apply all of the provided options to a query param value before posting the message. This will have the effect of setting the top level "text" field, along with your "blocks" field.

Something like:

```go
text := "This is the content"
headerText := slack.NewTextBlockObject("mrkdwn", text, false, false)
myBtnText := slack.NewTextBlockObject("plain_text", "OK!", false, false)
myBtn := slack.NewButtonBlockElement("ok", "ok", myBtnText)
headerSection := slack.NewSectionBlock(headerText, nil, slack.NewAccessory(myBtn))

fallbackOpt := slack.MsgOptionText(text, false)
blockOpt := slack.MsgOptionBlocks(headerSection)
msg := slack.MsgOptionCompose(fallbackOpt, blockOpt)

client.PostMessage(CID, msg)
```

should do the trick.

**Comment by twskj** [comment]
Thanks. That does it!
