### ISSUE TITLE
json: cannot unmarshal object into Go struct field Attachment.messages.attachments.blocks of type slack.Block

### ISSUE THREAD

**Issue by zfLQ2qx2** [slack-go/slack#645]
I'm getting the error "json: cannot unmarshal object into Go struct field Attachment.messages.attachments.blocks of type slack.Block" while doing api.GetConversationHistory.

It appears there is a potential fix here - https://github.com/nlopes/slack/pull/638 but seems to be stalled over last 30 days.

I can confirm that the actual one-liner fix from that PR does work, the majority of the PR is a unit test to verify correct behavior.

**Comment by gvirtanen** [comment]
@nlopes Any update on this, please? We also really need this PR, and can verify that the one line fix solves the problem of unmarshalling attachments in our case too.

**Comment by bitsofinfo** [comment]
same here, need the PR in #638

**Comment by rusq** [comment]
I think this can be closed, #638 is merged

**Comment by parsley42** [comment]
Closed by #638
