### ISSUE TITLE
When to expect a new tag?

### ISSUE THREAD

**Issue by Steel551454** [slack-go/slack#657]
In my project, I refer to the Blocks type in the Attachments section. When to expect the next tag?

**Comment by parsley42** [comment]
See the tail of #632; I've been working with Norberto to establish a new fork that moves a little faster. I'll leave this open in case @james-lawrence decides to continue maintaining this, which may be slower moving / more stable? I see James is still making commits to other repositories, so I suspect he's too busy with other things at the moment to work on this. Hopefully I'll hear from James as I heard from Norberto, and we'll have a better handle on the direction the slack library will take.

**Comment by amossc** [comment]
Same question was asked in https://github.com/slack-go/slack/issues/640 back in December. It might be beneficial to keep only one issue open to track.

**Comment by parsley42** [comment]
See #640
