### ISSUE TITLE
OAuthV2Response does not contain Incoming Webhook information

### ISSUE THREAD

**Issue by gjgd** [slack-go/slack#684]
https://github.com/slack-go/slack/blob/5b8bbb1b1ad5bfa1531ee0bd7a0cfbfa801de7fe/oauth.go#L35-L46

Should contain information about incoming webhooks.

For reference, this is the workaround we made because we couldn't use `OAuthV2Response`:
https://github.com/gjgd/dont-slack-evil/blob/8320d31f9ba7ddf193cd7994766cda1fc05d592c/db/team.go#L30
https://github.com/gjgd/dont-slack-evil/blob/0640619951a3eb8386c1bf0f5bd93082b45b2fbe/lambda/redirectUrl/redirectUrl.go#L21

**Comment by ollieparsley** [comment]
@gjgd I can't find any documentation for this, do you have any links or more information? Thanks!

**Comment by gjgd** [comment]
I agree, it's not well documented in the v2 Slack doc, but it is here: https://api.slack.com/messaging/webhooks#oauth_response

**Comment by ollieparsley** [comment]
Awesome! Thank you
