### ISSUE TITLE
Secret verifier does not include request body

### ISSUE THREAD

**Issue by ryanskidmore** [slack-go/slack#686]
Hey,

I noticed that the secret verifier [never uses](https://github.com/slack-go/slack/blob/master/security.go#L44) the body of the request in the HMAC generation - why is this?

This caused a lot of frustration today as I was attempting to mock the HMAC signature in the request as per the [docs](https://api.slack.com/docs/verifying-requests-from-slack) and had it repeatedly fail.

**Comment by frozenbonito** [comment]
The body of the request must be passed to `SecretsVerifier` using the [`Write()`](https://pkg.go.dev/github.com/slack-go/slack?tab=doc#SecretsVerifier.Write) method.
The following example will help.

https://github.com/slack-go/slack/blob/0cf5ed7b08d778d45820a260f42f56058d578b41/examples/slash/slash.go#L24-L40

**Comment by ryanskidmore** [comment]
@frozenbonito This was exactly what I was doing. If you check on the link in my original comment, the signature produced by the library is `v0:timestamp:` but it's supposed to be `v0:timestamp:body`.

Unless I'm missing something, the body is never appended to the signature prior to hashing?

**Comment by frozenbonito** [comment]
Doesn't `Write()` method append the body to hash?

https://github.com/slack-go/slack/blob/9c98723e5a0030d32bfcc55f62cb4db619aac1ed/security.go#L78-L80

In the example above, the important parts are:

https://github.com/slack-go/slack/blob/0cf5ed7b08d778d45820a260f42f56058d578b41/examples/slash/slash.go#L30-L31

Rewriting is as follows:

```go
body, _ := ioutil.ReadAll(r.Body)
verifier.Write(body)
```
