### ISSUE TITLE
Support for `source_team` and `user_team` in `message` and `app_mention`.

### ISSUE THREAD

**Issue by sfzylad** [slack-go/slack#695]
According to https://api.slack.com/enterprise/grid/developing message event can contain `source_team` and `user_team` fields. They seem to exist if the message comes from a channel that is shared between workspaces. From what I've seen (although the docs doesn't mention it: https://api.slack.com/events/app_mention), it also appears in `app_mention` events.

**Comment by ollieparsley** [comment]
Thanks @sfzylad! The PR is merged and this issue can be closed.
