### ISSUE TITLE
Unhandled response

### ISSUE THREAD

**Issue by vcastellm** [slack-go/slack#7]
I'm working with this lib in a project using it for the websockets RTM API implementation, and when receiving an error response from the api this line https://github.com/nlopes/slack/blob/master/websocket.go#L184 Is making the app crash.

The error responses from slack are also going here and I think it should handle the error gracefully.

For instance when sending a message with empty text, slacks answer is: `{"ok":false,"reply_to":1,"error":{"code":2,"msg":"message text is missing"}}`

Making the Unmarshal fail and exiting the app.

I think that the unmarshal error could be relaxed and at least reach https://github.com/nlopes/slack/blob/master/websocket.go#L194-L195

Said that, agree that error should not end up in that bucket.

**Comment by nlopes** [comment]
@victorcoder Thanks for the report, I will be taking a look shortly

**Comment by nlopes** [comment]
@victorcoder  This commit (https://github.com/nlopes/slack/commit/b8c4312a0b54fc89302947fabe02e83c766bda50) should fix the issue. I also made sure errors are being passed down to you. Example in https://github.com/nlopes/slack/blob/master/examples/websocket/websocket.go#L46

**Comment by vcastellm** [comment]
@nlopes, tested it and it fixes the error! Thanks

Just to let you know, I'm using https://github.com/danryan/hal and I used your API implementation to power the new RTM adaptor https://github.com/danryan/hal/pull/42

It's working like a charm

**Comment by nlopes** [comment]
Awesome!
