### ISSUE TITLE
Example cited in the docs creates Invalid Verification Token error

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [slack-go/slack#705]
I am using the example for the EventsAPI as cited in the [documentation](https://github.com/slack-go/slack/blob/master/examples/eventsapi/events.go).

The only thing I changed is to print the error under [L23](https://github.com/slack-go/slack/blob/master/examples/eventsapi/events.go#L23) to check the relevant error.

I am also printing the event.

```go
fmt.Printf("%+v\n", eventsAPIEvent)
```
I have hard-coded my **Bot User OAuth Access Token** in the place of the `"TOKEN"` string used in the example.

I am also tunneling my localhost using `ngrok` so that it is reachable from slack.

When I try to verify the url, the following is printed:

```
[INFO] Server listening
Invalid verification token
{Token: TeamID: Type: APIAppID: Data:<nil> InnerEvent:{Type: Data:<nil>}
```

**Comment by DeepanshuGautam** [comment]
There are two types of Token being used in the example:
- Bot User OAuth Access Token: For creating app
- Verification Token: For url_verification event.

Please, use these two token of your slack app.

**Comment by pantelis-karamolegkos** [comment]
Thank you!
I was kind of misled by the usage of the same placeholder  `"TOKEN"`
Closing this.
