### ISSUE TITLE
json data payload.Submisson not being Unmarshaled 

### ISSUE THREAD

**Issue by Jonatan-McE** [slack-go/slack#719]
Hi. 

I'm having issues Unmarshalaling event api json data with the slack.InteractionCallback struct. The playload.DialogSubmissonCallback.Submission field is not being poplulated even though it should from what i can see. I hope i'm not missing anything but this is what i have. 

Incomming json data:

```
{
   "type": "dialog_submission",
   "token": "xxxxxxxxxxxxxxxxx",
   "action_ts": "1588715017.701792",
   "team": {
      "id": "xxxxxxxxxxxxxxxxx",
      "domain": "yyyyyyyyyyyyyyyy"
    },
    "user": {
      "id": "xxxxxxxxxxxxxxxxx",
      "name": "yyyyyyyyyyyyyyyy"
   },
   "channel": {
      "id": "xxxxxxxxxxxxxxxxx",
      "name": "yyyyyyyyyyyyyyyy"
   },
   "submission": {
      "msg": "Testing..."
   },
   "callback_id": "replySubmit",
   "response_url": "https:\/\/hooks.slack.com\/app\/xxxxxxxxxxxxxxxxx\/yyyyyyyyyyyyyyyy\/xxxxxxxxxxxxxxxxx",
   "state": ""
}
```

The resulting Unmarshaled payload looks like this and is missing the submission data under the playload.DialogSubmissonCallback.Submission field. 

![image](https://user-images.githubusercontent.com/17752409/81187976-0b520a80-8fb5-11ea-88a4-15a084f88c14.png)

I have tested with adding State data and that works fine (playload.DialogSubmissonCallback.State)

I'm very helpfull for any help. Thanks alot!

**Comment by tkhandel** [comment]
@Jonatan-McE Seems like the `Submission` field is not empty. In the screenshot that you've shown, it says it has a `length: 1` which is correct. Maybe your UI is not showing the contents of the map.

I did try to unmarshal the JSON which you posted and it unmarshalled without a problem.

**Comment by Jonatan-McE** [comment]
You are completely right. 

I missed the fact that VSCode was show me that there where map values, but just not showing me the actual value. Testing it knowing that now, I can confirm that it is working as indented.

Sorry for wasting your time. 
Thanks again!
