### ISSUE TITLE
Question: Why slack.SlashCommandParse before verifier.Ensure() ?

### ISSUE THREAD

**Issue by sspaink** [slack-go/slack#720]
Hello! I was hoping I could get some help understanding the [slash example](https://github.com/slack-go/slack/blob/master/examples/slash/slash.go) why line 31 `s, err := slack.SlashCommandParse(r)` needs to happen before line 37 `if err = verifier.Ensure();`

I assumed we want to ensure the signatures are correct before parsing the slack command, but it fails if I try to swap the steps. I looked at the function implementation and don't see any obvious dependencies between them.

The [Dialog example](https://github.com/slack-go/slack/blob/master/examples/dialog/dialog.go) follows the logic I was expecting but I'm having trouble seeing the difference. Thank you for any help!

**Comment by k-saka** [comment]
@BattleBas The slack signature is created by combining version, date and body.
Don't have to parse, but you do have to write verifier.

https://api.slack.com/authentication/verifying-requests-from-slack#a_recipe_for_security

**Comment by sspaink** [comment]
@k-saka thank you for the explanation and document link, this answers my question.
