### ISSUE TITLE
Examples/help for retrieving input from a "multi_users_select" type block?

### ISSUE THREAD

**Issue by jacobburdeckiCA** [slack-go/slack#721]
Hi, I'm having an issue getting submission data from `ViewState` for an input block of type `multi_users_select` (`MultiOptTypeUser`).

My def for this input block looks like:
```
inputPlaceholderText = slack.NewTextBlockObject(slack.PlainTextType, " ", false, false)
inputLabel = slack.NewTextBlockObject(slack.PlainTextType, "Attendees:", false, false)
multiSelect := slack.NewOptionsMultiSelectBlockElement(slack.MultiOptTypeUser, inputPlaceholderText, g.attendeesAID)
inputBlock = slack.NewInputBlock(g.attendeesBID, inputLabel, multiSelect)
m.Blocks.BlockSet = append(m.Blocks.BlockSet, inputBlock)
```

Then, after filling out and submitting the modal in Slack, and back in my app on `InteractionTypeViewSubmission`, I grab the `ViewState` and key into the `Values` map fine using the right blockID and actionID for `multiSelect`. 

However, even though this input data exists in `ViewState.Values`... there's nothing associated with it. The `Value` for this input block is `""`. No errors or warnings are logged.
__________________________
Any ideas here? Seems like something off with my modal/block defs, but I'm not sure what. 
Help is appreciated, and thanks in advance.

**Comment by Donngi** [comment]
Hi, I was worried about the same thing and notice that `struct BlockAction (in block.go)` doesn't contain  `SelectedUsers` field. 

I already added it and made a pull request (https://github.com/slack-go/slack/pull/717). Currently, I'm waiting for approval.

**Comment by jacobburdeckiCA** [comment]
Nice - appreciate the heads-up, and the fix, @nicoJN!

**Comment by karl-johan-grahn** [comment]
@jacobburdeckiCA does it work now after https://github.com/slack-go/slack/pull/717 got merged?

**Comment by jacobburdeckiCA** [comment]
@karl-johan-grahn - hey, yep! 
`SelectedUsers` are coming through in the `ViewState.Values` map 👍
