### ISSUE TITLE
webhook support

### ISSUE THREAD

**Issue by tj** [slack-go/slack#74]
May have missed it but I didn't see a method for posting to a webhook url. Ended up just generating a token to use but support and/or docs for webhook integration would be great!

**Comment by milani** [comment]
@tj Did you find a solution for handling incoming requests?

**Comment by mingrammer** [comment]
Is it in progress?

**Comment by jBugman** [comment]
Receiving webhooks requires setting up a public web server with a valid SSL certificate. I think it should be left to be implemented by a final developer, not this library.
Even providing generic `HandlerFunc` would not really make sense as it is pretty application-specific.

**Comment by ardakuyumcu** [comment]
I think the original intent was to post messages via an incoming webhook, not regarding support for receiving webhooks via a server.
