### ISSUE TITLE
Deprecating early methods in favor of the Conversations API

### ISSUE THREAD

**Issue by tmc** [slack-go/slack#748]
Since we're now past Slack's July 10 deadline, many methods are now deprecated e.g. GetChannels().

A new revision of the published API that reflects these deprecations should be planned.

**Comment by kanata2** [comment]
It seems that the retirement has been postponed, but we should think about this breaking changes while we have time.

> February 24th, 2021 these methods will retire and cease functioning.

ref: https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api

**Comment by kanata2** [comment]
Ah, I overlooked the following warning.

> We'll stop allowing newly created Slack apps to use these deprecated APIs beginning June 10th, 2020.

We must add conversations APIs as soon as possible.

**Comment by andrewotoole** [comment]
Do you have an ETA on this, specifically with conversations/channels?

**Comment by andrewotoole** [comment]
Actually, fully checked out the most recent release and it seems that conversations work correctly. Looks like now channels should be removed or converted to conversations. Perhaps close this issue?

**Comment by tmc** [comment]
I think it should still be an API revision as a lot of the api can be cleaned up.

**Comment by kanata2** [comment]
`conversations.mark` is added in https://github.com/slack-go/slack/pull/761
The conversations API is fully implemented if this PR is merged.

I think we should remove deprecated methods after a few moments of warning with it.
What do you think? @slack-go/slack-maintainers

**Comment by kanata2** [comment]
Removed deprecated methods in v0.9.0.
