### ISSUE TITLE
Missing "bot_id" field from auth.test result?

### ISSUE THREAD

**Issue by amossc** [slack-go/slack#777]
I'm writing a bot which needs to find its own `bot_id`. Slack support referred me to `auth.test` which indeed returns this field when executed using an `xoxb-...` auth token. But `AuthTestResponse` doesn't have this field.

Here is the tester on Slack's web site: https://api.slack.com/methods/auth.test/test

Here is an example call (token redacted):

`https://slack.com/api/auth.test?token=xoxb-....&pretty=1`

And here is a sample output (redacted):

```
{
    "ok": true,
    "url": "https:\/\/domain.slack.com\/",
    "team": "Team NAme",
    "user": "name_of_bot_user",
    "team_id": "TXXXXXXXX",
    "user_id": "UYYYYYYYY",
    "bot_id": "BZZZZZZZZ"
}
```

**Comment by GLOFonseca** [comment]
@kanata2 I think we can close this issue
