### ISSUE TITLE
Leaving the `groupConversation` type unexported makes api testing complicated

### ISSUE THREAD

**Issue by binary132** [slack-go/slack#78]
Compare:
- https://api.slack.com/types/channel
- https://godoc.org/github.com/nlopes/slack#Channel

Is there a way I can use your API to find Slack channel membership?  How about its Name?

**Comment by binary132** [comment]
Bare minimum its ID??

**Comment by binary132** [comment]
For anyone else confused: it looks like the channel name and ID can be accessed through the unexported struct member.

> https://github.com/nlopes/slack/blob/master/channels.go#L19-L25

``` go
// Channel contains information about the channel
type Channel struct {
    groupConversation
    IsChannel bool `json:"is_channel"`
    IsGeneral bool `json:"is_general"`
    IsMember  bool `json:"is_member"`
}
```

> https://github.com/nlopes/slack/blob/5e8064e706a2cb3d2581c1298d9428db2c0984fa/conversation.go#L14-L24

``` go
// GroupConversation is the foundation for Group and Channel
type groupConversation struct {
    conversation
    Name       string   `json:"name"`
    Creator    string   `json:"creator"`
    IsArchived bool     `json:"is_archived"`
    Members    []string `json:"members"`
    NumMembers int      `json:"num_members,omitempty"`
    Topic      Topic    `json:"topic"`
    Purpose    Purpose  `json:"purpose"`
}
```

**Comment by dvdplm** [comment]
What kind of change would you like to see here? Sorry if dumb question, but I don't understand what the issue is. Thanks!

**Comment by depado** [comment]
It's not an unexported struct member, it's an embedded struct. You can do that :

``` go
c, err := api.JoinChannel("#test")
if err != nil {
    log.Fatal(err)
}
fmt.Println(c.ID, c.Members, c.Name, c.Topic)
```

**Comment by binary132** [comment]
@dvdplm, I got confused by the documentation, that's all.  My second comment is to clarify for anyone who had a similar problem. :)

@Depado, just because it is embedded doesn't make the embedded type exported.  For testing, for example, you cannot create a mock client that will return a `*slack.Channel`.  But you're right, I didn't expect that a type composed with an unexported struct type would have exported members from that struct!

**Comment by binary132** [comment]
I'll update the Issue title and close this, but leaving it unexported does make it a pain to mock up a Slack client...

**Comment by ghostsquad** [comment]
Sorry for the ignorance (if that's the case), as I don't understand why this issue was closed. The title is accurate, and the embedded struct is still unexported, making impossible to mock this struct accurately.

```Go
testSlackChannel := &stdslack.Channel{
	Name: expectedChannelName,
}
```

```
cannot use promoted field groupConversation.Name in struct literal of type ".../vendor/github.com/nlopes/slack".Channel
```

I can start a new issue.
