### ISSUE TITLE
Revert changes to json tags in Attachment's Text field. 

### ISSUE THREAD

**Issue by prgres** [slack-go/slack#784]
https://github.com/slack-go/slack/commit/13b47a4af036079f15990aa608caaa0c8255ea74

This should stay `omitempty`, because when using `client.PostMessage` or `client.UpdateMessage` with `Attachment` which contains `blocks` field, api returns error "invalid_attachments". I have just wasted 5 hours debugging what is wrong with my code, just because attachment payload cannot contains both `blocks` and `text`. 

```
{
        //...
 	Text      string `json:"text,omitempty"`
        //...
}
```

**Comment by prgres** [comment]
I have managed to create pr: #788

**Comment by mzduke** [comment]
+1 regarding this issue. A bit improved PR: #789

**Comment by kanata2** [comment]
LGTM.

@ollieparsley Please see this PR.

**Comment by kanata2** [comment]
I tried to reproduce this situation.
Here is the minimal code.

```

func main() {
	c := slack.New(os.Getenv("SLACK_ACCESS_TOKEN"))
	_, _, err := c.PostMessage(os.Getenv("SLACK_CHANNEL_ID"),
		slack.MsgOptionText("Text", false),
		slack.MsgOptionAttachments(
			slack.Attachment{
				Blocks: slack.Blocks{
					BlockSet: []slack.Block{
						slack.SectionBlock{
							Type: "section",
							Text: &slack.TextBlockObject{
								Type: "mrkdwn",
								Text: "Block Text",
							},
						},
					},
				},
			},
		),
	)
	if err != nil {
		panic(err)
	}
}
```

BTW, Slack recommend not to use this style called "secondary attachments" for now.
If you are faced this issue, you might want to work on getting rid of secondary attachments rather than waiting for merging #788 .

https://api.slack.com/messaging/composing/layouts#attachments
