### ISSUE TITLE
Support Message Buttons

### ISSUE THREAD

**Issue by abourget** [slack-go/slack#79]
Announced yesterday and described here:

https://api.slack.com/docs/message-buttons

I'll be working on that if you don't mind.. if you want to pitch in, notify me.. I really want that for https://github.com/abourget/slick  :)

**Comment by nlopes** [comment]
That's great! Feel free to put in a PR and I'll go through it.

**Comment by dougnukem** [comment]
I think this is closed via https://github.com/nlopes/slack/pull/81
