### ISSUE TITLE
Method in examples/ims is deprecated.

### ISSUE THREAD

**Issue by bukowa** [slack-go/slack#795]
https://github.com/slack-go/slack/blob/master/examples/ims/ims.go

**Comment by kanata2** [comment]
You can still use it in existing apps.

> - The final date for existing apps is now February 24th, 2021.
> - We'll stop allowing newly created Slack apps to use these deprecated APIs beginning June 10th, 2020.

See also: https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api

**Comment by bukowa** [comment]
Yes but example its deprecated maybe we could add this message in all deprecated examples?

**Comment by kanata2** [comment]
Good idea. Feel free to send PRs.
