### ISSUE TITLE
Cannot retrieve private channels using GetConversations

### ISSUE THREAD

**Issue by kmai** [slack-go/slack#797]
Taking the example from #285, I tried specifying both public _and_ private channel types:

```go

params := &slack.GetConversationsParameters{
		Limit: 200,
		Types: []string{"public_channel", "private_channel"},
	}
```

But I can't retrieve the channels using `GetConversations` (I only see the public ones). I tried debugging `GetConversationsContext` and I see that `Types` is being serialized properly and the values are the ones listed in https://api.slack.com/methods/conversations.list#arg_types. 

I also checked and my bot does have `groups:read` and `channels:read` which should be enough to get a list of channels.

Any hints?

**Comment by kanata2** [comment]
Maybe isn't your Bot participating in a private channel?
This API does not allow you to get a private channel that you are not participating in for security reason.

**Comment by kanata2** [comment]
I'll close this issue. Please feel free to reopen if you could not resolve.

**Comment by kmai** [comment]
You're absolutely right. The bot has to be in the channel, besides being added as an integration

**Comment by wellle** [comment]
FWIW, I'm currently having a similar problem, even with the bot being in the private channel. I suspect that Slack has changed their scopes and now ones need to be granted to the bot for this to work. Specifically I suspect it might need `groups:read`, see https://api.slack.com/scopes.

I might confirm here if I get it to work again. (It used to work in the past, stopped working around August 2020 for me)
