### ISSUE TITLE
How to direct message a user with conversation api

### ISSUE THREAD

**Issue by freshteapot** [slack-go/slack#799]
Today when you use "api.OpenIMChannel" it fails with deprecated warning.

> We'll stop allowing newly created Slack apps to use these deprecated APIs beginning June 10th, 2020.

My app was created today 12th September.

When I use a public channel it works.

```
channel, _ := api.GetConversationInfo("PUBLIC_CHANNEL", true)
msg := fmt.Sprintf("YO")
	api.PostMessage(channelID,
		slack.MsgOptionText(msg, false),
		slack.MsgOptionAttachments())
```

Not sure where to start in terms of a PR to help.

When I use "Tester" (https://api.slack.com/methods/conversations.open/test)

It seems to make sense with the channel I want to use, however when it sends the message it goes to the bot. Not the to the user.

# Reference
- https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api
- https://api.slack.com/methods#conversations
- https://api.slack.com/methods/conversations.open

**Comment by freshteapot** [comment]
For anyone who gets here and is wondering what the hell. The key detail is...

Use **OAuth Access Token**.
When I try using "Bot User OAuth Access Token" it doesnt seem to work.

**Comment by cjdenio** [comment]
Assuming you're using a new granular token, you can pass a user's ID into the `channel` field of `chat.postMessage`. Reference: https://api.slack.com/methods/chat.postMessage#begin-a-conversation-in-a-users-app-home

**Comment by kanata2** [comment]
I'll close this issue but feel free to reopen if you have any questions.
