### ISSUE TITLE
How to send a block Message type? 

### ISSUE THREAD

**Issue by echobops** [slack-go/slack#802]
I'm trying to create message blocks, but the examples only go as far as _NewBlockMessage(...)_. How do we send that newly constructed Message object? _PostMessage_ only accepts MsgOptions...   I've been digging through the code trying to find out how to use Msg or Message types, but can't seem to make heads or tails of it. :(

**Comment by cjdenio** [comment]
Did you mean to do this?

```go
client.PostMessage("channel", slack.MsgOptionBlocks(
  slack.NewSectionBlock(slack.NewTextBlockObject("mrkdwn", "text", false, false), nil, nil),
))
```

**Comment by kanata2** [comment]
I'll close this issue but feel free to reopen if you have any questions.

**Comment by zz** [comment]
If can't send BlockMessage. why have NewBlockMessage? WTF

**Comment by zz** [comment]
@echobops ``` api.PostMessage(slackChannel, slack.MsgOptionBlocks(message.Msg.Blocks.BlockSet...))```

**Comment by rosehgal** [comment]
This needs to be highlighted in the documentation. I had hard time finding this too. Thanks @zz  for the message above.

**Comment by srgpsk** [comment]
It doesn't work
```
b := slack.NewTextBlockObject(slack.PlainTextType, "test", false, false)
option := slack.MsgOptionBlocks(b)
_, _, err := slackClient.PostMessage(ch, option)
```

> 2023/01/17 12:14:52 invalid_blocks

Usage `NewBlockMessage` seems redundant at this point.

**Comment by lslavkov** [comment]
Is there an example using `slack.Attachment` struct to add `Blocks` but I am out of luck in this part.

Any suggestions?
