### ISSUE TITLE
method_deprecated

### ISSUE THREAD

**Issue by icobani** [slack-go/slack#807]
```
package main

import (
	"fmt"
	"github.com/slack-go/slack"
)

func main() {
	api := slack.New("<TOKEN>", slack.OptionDebug(true))
	// If you set debugging, it will log all requests to the console
	// Useful when encountering issues
	// slack.New("YOUR_TOKEN_HERE", slack.OptionDebug(true))
	groups, err := api.GetGroups(false)
	if err != nil {
		fmt.Printf("%s\n", err)
		return
	}
	for _, group := range groups {
		fmt.Printf("ID: %s, Name: %s\n", group.ID, group.Name)
	}

}
```

GOROOT=C:\Go #gosetup
GOPATH=C:\Users\Lenovo\go #gosetup
C:\Go\bin\go.exe build -o C:\Users\Lenovo\AppData\Local\Temp\___2go_build_github_com_icobani_icibot_slack.exe github.com/icobani/icibot.slack #gosetup
C:\Users\Lenovo\AppData\Local\Temp\___2go_build_github_com_icobani_icibot_slack.exe #gosetup
**method_deprecated**

Process finished with exit code 0

I get a message called **method_deprecated**. Why could it be.

**Comment by mike-webster** [comment]
I was just playing around with this and got the same error.  Looks like almost the same code snippet too:

```go
package main

import (
	"fmt"

	"github.com/slack-go/slack"
)

var (
	tok = "xoxb-my-token"
)

func main() {
	api := slack.New(tok, slack.OptionDebug(true))
	groups, err := api.GetGroups(false)
	if err != nil {
		panic(err)
	}

	fmt.Println(len(groups))
}
```

**Comment by mike-webster** [comment]
The underlying functionality seems to have been deprecated by slack:

https://api.slack.com/methods/groups.list

![image](https://user-images.githubusercontent.com/25595930/94352785-03136e00-002f-11eb-8a0f-dc23fe4b3396.png)

**Comment by mike-webster** [comment]
Probably replaced by this:
https://api.slack.com/methods/conversations.list

**Comment by kanata2** [comment]
Thank you.
Please see more details: https://github.com/slack-go/slack/issues/748
