### ISSUE TITLE
Empty BlockIDs in input blocks now lead to the error "Block ID needs to be unique"

### ISSUE THREAD

**Issue by jmiller101** [slack-go/slack#823]
**What happened**
Created a modal with 2 input blocks with blank Block IDs. I got the following error from the Slack API: `Block ID needs to be unique`.

**Expected outcome**
Slack prompts the user with a modal.

I know there was a Slack API update so I checked the docs and it appears to still accept blank Block IDs:
https://api.slack.com/reference/block-kit/blocks#input

I've worked around this by just putting random characters in the Block ID.

**Comment by kanata2** [comment]
> A string acting as a unique identifier for a block. If not specified, one will be generated.
> `block_id` should be unique for each message and each iteration of a message.

According to the documentation, it seems not to be able to specify empty string in multiple block ids.

**Comment by jmiller101** [comment]
After reading it again I think you're right. Weird that it only recently stopped working. Looks like I've become the subject of one of my favorite comics... https://xkcd.com/1172/
