### ISSUE TITLE
Support Options Load payload 

### ISSUE THREAD

**Issue by hagaishapira** [slack-go/slack#834]
Select menu elements from external data source send options load payloads and expect options to be returned.
I have failed to find any support for handling these options request payload. Am I missing something? Could support for handling these payload be added?

**Comment by kanata2** [comment]
> Your app should return an HTTP 200 OK response, along with an application/json post body with an object containing either an options array, or an option_groups array. Here's an example response:
_ref: https://api.slack.com/reference/block-kit/block-elements#external_select_

Just response like a normal web application, so we don't have any support for this.

**Comment by kanata2** [comment]
I'll close it once, but you can reopen it if you have additional questions :)
