### ISSUE TITLE
`Minimal EventsAPI usage` example using deprecated verification token

### ISSUE THREAD

**Issue by vvakame** [slack-go/slack#837]
https://github.com/slack-go/slack#minimal-eventsapi-usage
https://github.com/slack-go/slack/blob/686c209f9525a78313cfe54cbc07cd86bd677384/examples/eventsapi/events.go#L21
new way #353 #399

**Comment by kanata2** [comment]
Sorry for slow response and thank you for your reporting. 
Fixed #863
