### ISSUE TITLE
Error from "Ensure" should not disclose expected signature

### ISSUE THREAD

**Issue by tyrannosaurus-becks** [slack-go/slack#849]
Hello! First of all, a big thank-you to the maintainers and contributors for this library.

I'm surfacing this issue because I wonder if the error message located [here](https://github.com/slack-go/slack/blob/master/security.go#L90) is too descriptive. Specifically, it reads:

```
return fmt.Errorf("Expected signing signature: %s, but computed: %s", hex.EncodeToString(v.signature), hex.EncodeToString(computed))
```

My concern is that since Go errors tend to get blindly passed upwards, this could be eventually returned directly to a caller making a request. Because it directly discloses the expected signature, the caller could simply update to the expected signature, and re-execute the call successfully.

Is returning the expected signature actually useful for debugging? If it's not, then perhaps we could strike it completely. If it _is_, perhaps instead we could do something like:

```
log.Debugf(""Expected signing signature: %s, but computed: %s", hex.EncodeToString(v.signature), hex.EncodeToString(computed)")
return fmt.Errorf("Computed unexpected signature of: %s", hex.EncodeToString(v.signature), hex.EncodeToString(computed))
```

Am I missing something here? Let me know. If this seems reasonable, I'm happy to open a pull request, just want to check with maintainers first. Thank you!

**Comment by kanata2** [comment]
Hi @tyrannosaurus-becks,

Sorry for slow response.
I generally agree with your concerns and suggestions.

> Is returning the expected signature actually useful for debugging? If it's not, then perhaps we could strike it completely. If it is, perhaps instead we could do something like:

As for the latter, I personally think it looks good to be able to output if needed.

**Comment by tyrannosaurus-becks** [comment]
Ah cool! Thanks for the feedback.

I will open a PR offering the debugging option.
