### ISSUE TITLE
The way of displaying divider in context block

### ISSUE THREAD

**Issue by nnn406** [slack-go/slack#852]
Hi folks,

first of all, thanks for the package it's awesome!

I'm quite new in GoLang and maybe that's why I'm suffering a bit with the following question

I'm trying to fetch from the DB and post a bunch of the rows into one Slack message.

```
var resultSection = make([]slack.MixedElement, 0)
...
for _, t := range bs {
  var text, image slack.MixedElement
  text = slack.NewTextBlockObject("mrkdwn", fmt.Sprintf("%s", t.Name), false, false) // I've tried to add \n at the end of the string, did not help :(
  resultSection = append(resultSection, text)
  // <--- how to add here a divider slack.NewDividerBlock() in a final message
}

msg := slack.MsgOptionBlocks(
  slack.NewSectionBlock(headerText, nil, nil),
  slack.NewContextBlock(
    "",
    resultSection...,
  ),
)
```

basically from the code above you may see that I'm going over the slice of data from the DB and generating the message based on that, however, the final result shown in one line. 

How can I separate one from the other (newline)?

**Comment by kanata2** [comment]
Do you mean you want to display a pair of image and text per row and put a divider between the rows?
You cannot use divider in a single context block. ( https://api.slack.com/reference/block-kit/blocks#context )
So it seems to be a good idea to have one context block per row and put a divider block between the rows.

**Comment by kanata2** [comment]
Closed this issue, but feel free to re-open if you have any additional questions.
