### ISSUE TITLE
Deprecating usage of token as a query string parameter in Web API requests

### ISSUE THREAD

**Issue by eliot-stripe** [slack-go/slack#857]
Slack announcement (2020-11-30): https://api.slack.com/changelog/2020-11-no-more-tokens-in-querystrings-for-newly-created-apps

Based on my initial splunking, it looks like `getResource` passes the the request parameters as a URL parameters: https://github.com/slack-go/slack/blob/853f55b35241219807941e42914bfc7905afb4c8/misc.go#L259-L268

The callsites of this include `token` as one of those URL parameters: https://github.com/slack-go/slack/blob/master/chat.go#L696-L714

It's possible that other http methods do as well, but I haven't done an exhaustive search of the codebase.

**Comment by kanata2** [comment]
Fixed in v0.8.3
