### ISSUE TITLE
Minor enhancement for "Style" object

### ISSUE THREAD

**Issue by sryoya** [slack-go/slack#874]
### Description

**About**
A minor enhancement for the readability and usability of API
It's about `Style`, a type definition used for setting a style of a button in a few elements

**Problem**
1. Naming
I feel `Style` is a little vague consider it's on `slack` package and shared by most of the resources.
It seems to be used just for the button. So, it may want to be `ButtonStyle`

2. Used scope
It's shared by both Block Element and Confirmation Dialog. But, according to the API definitions (See the below reference), the rules are a little different about the default setting.
It doesn't have the critical difference now, but we may want to have a separate definition.

**Suggestion**
1. Change the name to `ButtonStyle`
2. Change the setter function name to `WithButtonStyle`
3. Create the separate definition for Confirmation Dialog like `ConfirmationButtonStyle`

**Background**
I thought when implementing #873
But, didn't fix in that considering the compatibility with the old versions.

### (Optional) Slack's documentation
[Slack API Button element](https://api.slack.com/reference/block-kit/block-elements#button)
[Slack API Composition Object](https://api.slack.com/reference/block-kit/composition-objects#confirm)

**Comment by kanata2** [comment]
resolved by #873
