### ISSUE TITLE
UpdateMessage (chat.update) doesn't allow to pass other parameters

### ISSUE THREAD

**Issue by abourget** [slack-go/slack#89]
I want to call `chat.update` with `parse=full` or some of the other optional arguments here: https://api.slack.com/methods/chat.update#formatting

The current UpdateMessage function doesn't allow us to do that. I was wondering, would we:
1. create a new function like `UpdateMessageEx()`?! so we feel in Windowzland somehow
2. change the signature and use something like PostMessage() instead, with a parameter struct ?

**Comment by erizocosmico** [comment]
Just implemented that feature here: https://github.com/nlopes/slack/pull/93
If you need the feature you can use the master of my fork until it gets merged.

**Comment by dotdotdotpaul** [comment]
So the PR mentioned here was closed over a year ago (October 2016) with a comment from nlopes about how it would be pulled in "soon".  What's the status on this feature?  Not being able to update attachments on a message is a serious drawback.

**Comment by ruudk** [comment]
+1 :pray:

**Comment by dotdotdotpaul** [comment]
To be fair, you can do this with `SendMessageContext` directly, but it seems like it would be nicer to have a formal function to mirror the posting.

```
slack.SendMessageContext(
    context.Background(),
    channel,
    slack.MsgOptionText(text, params.EscapeText),
    slack.MsgOptionAttachments(params.Attachments...),
    slack.MsgOptionPostMessageParameters(params),
    slack.MsgOptionUpdate(timestamp))
```

**Comment by ruudk** [comment]
Nice, thanks for posting this 👌👍
