### ISSUE TITLE
AuthTest Returns Invalid_Auth for Bot User Token

### ISSUE THREAD

**Issue by moss-n** [slack-go/slack#903]
### What happend
I attempted to use the UploadFile function to upload a file to a workspace. When calling UploadFile, the function returns an error "invalid_auth". I confirmed that the file:write scope was provided to the bot user token, and I was able to successfully use the token when calling GetUserInfo. I noticed that GetUserInfo does not first call AuthTest before making the request, unlike FileUpload

### Expected behavior
Expected that when FileUpload was called with the given params, it would upload the text file I provided in the params argument 

### Steps to reproduce
This is my program 

```
import (
	"fmt"
	"github.com/slack-go/slack"
)

func main() {
	api := slack.New("TOKEN")

	params := slack.FileUploadParameters{
		File: "test.txt",
	}
	file, err := api.UploadFile(params)

	if err != nil {
		fmt.Printf("%s\n", err)
		return
	}

	fmt.Printf("Name: %s, URL: %s\n", file.Name, file.URL)
}
```

### Versions
- Go: go version go1.15.8 
- slack-go/slack: latest

**Comment by aubelsb2** [comment]
I'm also getting the same issue with both an user token and a bot token.. My permission are as follows:
Bot scopes: (xoxb-)
channels:history channels:join channels:read chat:write files:read files:write users:read
User scopes: (xoxp-)
channels:history channels:read chat:write files:read files:write users:read

The code is as follows:
```
	sf, err := api.UploadFile(slack.FileUploadParameters{
		Reader:   bytes.NewReader(bimg.Bytes()),
		Filename: fmt.Sprintf("%s.png", rightnow.Format("2006-01-02T15")),
		Channels: []string{wfo_wfh.ChannelId},
		InitialComment: "Auto generated",
	})

```

The token is being used for other things successfully.

**Comment by aubelsb2** [comment]
Ok a little digging, uploads only work if you use the "Content" method right now. I tested my token against with CURL and it worked as expected so it's a library issue.

**Comment by aubelsb2** [comment]
```
 curl -F file=@slack_api_logo_vogue.png -H "Authorization: Bearer xoxp-" -F channels=ASDF https://slack.com/api/file
s.upload
```

**Comment by aubelsb2** [comment]
Okay as far as I can tell it's because the authorization token is missing
https://github.com/slack-go/slack/pull/908

**Comment by aubelsb2** [comment]
Ok I think I solved the issue:
https://github.com/slack-go/slack/pull/908

**Comment by aubelsb2** [comment]
(Tested too.)

**Comment by moss-n** [comment]
Thank you for taking a look at this issue, @aubelsb2!

**Comment by kanata2** [comment]
Is this problem caused by https://github.com/slack-go/slack/issues/857 ?

**Comment by aubelsb2** [comment]
@kanata2 Yes I believe so.

**Comment by evgmoskalenko** [comment]
Hello, I still don't understand how you solved this problem

**Comment by kanata2** [comment]
Please use the latest version.
If you are still experiencing problems, please report with a new issue.
