### ISSUE TITLE
Implement the `channel_id_changed` event type for the Events API

### ISSUE THREAD

**Issue by seanami** [slack-go/slack#909]
### Description

I need my app to listen to the `channel_id_changed` event from Slack's Events API so that I can update records that store channel IDs on my side. However, I don't see this event available in the library implementation.

Is it possible to monkey-patch or add my own additional event type? (I couldn't find documentation on this.) Or is it possible to get this added to the library so that I can listen for this event?

### (Optional) Slack's documentation

https://api.slack.com/events/channel_id_changed

**Comment by xNok** [comment]
I would suggest to fork the repo. Implement the feature. You probably need to add an *event type* and the struct to receive that event.

In order tu use you own fork you need to add a replace statement in your `go.mod`. 

```
replace github.com/slack-go/slack => github/seanami/slack
```

Then running `go mod tidy` to re-evaluate go.mod. After that you would be using your own fork until your PR gets added to the repository. 😉

**Comment by DestroyerAlpha** [comment]
This issue can be closed right @kanata2?
