### ISSUE TITLE
json: cannot unmarshal string into Go value of type int64

### ISSUE THREAD

**Issue by andrewarrow** [slack-go/slack#92]
more info coming soon, but get that after calling `GetGroupHistory` for 1 specific group and then looping thru:

```
for _, message := range history.Messages
```

**Comment by kodieGlosser** [comment]
@andrewarrow I was seeing a similar error with one of our slack servers. 

I found the bit it was unable to unmarshal. 
https://github.com/nlopes/slack/blob/master/attachments.go#L75

Looking at the call to our slack server 
https://slack.com/api/rtm.start
token=xxxxxxxxxxxxxx

The json output for the this is datatype string and NOT int64. 

I have also noticed with another one of our slack servers, where we do not have this problem, that it does not return "Attachments".

I can see now this is being discussed in issue #90

**Comment by andrewarrow** [comment]
@kodieGlosser i'm not seeing this error any more, but I think I muted the group in question causing my problem. In my project I cache each room to disk, so running `touch cache/roomname/mute` the very presency of that mute file is the binary on/off value for muting. That's not really revelent to this discussion but I think it's cool. I love muting channels by just touching a file from the command line.

**Comment by stevenpoitras** [comment]
Seems like I'm hitting this as well, works fine for some messages but not all.  Changing the type to string worked for my scripts

**Comment by mehlium** [comment]
I'm having this problem as well. It was indeed introduced in https://github.com/nlopes/slack/pull/81 and the Slack API specifies TS as an Integer, however the json presents the value as a String.

I've created a fix for this issue in https://github.com/nlopes/slack/pull/96

**Comment by kulak-at** [comment]
I have the same issue as well, just for some of messages, not for all of them.

**Comment by postromantic** [comment]
#96 is not a fix for it. `Ts` should have `string` type, not int64. In my case `"ts":"1473362325.000027"` - it doesn't look like int :-)

**Comment by andrewarrow** [comment]
u don't want string you want `float64`

**Comment by andrewarrow** [comment]
then int64(ts) to go from 1473362325.000027, to 1473362325

**Comment by tobert** [comment]
IIRC Slack's docs say it's a string and should not be stored as a float. I can't find the link at the moment. The timestamp is also a message ID and a change in precision would render it incorrect. This is why they send it as a string.

**Comment by andrewarrow** [comment]
alright let's store it as a string but have two functions to get either part of the number. The string before the dot and the string after. And then might as well have two more functions for getting both those fields as ints or as parsed Time thingys not really objects cuz golang doesn't have objects.

**Comment by mehlium** [comment]
Ah, I didn't know that the `ts` could be _that_ precise. Yeah, sounds like the field should be treated as a string in the model.

**Comment by postromantic** [comment]
Slack discussion about `ts` field: https://github.com/slackhq/slack-api-docs/issues/7#issuecomment-67913241

**Comment by tonka3000** [comment]
Hey,

i'm also having this problem. Tried a8ceb9de0aca0376b293f159bbfb8a6aac72fade (latest commit at the time) which seems to address these issue but i'm also getting this error

> reconnection 4 failed: post: json: invalid use of ,string struct tag, trying to unmarshal unquoted value into int64

**Comment by adyatlov** [comment]
Hi everyone,

Unfortunately, Slack still can send a number instead of a string in the `message.attachments.ts` field. So after fetching #99, I'm getting `json: cannot unmarshal number into Go value of type string` instead of the initial `json: cannot unmarshal string into Go value of type int64 #92`.

**Comment by saxsir** [comment]
I'm having same problem. (getting `json: cannot unmarshal number into Go value of type string`)

How is use `json.Number` instead of `string` ?
https://golang.org/pkg/encoding/json/#Number

Type `json.Number` is an alias for `string`.

http://stackoverflow.com/questions/24480835/go-decoding-json-int-into-string

**Comment by postromantic** [comment]
@saxsir yep, looks like `json.Number` will cover both cases:
https://play.golang.org/p/75NwTQT-MG

**Comment by jpbruinsslot** [comment]
@saxsir his solution fixes it for me too

**Comment by saxsir** [comment]
plz close this issue, thx.
