### ISSUE TITLE
Support custom text for slack notification display

### ISSUE THREAD

**Issue by melisa92** [slack-go/slack#932]
### Description
The Slack API supports custom notification text in message payload. However, slack-go does not have support for this:
https://github.com/slack-go/slack/blob/045896a636192db130c0b23a36fa578be9d68404/chat.go#L251-L268

### (Optional) Slack's documentation
https://api.slack.com/messaging/composing/layouts#add_blocks_array

**Comment by kkoji** [comment]
@melisa92 
You can customize the notification message with the following code.

```
package main

import (
	"context"
	"fmt"

	"github.com/slack-go/slack"
)

func main() {
	api := slack.New("token")
	ctx := context.Background()
	api.SendMessageContext(
		ctx,
		"channelID",
		slack.MsgOptionText("New Paid Time Off request from Fred Enriquez",false),
		slack.MsgOptionBlocks(
			slack.NewHeaderBlock(
				&slack.TextBlockObject{
					Type: "plain_text",
					Text: "New request",
				},
			),
		),
	)
}
```

The text of `slack.MsgOptionText("New Paid Time Off request from Fred Enriquez",false)` appears in the notification, is this what you wanted to achieve?

**Comment by kanata2** [comment]
Thanks @kkoji ☺️ 

@melisa92 
If the above answer solves the problem, I'd like to close it, is that okay?
