### ISSUE TITLE
Add Dispatch action config to InputBlock struct

### ISSUE THREAD

**Issue by adezxc** [slack-go/slack#935]
### Description

Add Dispatch action config to InputBlock struct

**Comment by oogali** [comment]
Relates to https://github.com/slack-go/slack/pull/835?

**Comment by adezxc** [comment]
Yes, the same, but it wasn't merged from what I see.

**Comment by jromualdez-mulesoft** [comment]
Will this feature be added any time soon or is there a possible workaround to modify the dispatch_action_config?

**Comment by karl-johan-grahn** [comment]
@kanata2 will https://github.com/slack-go/slack/pull/835 be merged so the dispatch action config can be added?

**Comment by karl-johan-grahn** [comment]
Created https://github.com/slack-go/slack/pull/977
