### ISSUE TITLE
Support Events API

### ISSUE THREAD

**Issue by dougnukem** [slack-go/slack#94]
Slack announced a new Events API which provides similiar functionality to the Real-time message API (RTM) but with a simpler webhook interface.
- https://api.slack.com/events-api
- https://api.slack.com/faq#events_api

**Comment by james-lawrence** [comment]
will review/accept PRs for this.

high level requirements:
- don't implement the handler, that is application dependent.
- do implement the data structures and utility functions to reduce the http handler to a few lines.

**Comment by james-lawrence** [comment]
closing as we have basic support.
