### ISSUE TITLE
/slack-test/ README.md seems a bit out of date?

### ISSUE THREAD

**Issue by jc-dgit** [slack-go/slack#948]
### What happened

Noticed the README.md in the /slack-test/ directory:

```
code in this package was shamelessly copied from https://github.com/lusis/slack-test.
since we were unable to get a response from the maintainer and its lack of license
have left us in an odd state. but wanted to move it here for maintenance purposes.
```

Looking at the source repo:

* The author has [added a license](https://github.com/lusis/slack-test/blob/master/LICENSE)
* ... and updated their repo README.md to [point at slack-go as the new proper home](https://github.com/lusis/slack-test/commit/c40012f200185bff75d89262658800b58e713374).

Seems like the /slack-test/ repo readme should probably be updated?

**Comment by kanata2** [comment]
@jc-dgit I've submitted PR #1010. Could you review it when you get some time?
