### ISSUE TITLE
mapping channel names to ids

### ISSUE THREAD

**Issue by mischief** [slack-go/slack#95]
hi, i'm wondering how to map a channel name (`#general`) to an ID or vice-versa.

in my code i would like to be able to write e.g. `JoinChannel("#general")` but to do that i need to get the channel id.

`Channel` type does not expose ID or name, so i am confused about how `GetChannels` or `GetChannelInfo` is useful...

**Comment by leavengood** [comment]
Hi, I'm not the author of this package, but a recent new user. The `Channel` type does have an ID: it is part of the `groupConversation` struct which is embedded in `Channel`. When you get a ConnectedEvent it has the channel list in the `Info`, so you can build a map of channel names to either Channel structs or IDs to be able to do what you want. At least that is what I did in my code.

**Comment by tobert** [comment]
There are API methods to look up channels and users by ID and get detailed information. In my bot, I cache these in a pair of map[string]string so I can do quick lookups in both ways. It falls through to querying the Slack API when an ID isn't in the maps.

https://github.com/Netflix/hal-9001/blob/master/brokers/slack/broker.go#L539

**Comment by dvdplm** [comment]
@leavengood is correct. Closing.
