### ISSUE TITLE
Is there a limit on `[]*slack.TextBlockObject` about blocks?

### ISSUE THREAD

**Issue by iamrajiv** [slack-go/slack#956]
## Description

Getting 400 Bad Request for Slack App Webhook URL.

**Comment by kanata2** [comment]
Please give me more details.

**Comment by iamrajiv** [comment]
@kanata2 I am trying to send a slack message to the channel so I have written the below code

```go
    var str_array []*slack.TextBlockObject
    for i := 1; i < 10; i++ {
        str := fmt.Sprintf("Block Number%v", i)
        str_object := slack.TextBlockObject{
            Text: str,
            Type: "mrkdwn",
        }
        str_array = append(str_array, &str_object)
    }

    str_section := slack.NewSectionBlock(nil, str_array, nil)

    blocks := slack.Blocks{BlockSet: []slack.Block{
        str_section}}
```

When I do `go run main.go` message is sent to the channel but when I change the for loop to this `for i := 1; i < 20; i++` i.e. when I increase the blocks it says `slack server error: 400 Bad Request`.

**Comment by kanata2** [comment]
This is Slack's specification, as desribed below.

> Required if no text is provided. An array of text objects. Any text objects included with fields will be rendered in a compact format that allows for 2 columns of side-by-side text. Maximum number of items is 10. Maximum length for the text in each item is 2000 characters. Click here for an example.
-- ref: https://api.slack.com/reference/block-kit/blocks#section
