### ISSUE TITLE
About the lack of a Hint field in NewInputBlock function

### ISSUE THREAD

**Issue by deto-r** [slack-go/slack#964]
Is there any reason why the `NewInputBlock` doesn't have a Hint field? 

```
func NewInputBlock(blockID string, label *TextBlockObject, element BlockElement) *InputBlock {
	return &InputBlock{
		Type:    MBTInput,
		BlockID: blockID,
		Label:   label,
		Element: element,
	}
}
```

If not, I will send a PR.

**Comment by kanata2** [comment]
Probably not particularly. (Maybe it was added later.)

> If not, I will send a PR.

👍

**Comment by deto-r** [comment]
Hi,Thanks for the reply.
I've sent out a PR, please check it out.
