### ISSUE TITLE
long message text got split

### ISSUE THREAD

**Issue by yongzhang** [slack-go/slack#972]
### What happened
Hi, I have a function like this:
```
func ReplyMsg(channel, timestamp, text string) error {
	api, err := NewSlackClient()
	if err != nil {
		return err
	}

	_, _, err = api.PostMessage(
		channel,
		slacklib.MsgOptionTS(timestamp),
		slacklib.MsgOptionText(text, false),
	)
	return err
}
```
When I give a long message text, I receive 2 slack messages in split, total chars is about 4900. Can I get a single message?

### Expected behavior
Receive a single message.

### Versions
- Go: 1.16
- slack-go/slack:  v0.9.4

**Comment by kanata2** [comment]
Slack has the following limitation.

> The message server will disconnect any client that sends a message longer than 16 kilobytes. This includes all parts of the message, including JSON syntax, not just the message text. Clients should limit messages sent to channels to 4000 characters, which will always be under 16k bytes even with a message comprised solely of non-BMP Unicode characters at 4 bytes each.
-- https://api.slack.com/docs/rate-limits

How about using a Snippet or  a Post?

**Comment by yongzhang** [comment]
> Slack has the following limitation.
> 
> > The message server will disconnect any client that sends a message longer than 16 kilobytes. This includes all parts of the message, including JSON syntax, not just the message text. Clients should limit messages sent to channels to 4000 characters, which will always be under 16k bytes even with a message comprised solely of non-BMP Unicode characters at 4 bytes each.
> > -- https://api.slack.com/docs/rate-limits
> 
> How about using a Snippet or a Post?

Thanks, yes I got the answer already and successfully send the text with Snippet.
