### ISSUE TITLE
Unable to produce an input block with the ability to select users

### ISSUE THREAD

**Issue by karl-johan-grahn** [slack-go/slack#974]
### What happened
I am unable to reproduce this modal payload from the Block Kit Builder:
```
{
	"type": "modal",
	"title": {
		"type": "plain_text",
		"text": "My App",
		"emoji": true
	},
	"submit": {
		"type": "plain_text",
		"text": "Submit",
		"emoji": true
	},
	"close": {
		"type": "plain_text",
		"text": "Cancel",
		"emoji": true
	},
	"blocks": [
		{
			"type": "input",
			"element": {
				"type": "users_select",
				"placeholder": {
					"type": "plain_text",
					"text": "Select a user",
					"emoji": true
				}
			},
			"label": {
				"type": "plain_text",
				"text": "Choose user",
				"emoji": true
			}
		}
	]
}
```

Tried this:
```
label := slack.NewTextBlockObject(slack.PlainTextType, "Choose user", false, false)
blockElement := slack.NewOptionsSelectBlockElement(slack.OptTypeUser, "Select a user", "user", nil)
block := slack.NewInputBlock("user", label, blockElement)
```
but getting error "invalid_arguments", message "Error opening view".

### Expected behavior
Expecting to be able to produce an input block containing a user select dropdown list.

### Versions
- Go: 1.17.1
- slack-go/slack: v0.6.6

**Comment by kanata2** [comment]
Could you try with the latest version(= v0.9.5)?
If you encounter the same problem, it would be helpful if you could share all the reproducible code with us.

**Comment by karl-johan-grahn** [comment]
I tried `v0.9.5` and same problem.

You can reproduce the problem by updating the example https://github.com/slack-go/slack/blob/master/examples/modal_users/users.go - replace `NewSectionBlock` with the lines above.

In https://github.com/slack-go/slack/blob/master/block_element.go it says `NewOptionsSelectBlockElement returns a new instance of SelectBlockElement for use with the Options object only` - what does the `Options object` refer to, what kind of block is that?

**Comment by karl-johan-grahn** [comment]
Is a `NewUsersSelectBlockElement` missing?

**Comment by karl-johan-grahn** [comment]
Some progress, after reading this blog https://sho-memo01.blogspot.com/2020/09/slack-go.html I could see the `NewOptionsSelectBlockElement` should be specified like:
```
blockElement := slack.NewOptionsSelectBlockElement(slack.OptTypeUser, "Select a user", "user")
```
however the payload from the modal view request does not contain the chosen user.

**Comment by karl-johan-grahn** [comment]
This can be closed, I updated example
