### ISSUE TITLE
Add slacktest licence

### ISSUE THREAD

**Issue by aelse** [slack-go/slack#979]
### What happened

slack-go/slack/slacktest readme indicates some licensing difficulty. This appears to have been resolved as https://github.com/lusis/slack-test is licensed under the MIT license.

### Expected behavior

The slack-go/slack or slack-go/slack/slacktest documentation should reflect the correct license state of this code.

### Versions
- Go:
- slack-go/slack:

**Comment by kanata2** [comment]
@aelse I've submitted PR #1010. Could you review it when you get some time?

**Comment by aelse** [comment]
@kanata2 Happy to review.

The LICENSE file in the slacktest repo includes this sentence:

```The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.```

I think the correct thing to do to comply with the terms of the license is to copy the LICENSE file verbatim from the slack-test repo. To avoid confusion you could remove the license information from the CREDITS file.

**Comment by kanata2** [comment]
@aelse 
Thanks for your feedback!
I removed CREDITS and added the full text of the license in README.

**Comment by aelse** [comment]
lgtm thank you
