### ISSUE TITLE
Add support for `cookie` HTTP header

### ISSUE THREAD

**Issue by pbar1** [slack-go/slack#996]
### Description

Slack has multiple different types of API tokens, each identified by a specific prefix. For example, bot users have a token prefixed with `xoxb`.

Using browser devtools, one can inspect HTTP requests with Slack and see that the UI is communicating with the API using a special token prefixed with `xoxc`. This token functions similarly to a standard Slack token, with the caveat that it only works with the HTTP header `cookie` also set.

Support for setting the `cookie` header would enable using `xoxc` tokens with this library. An example use case for them would be developing locally, as having to make a bot user is extra overhead when trying out new ideas. 

### (Optional) Slack's documentation

This is undocumented behavior. However, here is some unofficial discussion on the subject:
- https://github.com/adsr/irslackd/issues/84
- https://github.com/adsr/irslackd/wiki/IRC-Client-Config#xoxc-tokens

**Comment by rusq** [comment]
@pbar1 you can check [github.com/rusq/slack](https://github.com/rusq/slack) (a fork with cookie support)
```
slack.New(token, slack.OptionCookie(cookie))
```

**Comment by nolanlum** [comment]
@rusq Is there a reason you haven't opened a PR to get cookie support merged into upstream?

**Comment by rusq** [comment]
@nolanlum I'd be happy to, would save me from merging the upstream updates every now and then.  Saw there's already a PR with "thinking" state, and this very issue with no attention, and thought there's no interest in this.  Can submit a PR, no problem.

**Comment by rusq** [comment]
I left the same comment in the PR, but will copy here for convenience:

Whoever's going to be searching for this, the solution is already there, no need to build anything custom:
- I was able to work around that by using a custom `http.Client` with a cookie jar and passing `OptionHTTPClient` to slack.New. [Example](https://github.com/rusq/slackdump/blob/85358171b3fd3c44e78f82e4dbd684d84eb4be74/slackdump.go#L116)

You can grab the chttp implementation from slackdump or BYO.

Thanks, you're welcome. Closing this.

**Comment by rusq** [comment]
Can't self-close the issue.
