### ISSUE TITLE
The value contained `message_ts` in LinkShared event is not only a timestamp

### ISSUE THREAD

**Issue by toshok** [slack-go/slack#998]
we're seeing a lot of failures to unmarshal events from slack to their respective event structs, so I went looking to see if there was something amiss.  I found a number of places in `inner_events.go` where `event_ts` is defined as a `json.Number`:

```
	EventTimeStamp json.Number `json:"event_ts"`
```

but i can't find any mention  of `event_ts` in the spec (https://github.com/slackapi/slack-api-specs/blob/760ee9843ec8045ce3f62edd451751b0353acead/events-api/slack_events_api_async_v1.json) where the type is anything other than `string`.

I haven't tracked the errors down to event_ts specifically, but the failures are universally attempts to unmarshal uuids string as `json.Number`, which fails.

**Comment by kanata2** [comment]
If `event_ts`'s value is like `"1611456175.413379"`, `json.Number` type can handle it correctly.
Could you give me the steps to reproduce it for investigation?

**Comment by toshok** [comment]
did a little more digging into the spec/docs and found some text that may be of use.  I haven't actually dumped the problematic payload bodies (will do that next).  It looks like `message_ts` is the likely culprit.

from https://api.slack.com/events/link_shared

> Take care with the message_ts and channel fields. When the source of this event is the message composer, rather than a posted message, these values don't correspond to typical timestamps and channels

Then further down there's an example payload of what a link_shared event looks like from the message composer, and:

```
    "message_ts": "Uxxxxxxx-909b5454-75f8-4ac4-b325-1b40e230bbd8-gryl3kb80b3wm49ihzoo35fyqoq08n2y",
```

The error I'm seeing in our app is:
```
EventsAPI Error parsing inner event: unmarshalling_error, json: invalid number literal, trying to unmarshal "\"U........ (uuid here) .....\"" into Number
```

`message_ts` is also defined to be a `json.Number`.

**Comment by kanata2** [comment]
This specification is so weird...but we should fix it.
Thanks for reporting and investigating.

**Comment by toshok** [comment]
verified that switching `message_ts` to `string` fixes the error, and also fixes link_shared unfurls in the message compose area.

it's a one-liner in the struct definition, but obviously a breaking change.  ~should I open a PR to discuss further?~ in order to reduce synchronization costs, I went ahead and did it - #999.

**Comment by abustany** [comment]
In general, if we believe [that message](https://github.com/slackhq/slack-api-docs/issues/7#issuecomment-67913241) from a Slack engineer (?), the `ts`/`event_ts` fields should be parsed as strings always. That would be a breaking API change for slack-go, but if we consider that it's fixing a bug it's maybe fine? It'd also ensure all `EventTimestamp` fields on inner events have the same types, currently some are `json.Number` while others are `string`...
